// angular/angular/src/app/feature-module/ui-interface/base-ui/ui-tooltips/ui-tooltips.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../../shared/routes/routes';

@Component({
    selector: 'app-ui-tooltips',
    templateUrl: './ui-tooltips.component.html',
    styleUrl: './ui-tooltips.component.scss',
    standalone: false
})
export class UiTooltipsComponent {
  public routes = routes;
  html = `<em>Tooltip</em> <u>with</u> <b>HTML</b>`;
  content = 'Disabled tooltip';

  primary = `<p class="btn-primary">Primary Tooltip</p>`;
  secondary = `<div class="btn-secondary">Secondary Tooltip</div>`;
  warning = `<div>Warning Tooltip</div>`;
  info = `<div>Info Tooltip</div>`;
  success = `<div class="btn-success">Success Tooltip</div>`;
  danger = `<div class="btn-danger">Danger Tooltip</div>`;
  light = `<div class="btn-light">Light Tooltip</div>`;
  dark = `<div class="btn-dark">Dark Tooltip</div>`;

  icon1 = `Marina Kai`;
  icon2 = `Alex Carey`;
  icon3 = `Maria John`;

  link = `Link Tooltip`
}

<!-- Page Header -->
<div class="page-header">
    <div class="row">
        <div class="col-sm-12">
            <h3 class="page-title">Tooltip</h3>
        </div>
    </div>
</div>
<!-- /Page Header -->

<div class="row">

    <!-- Colored Tooltips -->
    <div class="col-xl-12">
        <div class="card">
            <div class="card-header justify-content-between">
                <div class="card-title">
                    Colored Tooltips
                </div>
            </div>
            <div class="card-body">
                <div class="btn-list custom-btn-tooptip-class">
                    <div class="tooltip-content-primary">
                        <ng-template #popTemplate1>
                            <div [innerHtml]="primary"></div>
                        </ng-template>
                        <button type="button" class="btn btn-primary" [tooltip]="popTemplate1">
                            Primary Tooltip
                        </button>
                    </div>
                    <div class="tooltip-content-secondary">
                        <ng-template #popTemplate2>
                            <div [innerHtml]="secondary"></div>
                        </ng-template>
                        <button type="button" class="btn btn-secondary" [tooltip]="popTemplate2">
                            Secondary Tooltip
                        </button>
                    </div>
                    <div class="tooltip-content-warning">
                        <ng-template #popTemplate3>
                            <div [innerHtml]="warning"></div>
                        </ng-template>
                        <button type="button" class="btn btn-warning" [tooltip]="popTemplate3">
                            Warning Tooltip
                        </button>
                    </div>
                    <div class="tooltip-content-info">
                        <ng-template #popTemplate4>
                            <div [innerHtml]="info"></div>
                        </ng-template>
                        <button type="button" class="btn btn-info" [tooltip]="popTemplate4">
                            Info Tooltip
                        </button>
                    </div>
                    <div class="tooltip-content-success">
                        <ng-template #popTemplate5>
                            <div [innerHtml]="success"></div>
                        </ng-template>
                        <button type="button" class="btn btn-success" [tooltip]="popTemplate5">
                            Success Tooltip
                        </button>
                    </div>

                    <div class="tooltip-content-danger">
                        <ng-template #popTemplate6>
                            <div [innerHtml]="danger"></div>
                        </ng-template>
                        <button type="button" class="btn btn-danger" [tooltip]="popTemplate6">
                            Danger Tooltip
                        </button>
                    </div>
                    <div class="tooltip-content-light">
                        <ng-template #popTemplate7>
                            <div [innerHtml]="light"></div>
                        </ng-template>
                        <button type="button" class="btn btn-light" [tooltip]="popTemplate7">
                            Light Tooltip
                        </button>
                    </div>

                    <div class="tooltip-content-dark">
                        <ng-template #popTemplate8>
                            <div [innerHtml]="dark"></div>
                        </ng-template>
                        <button type="button" class="btn btn-dark" [tooltip]="popTemplate8">
                            Dark Tooltip
                        </button>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- /Colored Tooltips -->

</div>

<div class="row">

    <!-- Html Element -->
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Html Element</h5>
            </div>
            <div class="card-body">
                <div class="popover-list">
                    <button class="example-popover btn btn-primary" type="button" data-container="body"
                        data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="Popover title"
                        tooltip="Popover title" placement="top">Hover Me</button>
                </div>
            </div>
        </div>
    </div>
    <!-- /Html Element -->

    <!-- Direction Tooltip -->
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Direction Tooltip</h5>
            </div>
            <div class="card-body">
                <div class="tooltip-list">
                    <button type="button" class="btn btn-primary me-1" data-bs-toggle="tooltip" data-bs-placement="top"
                        title="" data-bs-original-title="Tooltip on top" tooltip="Tooltip on top" placement="top">
                        Tooltip on top
                    </button>
                    <button type="button" class="btn btn-primary me-1" data-bs-toggle="tooltip"
                        data-bs-placement="right" title="" data-bs-original-title="Tooltip on right"
                        tooltip="Tooltip on right" placement="right">
                        Tooltip on right
                    </button>
                    <button type="button" class="btn btn-primary me-1" data-bs-toggle="tooltip"
                        data-bs-placement="bottom" title="" data-bs-original-title="Tooltip on bottom"
                        tooltip="Tooltip on bottom" placement="bottom">
                        Tooltip on bottom
                    </button>
                    <button type="button" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="left"
                        title="" data-bs-original-title="Tooltip on left" tooltip="Tooltip on left" placement="left">
                        Tooltip on left
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- /Direction Tooltip -->

    <!-- Html Element -->
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Html Element</h5>
            </div>
            <div class="card-body">
                <div class="popover-list">
                    <ng-template #popTemplate9>
                        <div [innerHtml]="html"></div>
                    </ng-template>
                    <button type="button" class="btn btn-primary me-1" [tooltip]="popTemplate9">
                        Tooltip with HTML
                    </button>
                    <ng-template #popTemplate10>
                        <div [innerHtml]="html"></div>
                    </ng-template>
                    <button type="button" class="btn btn-primary me-1" [tooltip]="popTemplate10" triggers="click">
                        Click Me
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- /Html Element -->

    <!-- Tooltip -->
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Disabled Elements</h5>
            </div>
            <div class="card-body">
                <span class="d-inline-block" tabindex="0" data-bs-toggle="tooltip">
                    <button class="custom-disabled btn btn-primary" type="button" [tooltip]="content" placement="top" container="body">
                       Disabled button
                    </button>
                </span>
            </div>
        </div>
    </div>
    <!-- /Tooltip -->

    <!-- Tooltip Links -->
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Tooltips on Links</h5>
            </div>
            <div class="card-body">
                <p class="text-muted mb-0 custom-link-tooltip">
                    Hover on the link to view the 
                    <ng-template #popTemplate14>
                        <div [innerHtml]="link"></div>
                    </ng-template>
                    <a href="javascript:void(0);" data-bs-toggle="tooltip"
                        data-bs-custom-class="tooltip-primary" class="text-primary" tooltip="Link Tooltip"
                        placement="auto">Tooltip</a>
                </p>
            </div>
        </div>
    </div>
    <!-- /Tooltip Links -->

    <!-- Tooltip Images -->
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Tooltip For Images</h5>
            </div>
            <div class="card-body tooltip-icon-custom-wrapper">
                <a href="javascript:void(0);" data-bs-toggle="tooltip" data-bs-custom-class="tooltip-primary"
                    class="avatar avatar-md me-2 online avatar-rounded" [tooltip]="popTemplate11" placement="auto">
                    <img src="assets/img/profiles/avatar-01.jpg" alt="img">
                </a>
                <ng-template #popTemplate11>
                    <div [innerHtml]="icon1"></div>
                </ng-template>
                <a href="javascript:void(0);" data-bs-toggle="tooltip" data-bs-custom-class="tooltip-primary"
                    class="avatar avatar-lg me-2 online avatar-rounded" [tooltip]="popTemplate12" placement="auto">
                    <img src="assets/img/profiles/avatar-02.jpg" alt="img">
                </a>
                <ng-template #popTemplate12>
                    <div [innerHtml]="icon2"></div>
                </ng-template>
                <a href="javascript:void(0);" data-bs-toggle="tooltip" data-bs-custom-class="tooltip-primary"
                    class="avatar avatar-xl me-2 online avatar-rounded" [tooltip]="popTemplate13" placement="auto">
                    <img src="assets/img/profiles/avatar-03.jpg" alt="img">
                </a>
                <ng-template #popTemplate13>
                    <div [innerHtml]="icon3"></div>
                </ng-template>
            </div>
        </div>
    </div>
    <!-- /Tooltip Images -->

</div>

// vue/vue/src/views/pages/uiinterface/baseui/ui-tooltips.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper cardhead">
    <div class="content">
      <!-- Page Header -->
      <div class="page-header">
        <div class="row">
          <div class="col-sm-12">
            <h3 class="page-title">Tooltip</h3>
          </div>
        </div>
      </div>
      <!-- /Page Header -->

      <div class="row">
        <!-- Colored Tooltips -->
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header justify-content-between">
              <div class="card-title">Colored Tooltips</div>
            </div>
            <div class="card-body">
              <div class="btn-list">
                <a-tooltip placement="top" title="Primary Tooltip">
                  <button type="button" class="btn btn-primary">
                    Primary Tooltip
                  </button>
                </a-tooltip>
                <a-tooltip placement="top" title="Secondary Tooltip">
                  <button
                    type="button"
                    class="btn btn-secondary"
                  >
                    Secondary Tooltip
                  </button>
                </a-tooltip>
                <a-tooltip placement="top" title="Warning Tooltip">
                  <button
                    type="button"
                    class="btn btn-warning"
                  >
                    Warning Tooltip
                  </button>
                </a-tooltip>
                <a-tooltip placement="top" title="Info Tooltip">
                  <button
                    type="button"
                    class="btn btn-info"
                  >
                    Info Tooltip
                  </button>
                </a-tooltip>
                <a-tooltip placement="top" title="Success Tooltip">
                  <button
                    type="button"
                    class="btn btn-success"
                  >
                    Success Tooltip
                  </button>
                </a-tooltip>
                <a-tooltip placement="top" title="Danger Tooltip">
                  <button
                    type="button"
                    class="btn btn-danger"
                  >
                    Danger Tooltip
                  </button>
                </a-tooltip>
                <a-tooltip placement="top" title="Light Tooltip">
                  <button
                    type="button"
                    class="btn btn-light"
                  >
                    Light Tooltip
                  </button>
                </a-tooltip>
                <a-tooltip placement="top" title="Dark Tooltip">
                  <button
                    type="button"
                    class="btn btn-dark text-white"
                  >
                    Dark Tooltip
                  </button>
                </a-tooltip>
              </div>
            </div>
          </div>
        </div>
        <!-- /Colored Tooltips -->
      </div>

      <div class="row">
        <!-- Html Element -->
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Html Element</h5>
            </div>
            <div class="card-body">
              <div class="popover-list">
                <a-tooltip placement="top" title="Popover title">
                  <button
                    class="example-popover btn btn-primary"
                    type="button"
                  >
                    Hover Me
                  </button>
                </a-tooltip>
              </div>
            </div>
          </div>
        </div>
        <!-- /Html Element -->

        <!-- Direction Tooltip -->
        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Direction Tooltip</h5>
            </div>
            <div class="card-body">
              <div class="tooltip-list">
                <a-tooltip placement="top" title="Tooltip on top">
                  <button
                    type="button"
                    class="btn btn-primary"
                  >
                    Tooltip on top
                  </button>
                </a-tooltip>
                <a-tooltip placement="right" title="Tooltip on right">
                  <button
                    type="button"
                    class="btn btn-primary ms-1"
                  >
                    Tooltip on right
                  </button>
                </a-tooltip>
                <a-tooltip placement="bottom" title="Tooltip on bottom">
                  <button
                    type="button"
                    class="btn btn-primary ms-1"
                  >
                    Tooltip on bottom
                  </button>
                </a-tooltip>
                <a-tooltip placement="left" title="Tooltip on left">
                  <button
                    type="button"
                    class="btn btn-primary ms-1"
                  >
                    Tooltip on left
                  </button>
                </a-tooltip>
              </div>
            </div>
          </div>
        </div>
        <!-- /Direction Tooltip -->

        <!-- Html Element -->
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Html Element</h5>
            </div>
            <div class="card-body">
              <div class="popover-list">
                <a-tooltip placement="top">
                  <template #title>
                    <span v-html="tooltipContent"></span>
                  </template>
                  <button
                    type="button"
                    class="btn btn-primary"
                  >
                    Tooltip with HTML
                  </button>
                </a-tooltip>
                <a-tooltip placement="bottom">
                  <template #title>
                    <span v-html="tooltipContent"></span>
                  </template>
                  <button
                    type="button"
                    class="btn btn-primary ms-1"
                  >
                    Click Me
                  </button>
                </a-tooltip>
              </div>
            </div>
          </div>
        </div>
        <!-- /Html Element -->

        <!-- Tooltip -->
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Disabled Elements</h5>
            </div>
            <div class="card-body">
              <a-tooltip placement="top" title="Disabled tooltip">
                <span
                class="d-inline-block"
                tabindex="0"
              >
                <button class="btn btn-primary" type="button" disabled="">
                  Disabled button
                </button>
              </span>
              </a-tooltip>
            </div>
          </div>
        </div>
        <!-- /Tooltip -->

        <!-- Tooltip Links -->
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Tooltips on Links</h5>
            </div>
            <div class="card-body">
              <p class="text-muted mb-0">
                Hover on the link to view the
                <a-tooltip placement="top" title="Link Tooltip">
                  <a
                    href="javascript:void(0);"
                    class="text-primary"
                    >Tooltip</a
                  >
                </a-tooltip>
              </p>
            </div>
          </div>
        </div>
        <!-- /Tooltip Links -->

        <!-- Tooltip Images -->
        <div class="col-md-6">
          <div class="card">
            <div class="card-header">
              <h5 class="card-title">Tooltip For Images</h5>
            </div>
            <div class="card-body">
              <a-tooltip placement="top" title="Marina Kai">
                <a
                  href="javascript:void(0);"
                  class="avatar avatar-md me-2 online avatar-rounded"
                >
                  <img src="@/assets/img/profiles/avatar-01.jpg" alt="img" />
                </a>
              </a-tooltip>
              <a-tooltip placement="top" title="Alex Carey">
                <a
                  href="javascript:void(0);"
                  class="avatar avatar-lg me-2 online avatar-rounded"
                >
                  <img src="@/assets/img/profiles/avatar-02.jpg" alt="img" />
                </a>
              </a-tooltip>
              <a-tooltip placement="top" title="Maria John">
                <a
                  href="javascript:void(0);"
                  class="avatar avatar-xl me-2 offline avatar-rounded"
                >
                  <img src="@/assets/img/profiles/avatar-03.jpg" alt="img" />
                </a>
              </a-tooltip>
            </div>
          </div>
        </div>
        <!-- /Tooltip Images -->
      </div>
    </div>
  </div>
</template>

<script>
import { ref } from "vue";
import { Tooltip } from 'ant-design-vue';

const tooltipContent = ref("<em>Tooltip</em> <u>with</u> <b>HTML</b>");

export default {
  components: {
    'a-tooltip': Tooltip
  },
  data(){
    return{
      tooltipContent,
    }
  }
}
</script>
