// nextjs/nextjs/template/src/components/auth/lockScreen.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React, { useState } from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";

const LockScreen = () => {
  const route = all_routes;
  const [isPasswordVisible, setPasswordVisible] = useState(false);

  const togglePasswordVisibility = () => {
    setPasswordVisible((prevState) => !prevState);
  };
  return (
    <div className="account-content">
    <div className="d-flex flex-wrap w-100 vh-100 overflow-hidden">
      <div className="d-flex align-items-center justify-content-center flex-fill flex-wrap vh-100 overflow-auto">
        <div className="login-shapes">
          <div className="login-right-shape">
            <img src="assets/img/authentication/shape-01.png" alt="Shape" />
          </div>
          <div className="login-left-shape">
            <img src="assets/img/authentication/shape-02.png" alt="Shape" />
          </div>
        </div>
        <div className="container">
          <div className="row justify-content-center">
            <div className="col-md-5">
              <div className="login-content user-login">
                <div className="text-center mb-4">
                  <img
                    src="assets/img/logo.svg"
                    className="img-fluid"
                    alt="Logo"
                  />
                </div>
                <form >
                  <div className="card border p-sm-3">
                    <div className="card-body p-4">
                      <div className="text-center">
                        <p className="text-default mb-3">Welcome back!</p>
                        <div className="mb-3">
                          <span className="avatar avatar-xxxl rounded-circle mb-4">
                            <img
                              src="assets/img/profiles/avatar-14.jpg"
                              className="img-fluid rounded-circle"
                              alt="Profile"
                            />
                          </span>
                          <h5 className="fs-18 fw-semibold">Adrian Davies</h5>
                        </div>
                      </div>
                      <div className="mb-3">
                        <label className="col-form-label">Enter Password</label>
                        <div className="pass-group">
                        <input
                      type={isPasswordVisible ? "text" : "password"}
                      className="pass-input form-control"
                    />
                    <span
                      className={`ti toggle-password ${
                        isPasswordVisible ? "ti-eye" : "ti-eye-off"
                      }`}
                      onClick={togglePasswordVisibility}
                    ></span>
                        </div>
                      </div>
                      <div className="mb-0">
                      <Link href={route.dealsDashboard} className="btn btn-primary w-100">
                    Log In
                  </Link>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
              <div className="d-flex align-items-center flex-wrap row-gap-2 justify-content-center mb-4">
                <Link href="#" className="fw-medium me-3">
                  Terms &amp; Condition
                </Link>
                <Link href="#" className="fw-medium me-3">
                  Privacy
                </Link>
                <Link href="#" className="fw-medium me-3">
                  Help
                </Link>
                <div className="dropdown">
                  <Link
                    href="#"
                    className="dropdown-toggle fw-medium border-0 p-0 bg-transparent shadow-none"
                    data-bs-toggle="dropdown"
                  >
                    English
                  </Link>
                  <div className="dropdown-menu dropdown-menu-end">
                    <Link href="#" className="dropdown-item">
                      French
                    </Link>
                    <Link href="#" className="dropdown-item">
                      Spanish
                    </Link>
                  </div>
                </div>
              </div>
              <div className="text-center">
                <p className="fw-medium text-gray">Copyright © 2025 - CRMS</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  
  );
};

export default LockScreen;

// vue/vue/src/views/pages/pages/authentication/lock-screen.vue
<template>
  <div class="account-page">
    <div class="main-wrapper">
      <div class="account-content">
        <div class="d-flex flex-wrap w-100 vh-100 overflow-hidden">
          <div
            class="d-flex align-items-center justify-content-center flex-fill flex-wrap vh-100 overflow-auto"
          >
            <div class="login-shapes">
              <div class="login-right-shape">
                <img src="@/assets/img/authentication/shape-01.png" alt="Shape" />
              </div>
              <div class="login-left-shape">
                <img src="@/assets/img/authentication/shape-02.png" alt="Shape" />
              </div>
            </div>
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-5">
                  <div class="login-content user-login">
                    <div class="text-center mb-4">
                      <img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo" />
                    </div>
                    <form @submit.prevent="submitForm">
                      <div class="card border p-sm-3">
                        <div class="card-body p-4">
                          <div class="text-center">
                            <p class="text-default mb-3">Welcome back!</p>
                            <div class="mb-3">
                              <span class="avatar avatar-xxxl rounded-circle mb-4"
                                ><img
                                  src="@/assets/img/profiles/avatar-14.jpg"
                                  class="img-fluid rounded-circle"
                                  alt="Profile"
                              /></span>
                              <h5 class="fs-18 fw-semibold">Adrian Davies</h5>
                            </div>
                          </div>
                          <div class="mb-3">
                            <label class="col-form-label">Enter Password</label>
                            <div class="pass-group">
                              <input type="password" class="pass-input form-control" />
                              <span class="ti toggle-password ti-eye-off"></span>
                            </div>
                          </div>
                          <div class="mb-0">
                            <button type="submit" class="btn btn-primary w-100">
                              Log In
                            </button>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                  <div
                    class="d-flex align-items-center flex-wrap row-gap-2 justify-content-center mb-4"
                  >
                    <a href="javascript:void(0);" class="fw-medium me-3"
                      >Terms & Condition</a
                    >
                    <a href="javascript:void(0);" class="fw-medium me-3">Privacy</a>
                    <a href="javascript:void(0);" class="fw-medium me-3">Help</a>
                    <div class="dropdown">
                      <a
                        href="javascript:void(0);"
                        class="dropdown-toggle fw-medium border-0 p-0 bg-transparent shadow-none"
                        data-bs-toggle="dropdown"
                        >English</a
                      >
                      <div class="dropdown-menu dropdown-menu-end">
                        <a href="javascript:void(0);" class="dropdown-item">French</a>
                        <a href="javascript:void(0);" class="dropdown-item">Spanish</a>
                      </div>
                    </div>
                  </div>
                  <div class="text-center">
                    <p class="fw-medium text-gray">Copyright &copy; 2024 - CRMS</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {};
  },
  methods: {
    submitForm() {
      this.$router.push("/dashboard");
    },
  },
};
</script>
