// nextjs/nextjs/template/src/components/settings/appSettings/invoiceSettings.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import Select from "react-select";
import CollapseHeader from "../../../core/common/collapse-header";
const route = all_routes;
const InvoiceSettingsComponent = () => {
  const options1 = [
    { value: "5", label: "5" },
    { value: "7", label: "7" },
  ];

  const options2 = [
    { value: "roundoff-up", label: "Roundoff Up" },
    { value: "roundoff-down", label: "Roundoff Down" },
  ];
  return (
    <div className="page-wrapper">
      <div className="content">
        <div className="row">
          <div className="col-md-12">
            {/* Page Header */}
            <div className="page-header">
              <div className="row align-items-center">
                <div className="col-8">
                  <h4 className="page-title">Settings</h4>
                </div>
                <div className="col-4 text-end">
                  <div className="head-icons">
                    <CollapseHeader />
                  </div>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Settings Menu */}
            <div className="card">
              <div className="card-body pb-0 pt-2">
              <ul className="nav nav-tabs nav-tabs-bottom">
                    <li className="nav-item me-3">
                      <Link href={route.profile} className="nav-link px-0 ">
                        <i className="ti ti-settings-cog" /> General Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.companySettings}
                        className="nav-link px-0 "
                      >
                        <i className="ti ti-world-cog" /> Website Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.invoiceSettings}
                        className="nav-link px-0 active"
                      >
                        <i className="ti ti-apps" /> App Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link href={route.emailSettings} className="nav-link px-0 ">
                        <i className="ti ti-device-laptop" /> System Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.paymentGateways}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-moneybag" /> Financial Settings
                      </Link>
                    </li>
                    <li className="nav-item ">
                      <Link href={route.storage} className="nav-link px-0 ">
                        <i className="ti ti-flag-cog" /> Other Settings
                      </Link>
                    </li>
                  </ul>
              </div>
            </div>
            {/* /Settings Menu */}
            <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">App Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
            <Link href={route.invoiceSettings} className="fw-medium active">
              Invoice Settings
            </Link>
            <Link href={route.printers} className="fw-medium">
              Printer
            </Link>
            <Link href={route.customFields} className="fw-medium">
              Custom Fields
            </Link>
          </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Invoice Settings */}
    <div className="card">
      <div className="card-body">
        <h4 className="fw-semibold mb-3">Invoice Settings</h4>
        <form >
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Logo</h6>
                <p>Upload logo of your company to display in invoice</p>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="profile-upload">
                  <div className="profile-upload-img">
                    <span>
                      <i className="ti ti-photo" />
                    </span>
                    <img
                      id="ImgPreview"
                      src="assets/img/logo.svg"
                      alt="img"
                      className="preview1"
                    />
                    <button
                      type="button"
                      id="removeImage1"
                      className="profile-remove"
                    >
                      <i className="feather-x" />
                    </button>
                  </div>
                  <div className="profile-upload-content">
                    <label className="profile-upload-btn">
                      <i className="ti ti-file-broken" /> Upload File
                      <input type="file" id="imag" className="input-img" />
                    </label>
                    <p>
                      Upload Logo of your company to display in website(JPG or
                      PNG). Max size of 800K
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Prefix</h6>
                <p>Add prefix to your invoice</p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="mb-3">
                <input
                  type="text"
                  className="form-control"
                  defaultValue="INV-"
                />
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Due</h6>
                <p>Select due date to display in invoice</p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="mb-3">
                <div className="d-flex align-items-center inv-days">
                  <div className="select-drop">
                  <Select
                                     classNamePrefix="react-select"
                                    className="select"
                                    defaultValue={options1[0]}
                                    options={options1}
                                  />
                  </div>
                  <p>Days</p>
                </div>
              </div>
            </div>
          </div>
          <div className="row align-items-center">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Round Off</h6>
                <p>Value roundoff in invoice</p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="mb-3">
                <div className="d-flex align-items-center">
                  <div className="form-check form-switch me-2">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                  <div className="select-drop w-100">
                  <Select
                                    className="select"
                                    defaultValue={options2[0]}
                                    options={options2}
                                  />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row align-items-center">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Show Company Details</h6>
                <p>Show/hide company details in invoice</p>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="form-check form-switch">
                  <input
                    className="form-check-input"
                    type="checkbox"
                    role="switch"
                    defaultChecked
                  />
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Header Terms</h6>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="summernote" />
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Footer Terms</h6>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="summernote" />
              </div>
            </div>
          </div>
          <div>
            <Link href="#" className="btn btn-light me-2">
              Cancel
            </Link>
            <button type="button" className="btn btn-primary">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
    {/* /Invoice Settings */}
  </div>
</div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default InvoiceSettingsComponent;

// vue/vue/src/views/pages/settings/app-settings/invoice-settings.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Page Header -->
          <page-header :title="title" />
          <!-- /Page Header -->

          <!-- Settings Menu -->
          <settings-tabs></settings-tabs>
          <!-- /Settings Menu -->

          <div class="row">
            <app-sidebar></app-sidebar>
            <div class="col-xl-9 col-lg-12">
              <!-- Invoice Settings -->
              <div class="card">
                <div class="card-body">
                  <h4 class="fw-semibold mb-3">Invoice Settings</h4>
                  <form @submit.prevent="submitForm">
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Logo</h6>
                          <p>Upload logo of your company to display in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="mb-3">
                          <div class="profile-upload">
                            <div class="profile-upload-img">
                              <span><i class="ti ti-photo"></i></span>
                              <img
                                id="ImgPreview"
                                src="@/assets/img/logo.svg"
                                alt="img"
                                class="preview1"
                              />
                              <button
                                type="button"
                                id="removeImage1"
                                class="profile-remove"
                              >
                                <i class="feather-x"></i>
                              </button>
                            </div>
                            <div class="profile-upload-content">
                              <label class="profile-upload-btn">
                                <i class="ti ti-file-broken"></i> Upload File
                                <input type="file" id="imag" class="input-img" />
                              </label>
                              <p>
                                Upload Logo of your company to display in website(JPG or
                                PNG). Max size of 800K
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Prefix</h6>
                          <p>Add prefix to your invoice</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <input type="text" class="form-control" value="INV-" />
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Due</h6>
                          <p>Select due date to display in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <div class="d-flex align-items-center inv-days">
                            <div class="select-drop">
                              <vue-select :options="NumSel" id="numsel" placeholder="5" />
                            </div>
                            <p>Days</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row align-items-center">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Round Off</h6>
                          <p>Value roundoff in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <div class="d-flex align-items-center">
                            <div class="form-check form-switch me-2">
                              <input
                                class="form-check-input"
                                type="checkbox"
                                role="switch"
                                checked
                              />
                            </div>
                            <div class="select-drop w-100">
                              <vue-select
                                :options="RounSel"
                                id="rounsel"
                                placeholder="Roundoff Up"
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row align-items-center">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Show Company Details</h6>
                          <p>Show/hide company details in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="mb-3">
                          <div class="form-check form-switch">
                            <input
                              class="form-check-input"
                              type="checkbox"
                              role="switch"
                              checked
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Header Terms</h6>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="mb-3">
                          <ckeditor
                            :editor="editor"
                            v-model="editorData"
                            :config="editorConfig"
                          ></ckeditor>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Footer Terms</h6>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="mb-3">
                          <ckeditor
                            :editor="editor"
                            v-model="editorDataOne"
                            :config="editorConfigOne"
                          ></ckeditor>
                        </div>
                      </div>
                    </div>
                    <div>
                      <a href="#" class="btn btn-light me-2">Cancel</a>
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form>
                </div>
              </div>
              <!-- /Invoice Settings -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import ClassicEditor from "@ckeditor/ckeditor5-build-classic";
export default {
  data() {
    return {
      editor: ClassicEditor,
      editorData: "Description",
      editorConfig: {},
      editorDataOne: "Description",
      editorConfigOne: {},
      title: "Invoice Settings",
      RounSel: ["Roundoff Up", "Roundoff Down"],
      NumSel: ["5", "7"],
    };
  },
  methods: {
    submitForm() {
      this.$router.push("/app-settings/invoice-settings");
    },
  },
};
</script>
