// angular/angular/src/app/feature-module/membership/membership-transactions/membership-transactions.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { DataService } from '../../../../shared/data/data.service';
import { membershipTransactions, apiResultFormat } from '../../../../shared/model/pages.model';
import { routes } from '../../../../shared/routes/routes';
import { PaginationService, tablePageSize, pageSelection } from '../../../../shared/shared.index';

@Component({
    selector: 'app-membership-transactions',
    templateUrl: './membership-transactions.component.html',
    styleUrl: './membership-transactions.component.scss',
    standalone: false
})
export class MembershipTransactionsComponent {
  bsValue = new Date();
  bsRangeValue: Date[];
  maxDate = new Date();
  public routes = routes;
  // pagination variables
  public tableData: membershipTransactions[] = [];
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<membershipTransactions>;
  public searchDataValue = '';
  public tableDataCopy: membershipTransactions[] = [];
  public actualData: membershipTransactions[] = [];
  //** pagination variables
  initChecked = false;

  constructor(private data: DataService,
    private pagination: PaginationService,
    private router: Router) {
      this.data.getMembershipTransactions().subscribe((apiRes: apiResultFormat) => {
        this.actualData = apiRes.data;
        this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
          if (this.router.url == this.routes.membershipTransactions) {
            this.getTableData({ skip: res.skip, limit: res.limit });
            this.pageSize = res.pageSize;
          }
        });
      });
    this.maxDate.setDate(this.maxDate.getDate() + 7);
    this.bsRangeValue = [this.bsValue, this.maxDate];


  }
  private getTableData(pageOption: pageSelection): void {
    this.data.getMembershipTransactions().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.tableDataCopy = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: membershipTransactions, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.id = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
          this.tableDataCopy.push(res);
        }
      });
      this.dataSource = new MatTableDataSource<membershipTransactions>(this.actualData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        tableDataCopy: this.tableDataCopy,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public searchData(value: string): void {
    if (value == '') {
      this.tableData = this.tableDataCopy;
    } else {
      this.dataSource.filter = value.trim().toLowerCase();
      this.tableData = this.dataSource.filteredData;
    }
  }
  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
}

<div class="page-wrapper">
  <div class="content">

    <div class="row">
      <div class="col-md-12">

        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-sm-8">
              <h4 class="page-title">Membership Transactions</h4>
            </div>
            <div class="col-sm-4 text-sm-end">
              <div class="head-icons">
                <a [routerLink] = "routes.membershipTransactions" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-original-title="Refresh" matTooltip="Refresh"><i
                class="ti ti-refresh-dot"></i></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <div class="card">
          <div class="card-header">
            <!-- Search -->
            <div class="row align-items-center">
              <div class="col-sm-4">
                <div class="icon-form mb-3 mb-sm-0">
                  <span class="form-icon"><i class="ti ti-search"></i></span>
                  <input type="text" class="form-control" placeholder="Search Contacts">
                </div>							
              </div>		
              <div class="col-sm-8">					
                <div class="d-flex align-items-center flex-wrap row-gap-2 justify-content-sm-end">
                  <div class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle"  data-bs-toggle="dropdown"><i class="ti ti-package-export me-2"></i>Export</a>
                    <div class="dropdown-menu  dropdown-menu-end">
                      <ul>
                        <li>
                          <a href="javascript:void(0);" class="dropdown-item"><i class="ti ti-file-type-pdf text-danger me-1"></i>Export as PDF</a>
                        </li>
                        <li>
                          <a href="javascript:void(0);" class="dropdown-item"><i class="ti ti-file-type-xls text-green me-1"></i>Export as Excel </a>
                        </li>
                      </ul>
                    </div>
                  </div>	
                </div>
              </div>
            </div>
            <!-- /Search -->
          </div>
          <div class="card-body">

           

       <!-- Filter -->
       <div class="d-flex align-items-center justify-content-between flex-wrap row-gap-2 mb-4">
        <div class="d-flex align-items-center flex-wrap row-gap-2">
          <div class="dropdown me-2">
            <a href="javascript:void(0);" class="dropdown-toggle"  data-bs-toggle="dropdown"><i class="ti ti-sort-ascending-2 me-2"></i>Sort </a>
            <div class="dropdown-menu  dropdown-menu-start">
              <ul>
                <li>
                  <a href="javascript:void(0);" class="dropdown-item">
                    <i class="ti ti-circle-chevron-right me-1"></i>Ascending
                  </a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="dropdown-item">
                    <i class="ti ti-circle-chevron-right me-1"></i>Descending
                  </a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="dropdown-item">
                    <i class="ti ti-circle-chevron-right me-1"></i>Recently Viewed
                  </a>
                </li>
                <li>
                  <a href="javascript:void(0);" class="dropdown-item">
                    <i class="ti ti-circle-chevron-right me-1"></i>Recently Added
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <app-date-range-picker></app-date-range-picker>
        </div>
        <div class="d-flex align-items-center flex-wrap row-gap-2">
          <div class="dropdown me-2">
            <a href="javascript:void(0);" class="btn bg-soft-purple text-purple"  data-bs-toggle="dropdown"  data-bs-auto-close="outside"><i class="ti ti-columns-3 me-2"></i>Manage Columns</a>
            <div class="dropdown-menu  dropdown-menu-md-end dropdown-md p-3">
              <h4 class="mb-2 fw-semibold">Want to manage datatables?</h4>
              <p class="mb-3">Please drag and drop your column to reorder your table and enable see option as you want.</p>
              <div class="border-top pt-3">
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Name</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-name" class="check">
                    <label for="col-name" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Phone</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-phone" class="check">
                    <label for="col-phone" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Email</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-email" class="check">
                    <label for="col-email" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Tags</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-tag" class="check">
                    <label for="col-tag" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Location</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-loc" class="check">
                    <label for="col-loc" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Rating</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-rate" class="check">
                    <label for="col-rate" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Owner</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-owner" class="check">
                    <label for="col-owner" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Contact</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-contact" class="check" checked="">
                    <label for="col-contact" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between mb-3">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Status</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-status" class="check">
                    <label for="col-status" class="checktoggle"></label>
                  </div>
                </div>
                <div class="d-flex align-items-center justify-content-between">
                  <p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Action</p>
                  <div class="status-toggle">
                    <input type="checkbox" id="col-action" class="check">
                    <label for="col-action" class="checktoggle"></label>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="form-sorts dropdown">
            <a href="javascript:void(0);" data-bs-toggle="dropdown"  data-bs-auto-close="outside"><i class="ti ti-filter-share"></i>Filter</a>
            <div class="filter-dropdown-menu dropdown-menu  dropdown-menu-xl-end p-3">
              <div class="filter-set-view">
                <div class="filter-set-head">
                  <h4><i class="ti ti-filter-share"></i>Filter</h4>
                </div>
                <div class="accordion" id="accordionExample">
                  <div class="filter-set-content">
                    <div class="filter-set-content-head">
                      <a href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">Type</a>
                    </div>
                    <div class="filter-set-contents accordion-collapse collapse show" id="collapseTwo" data-bs-parent="#accordionExample">
                      <div class="filter-content-list">
                        <ul>
                          <li>
                            <div class="filter-checks">
                              <label class="checkboxs">
                                <input type="checkbox">
                                <span class="checkmarks"></span>
                                Wallet Topup
                              </label>
                            </div>
                          </li>
                          <li>
                            <div class="filter-checks">
                              <label class="checkboxs">
                                <input type="checkbox">
                                <span class="checkmarks"></span>
                                Purchase
                              </label>
                            </div>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="filter-set-content">
                    <div class="filter-set-content-head">
                      <a href="javascript:void(0);" class="collapsed" data-bs-toggle="collapse" data-bs-target="#owner" aria-expanded="false" aria-controls="owner">Status</a>
                    </div>
                    <div class="filter-set-contents accordion-collapse collapse" id="owner" data-bs-parent="#accordionExample">
                      <ul>
                        <li>
                          <div class="filter-checks">
                            <label class="checkboxs">
                              <input type="checkbox" checked>
                              <span class="checkmarks"></span>
                              Completed
                            </label>
                          </div>
                        </li>
                        <li>
                          <div class="filter-checks">
                            <label class="checkboxs">
                              <input type="checkbox">
                              <span class="checkmarks"></span>
                              Cancel
                            </label>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="filter-set-content">
                    <div class="filter-set-content-head">
                      <a href="javascript:void(0);" class="collapsed" data-bs-toggle="collapse" data-bs-target="#Status" aria-expanded="false" aria-controls="Status">Payment Type</a>
                    </div>
                    <div class="filter-set-contents accordion-collapse collapse" id="Status" data-bs-parent="#accordionExample">
                      <div class="filter-content-list">
                        <ul>
                          <li>
                            <div class="filter-checks">
                              <label class="checkboxs">
                                <input type="checkbox" checked>
                                <span class="checkmarks"></span>
                                Paypal
                              </label>
                            </div>
                          </li>
                          <li>
                            <div class="filter-checks">
                              <label class="checkboxs">
                                <input type="checkbox">
                                <span class="checkmarks"></span>
                                Cash
                              </label>
                            </div>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="filter-set-content">
                    <div class="filter-set-content-head">
                      <a href="javascript:void(0);" class="collapsed" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">Created Date</a>
                    </div>
                    <div class="filter-set-contents accordion-collapse collapse" id="collapseOne" data-bs-parent="#accordionExample">
                      <div class="filter-content-list">
                        <ul>
                          <li>
                            <div class="filter-checks">
                              <label class="checkboxs">
                                <input type="checkbox" checked>
                                <span class="checkmarks"></span>
                                25 Sep 2023, 01:22 pm
                              </label>
                            </div>
                            
                          </li>
                          <li>
                            <div class="filter-checks">
                              <label class="checkboxs">
                                <input type="checkbox">
                                <span class="checkmarks"></span>
                                27 Sep 2023, 04:18 pm
                              </label>
                            </div>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>													
                <div class="filter-reset-btns">
                  <div class="row">
                    <div class="col-6">
                      <a href="javascript:void(0);" class="btn btn-light">Reset</a>
                    </div>
                    <div class="col-6">
                      <a [routerLink]="routes.membershipTransactions" class="btn btn-primary">Filter</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /Filter -->


              <!-- Transactions List -->
              <div class="table-responsive custom-table">
                <table matSort (matSortChange)="sortData($event)" class="table" id="transactions_list">
                  <thead class="thead-light">
                    <tr>
                      <th class="no-sort">
                         <label class="checkboxs" (click)="selectAll(initChecked)"  (keydown.enter)="selectAll(initChecked)" tabindex="0">
                          <input type="checkbox" [(ngModel)]="initChecked"><span
                        class="checkmarks"></span></label>
                      </th>
                      <th class="no-sort"></th>
                      <th mat-sort-header="type">Type</th>
                      <th mat-sort-header="amount">Amount</th>
                      <th mat-sort-header="date">Date</th>
                      <th mat-sort-header="payment_type">Payment Type</th>
                      <th mat-sort-header="status">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    @for (data of tableData; track data) {
                      <tr class="odd">
                        <td class="sorting_1"><label class="checkboxs"><input type="checkbox"
                          [(ngModel)]="data.isSelected"><span
                        class="checkmarks"></span></label></td>
                        <td>
                          <div class="set-star rating-select filled"><i class="fa fa-star"></i></div>
                        </td>
                        <td>{{data.type}}</td>
                        <td>{{data.amount}}</td>
                        <td>{{data.date}}</td>
                        <td>{{data.payment_type}}</td>
                        <td><span class="badge badge-pill badge-status"
                        [ngClass]="{'bg-success': data.status === 'Completed', 'bg-danger': data.status === 'Cancel'}">{{data.status}}</span>
                      </td>
                    </tr>
                  }
                </tbody>
              </table>
            </div>
            <app-custom-pagination></app-custom-pagination>
            <div class="row align-items-center">
              <div class="col-md-6">
                <div class="datatable-length"></div>
              </div>
              <div class="col-md-6">
                <div class="datatable-paginate"></div>
              </div>
            </div>
            <!-- /Transactions List -->

          </div>
        </div>

      </div>
    </div>

  </div>
</div>

// vue/vue/src/views/pages/membership/membership-transactions.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Page Header -->
          <page-header :title="title" />
          <!-- /Page Header -->

          <div class="card">
            <!-- Search -->
            <div class="card-header">
              <!-- Search -->
              <div class="row align-items-center">
                <div class="col-sm-4">
                  <div class="icon-form mb-3 mb-sm-0">
                    <span class="form-icon"><i class="ti ti-search"></i></span>
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Search Contacts"
                    />
                  </div>
                </div>
                <div class="col-sm-8">
                  <div
                    class="d-flex align-items-center flex-wrap row-gap-2 justify-content-sm-end"
                  >
                    <div class="dropdown">
                      <a
                        href="javascript:void(0);"
                        class="dropdown-toggle"
                        data-bs-toggle="dropdown"
                        ><i class="ti ti-package-export me-2"></i>Export</a
                      >
                      <div class="dropdown-menu dropdown-menu-end">
                        <ul>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item"
                              ><i class="ti ti-file-type-pdf text-danger me-1"></i>Export
                              as PDF</a
                            >
                          </li>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item"
                              ><i class="ti ti-file-type-xls text-green me-1"></i>Export
                              as Excel
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Search -->
            </div>
            <!-- /Search -->
            <div class="card-body">
              <!-- Filter -->
              <membership-filter></membership-filter>
              <!-- /Filter -->

              <!-- Transactions List -->
              <div class="table-responsive custom-table">
                <a-table
                  class="table"
                  :columns="columns"
                  :data-source="data"
                  :row-selection="rowSelection"
                >
                  <template #bodyCell="{ column, record }">
                    <template v-if="column.key === 'Star'">
                      <div class="set-star rating-select filled">
                        <i class="fa fa-star"></i>
                      </div>
                    </template>
                    <template v-else-if="column.key === 'Status'">
                      <span :class="record.Class">{{ record.Status }}</span>
                    </template>
                  </template>
                </a-table>
              </div>
              <div class="row align-items-center">
                <div class="col-md-6">
                  <div class="datatable-length"></div>
                </div>
                <div class="col-md-6">
                  <div class="datatable-paginate"></div>
                </div>
              </div>
              <!-- /Transactions List -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
const columns = [
  {
    title: "",
    dataIndex: "",
    sorter: false,
  },
  {
    title: "",
    dataIndex: "",
    key: "Star",
    sorter: false,
  },
  {
    title: "Type",
    dataIndex: "Type",
    sorter: {
      compare: (a, b) => {
        a = a.Type.toLowerCase();
        b = b.Type.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Amount",
    dataIndex: "Amount",
    key: "Amount",
    sorter: {
      compare: (a, b) => {
        a = a.Amount.toLowerCase();
        b = b.Amount.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Date",
    dataIndex: "Date",
    sorter: {
      compare: (a, b) => {
        a = a.Date.toLowerCase();
        b = b.Date.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Payment Type",
    dataIndex: "PaymentType",
    sorter: {
      compare: (a, b) => {
        a = a.PaymentType.toLowerCase();
        b = b.PaymentType.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) => {
        a = a.Status.toLowerCase();
        b = b.Status.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
];
const data = [
  {
    key: 1,
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "25 Sep 2023, 01:22 pm",
    PaymentType: "Paypal",
    Class: "badge badge-pill badge-status bg-success",
    Status: "Completed",
  },
  {
    key: 2,
    Type: "Purchase",
    Amount: "-350",
    Date: "27 Sep 2023, 04:18 pm",
    PaymentType: "Cash",
    Class: "badge badge-pill badge-status bg-danger",
    Status: "Cancel",
  },
  {
    key: 3,
    Type: "Refund",
    Amount: "+$100",
    Date: "29 Sep 2023, 10:08 am",
    PaymentType: "Paypal",
    Class: "badge badge-pill badge-status bg-success",
    Status: "Completed",
  },
  {
    key: 4,
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "05 Oct 2023, 09:43 am",
    PaymentType: "Cash",
    Class: "badge badge-pill badge-status bg-success",
    Status: "Completed",
  },
  {
    key: 5,
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "17 Oct 2023, 01:22 am",
    PaymentType: "Paypal",
    Class: "badge badge-pill badge-status bg-danger",
    Status: "Cancel",
  },
  {
    key: 6,
    Type: "Wallet Topup",
    Amount: "+$650",
    Date: "22 Oct 2023, 06:32 pm",
    PaymentType: "Cash",
    Class: "badge badge-pill badge-status bg-success",
    Status: "Completed",
  },
];
const rowSelection = {
  onChange: () => {},
  onSelect: () => {},
  onSelectAll: () => {},
};

export default {
  data() {
    return {
      title: "Membership Trasactions",
      data,
      columns,
      rowSelection,
    };
  },
};
</script>
