// angular/angular/src/app/feature-module/main-menu/application/call/audio-call/audio-call.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-audio-call',
    templateUrl: './audio-call.component.html',
    styleUrl: './audio-call.component.scss',
    standalone: false
})
export class AudioCallComponent {
  isAddMeetingClassVisible = false;

  toggleAddMeetingClass() {
    this.isAddMeetingClassVisible = !this.isAddMeetingClassVisible;
  }
  closeChat() {
    this.isAddMeetingClassVisible = false;
  }
  isMuted = false;
  isMuteButtonClicked = false;
  toggleMute() {
    this.isMuted = !this.isMuted;
  }
  toggleMute1() {
    this.isMuted = !this.isMuted;
    this.isMuteButtonClicked = true;
  }

  isOtherMicOffClicked = false;

  toggleOtherMicOff() {
    this.isOtherMicOffClicked = !this.isOtherMicOffClicked;
  }
  public mic = false;

  public toggleChange() {
    this.mic = !this.mic;
  }
}

<div class="page-wrapper">
  <div class="content">
    <!-- /product list -->
    <div class="card">
      <div class="card-body">
        <div class="row">
          <div class="col-xl-12">
            <div class="conference-meet-group">
              <div class="meeting-list " [class.add-meeting]="isAddMeetingClassVisible">

                <!-- Horizontal View -->
                <div class="join-contents horizontal-view fade-whiteboard">
                  <div class="join-video audio-calls user-active">
                    <div class="audio-call-group">
                      <ul>
                        <li class="active">
                          <div class="avatar ">
                            <img src="assets/img/profiles/avatar-02.jpg" class="rounded-circle" alt="image">
                            <div class="more-icon">
                              <a href="javascript:void(0);">
                                <i class="feather feather icon-radio"></i>
                              </a>
                            </div>
                          </div>
                          <div class="user-audio-call">
                            <h5>Mark Villiams</h5>
                          </div>
                        </li>
                        <li>
                          <div class="avatar ">
                            <img src="assets/img/users/user-16.jpg" class="rounded-circle" alt="image">
                            <div class="more-icon audio-more-icon mic-view">
                              <a href="javascript:void(0);" class="other-mic-off" [ngClass]="{'stop': mic === true}"  (click)="toggleChange()">
                                <i class="bx" [ngClass]="mic ? 'bx-microphone' : 'bx-microphone-off'"></i>
                              </a>
                            </div>
                          </div>
                          <div class="user-audio-call">
                            <h5>Benjamin</h5>
                          </div>
                        </li>
                      </ul>
                    </div>
                    <div class="record-time">
                      <span>40:12</span>
                    </div>
                    <div class="meet-drop meet-mutes-bottom">
                      <ul>
                        <li><a href="javascript:void(0);" (click)="toggleAddMeetingClass()" id="show-message"><i
                              class="bx bx-message-alt-dots"></i></a></li>
                      </ul>
                    </div>
                  </div>

                </div>
                <!-- /Horizontal View -->

              </div>
              <div class="right-user-side chat-rooms theiaStickySidebar mb-2" id="chat-room"
                [class.open-chats]="isAddMeetingClassVisible">
                <ng-scrollbar>
                  <div class=" slime-grp">
                    <div class="left-chat-title">
                      <div class="chat-title">
                        <h4>Message</h4>
                      </div>
                      <div class="contact-close_call">
                        <a href="javascript:void(0);" class="close_profile close_profile4" (click)="closeChat()">
                          <i class="feather icon-x"></i>
                        </a>
                      </div>
                    </div>
                    <div class="card-body-blk slimscroll  p-0">
                      <div class="chat-msg-blk ">
                        <div class="chats">
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-01.jpg" class="dreams_chat" alt="image">
                          </div>
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Hi Everyone.!</h4>
                            </div>
                            <div class="chat-profile-name d-flex justify-content-end">
                              <h6>10:00 AM</h6>
                            </div>
                          </div>
                        </div>
                        <div class="chats chats-right">
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Good Morning..! Today we have meeting about the new product.</h4>
                            </div>
                            <div class="chat-profile-name text-end">
                              <h6><i class="bx bx-check-double"></i> 10:00</h6>
                            </div>
                          </div>
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-02.jpg" class=" dreams_chat" alt="image">
                          </div>
                        </div>
                        <div class="chats">
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-01.jpg" class=" dreams_chat" alt="image">
                          </div>
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Hi.! Good Morning all.</h4>
                            </div>
                            <div class="chat-profile-name d-flex justify-content-end">
                              <h6>10:00 AM</h6>
                            </div>
                          </div>
                        </div>
                        <div class="chats">
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-01.jpg" class=" dreams_chat" alt="image">
                          </div>
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Nice..which category it belongs to?</h4>
                            </div>
                            <div class="chat-profile-name d-flex justify-content-end">
                              <h6>10:00 AM</h6>
                            </div>
                          </div>
                        </div>
                        <div class="chats">
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-01.jpg" class=" dreams_chat" alt="image">
                          </div>
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Great.! This is the second new product that comes in this week.</h4>
                            </div>
                            <div class="chat-profile-name d-flex justify-content-end">
                              <h6>10:00 AM</h6>
                            </div>
                          </div>
                        </div>
                        <div class="chats">
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-01.jpg" class=" dreams_chat" alt="image">
                          </div>
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Hi.! Good Morning all.</h4>
                            </div>
                            <div class="chat-profile-name d-flex justify-content-end">
                              <h6>10:00 AM</h6>
                            </div>
                          </div>
                        </div>
                        <div class="chats">
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-01.jpg" class=" dreams_chat" alt="image">
                          </div>
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Nice..which category it belongs to?</h4>
                            </div>
                            <div class="chat-profile-name d-flex justify-content-end">
                              <h6>10:00 AM</h6>
                            </div>
                          </div>
                        </div>
                        <div class="chats chats-right">
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Good Morning..! Today we have meeting about the new product.</h4>
                            </div>
                            <div class="chat-profile-name text-end">
                              <h6><i class="bx bx-check-double"></i> 10:00</h6>
                            </div>
                          </div>
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-02.jpg" class="dreams_chat" alt="image">
                          </div>
                        </div>
                        <div class="chats">
                          <div class="chat-avatar">
                            <img src="assets/img/users/user-01.jpg" class=" dreams_chat" alt="image">
                          </div>
                          <div class="chat-content">
                            <div class="message-content">
                              <h4>Great.! This is the second new product that comes in this week.</h4>
                            </div>
                            <div class="chat-profile-name d-flex justify-content-end">
                              <h6>10:00 AM</h6>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="chat-footer">
                        <form>
                          <div class="smile-col comman-icon">
                            <a href="javascript:void(0);"><i class="far fa-smile"></i></a>
                          </div>
                          <div class="attach-col comman-icon">
                            <a href="javascript:void(0);"><i class="fas fa-paperclip"></i></a>
                          </div>
                          <div class="micro-col comman-icon">
                            <a href="javascript:void(0);"><i class="feather icon-microphone"></i></a>
                          </div>
                          <input type="text" class="form-control chat_form" placeholder="Enter Message.....">
                          <div class="send-chat comman-icon">
                            <a href="javascript:void(0);"><i class="feather icon-send"></i></a>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </ng-scrollbar>
              </div>
            </div>
            <div class="meet-call-menu-blk">
              <div class="video-call-action">
                <ul class="nav">
                  <li> <a href="javascript:void(0);" class="mute-bt" [class.stop]="isMuted" (click)="toggleMute()">
                      <i class="bx" [ngClass]="{'bx-microphone': !isMuted, 'bx-microphone-off': isMuted}"></i>
                    </a></li>
                  <li><a href="javascript:void(0);" class="call-end"><i class="feather icon-phone"></i></a></li>
                  <li><a href="javascript:void(0);"><i class="bx bx-video-off"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /product list -->
  </div>
</div>

// nextjs/nextjs/template/src/components/application/call/audioCall.tsx
"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import React, { useState } from "react";



const AudioCallComponent = () => {
  const [addClass, setAddClass] = useState(false);
  const handleShowClass = () => {
    setAddClass(true);
  };

  const handleShowremoveClass = () => {
    setAddClass(false);
  };

  return (
    <div className="page-wrapper">
      <div className="content">
        {/* /product list */}
        <div className="card">
          <div className="card-body">
            <div className="row">
              <div className="col-xl-12">
                <div className="conference-meet-group">
                  <div
                    className={
                      addClass ? "meeting-list add-meeting" : "meeting-list"
                    }
                  >
                    {" "}
                    {/* Horizontal View */}
                    <div className="join-contents horizontal-view fade-whiteboard">
                      <div className="join-video audio-calls user-active">
                        <div className="audio-call-group">
                          <ul>
                            <li className="active">
                              <div className="avatar ">
                                <img
                                  src="assets/img/profiles/avatar-02.jpg"
                                  className="rounded-circle"
                                  alt="img"
                                />
                                <div className="more-icon">
                                  <Link href="#">
                                    <i className="feather feather-radio" />
                                  </Link>
                                </div>
                              </div>
                              <div className="user-audio-call">
                                <h5>Mark Villiams</h5>
                              </div>
                            </li>
                            <li>
                              <div className="avatar ">
                                <img
                                  src="assets/img/users/user-16.jpg"
                                  className="rounded-circle"
                                  alt="img"
                                />
                                <div className="more-icon audio-more-icon">
                                  <Link href="#" className="other-mic-off">
                                    <i className="bx bx-microphone" />
                                  </Link>
                                </div>
                              </div>
                              <div className="user-audio-call">
                                <h5>Benjamin</h5>
                              </div>
                            </li>
                          </ul>
                        </div>
                        <div className="record-time">
                          <span>40:12</span>
                        </div>
                        <div className="meet-drop meet-mutes-bottom">
                          <ul>
                            <li>
                              <Link
                                href="#"
                                id="show-message"
                                onClick={handleShowClass}
                              >
                                <i className="bx bx-message-alt-dots" />
                              </Link>
                            </li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    {/* /Horizontal View */}
                  </div>
                  <div
                    id="chat-room"
                    className={
                      addClass
                        ? "right-user-side chat-rooms theiaStickySidebar mb-2 open-chats"
                        : "right-user-side chat-rooms theiaStickySidebar mb-2"
                    }
                  >
                      <div className=" slime-grp">
                        <div className="left-chat-title">
                          <div className="chat-title">
                            <h4>Message</h4>
                          </div>
                          <div className="contact-close_call">
                            <Link
                              href="#"
                              className="close_profile close_profile4"
                              onClick={handleShowremoveClass}
                            >
                              <i className=" feather feather-x" />
                            </Link>
                          </div>
                        </div>
                        <div className="card-body-blk slimscroll  p-0">
                          <div className="chat-msg-blk ">
                            <div className="chats">
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-01.jpg"
                                  className="dreams_chat"
                                  alt="img"
                                />
                              </div>
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>Hi Everyone.!</h4>
                                </div>
                                <div className="chat-profile-name d-flex justify-content-end">
                                  <h6>10:00 AM</h6>
                                </div>
                              </div>
                            </div>
                            <div className="chats chats-right">
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>
                                    Good Morning..! Today we have meeting about
                                    the new product.
                                  </h4>
                                </div>
                                <div className="chat-profile-name text-end">
                                  <h6>
                                    <i className="bx bx-check-double" /> 10:00
                                  </h6>
                                </div>
                              </div>
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-02.jpg"
                                  className=" dreams_chat"
                                  alt="img"
                                />
                              </div>
                            </div>
                            <div className="chats">
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-01.jpg"
                                  className=" dreams_chat"
                                  alt="img"
                                />
                              </div>
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>Hi.! Good Morning all.</h4>
                                </div>
                                <div className="chat-profile-name d-flex justify-content-end">
                                  <h6>10:00 AM</h6>
                                </div>
                              </div>
                            </div>
                            <div className="chats">
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-01.jpg"
                                  className=" dreams_chat"
                                  alt="img"
                                />
                              </div>
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>Nice..which category it belongs to?</h4>
                                </div>
                                <div className="chat-profile-name d-flex justify-content-end">
                                  <h6>10:00 AM</h6>
                                </div>
                              </div>
                            </div>
                            <div className="chats">
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-01.jpg"
                                  className=" dreams_chat"
                                  alt="img"
                                />
                              </div>
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>
                                    Great.! This is the second new product that
                                    comes in this week.
                                  </h4>
                                </div>
                                <div className="chat-profile-name d-flex justify-content-end">
                                  <h6>10:00 AM</h6>
                                </div>
                              </div>
                            </div>
                            <div className="chats">
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-01.jpg"
                                  className=" dreams_chat"
                                  alt="img"
                                />
                              </div>
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>Hi.! Good Morning all.</h4>
                                </div>
                                <div className="chat-profile-name d-flex justify-content-end">
                                  <h6>10:00 AM</h6>
                                </div>
                              </div>
                            </div>
                            <div className="chats">
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-01.jpg"
                                  className=" dreams_chat"
                                  alt="img"
                                />
                              </div>
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>Nice..which category it belongs to?</h4>
                                </div>
                                <div className="chat-profile-name d-flex justify-content-end">
                                  <h6>10:00 AM</h6>
                                </div>
                              </div>
                            </div>
                            <div className="chats chats-right">
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>
                                    Good Morning..! Today we have meeting about
                                    the new product.
                                  </h4>
                                </div>
                                <div className="chat-profile-name text-end">
                                  <h6>
                                    <i className="bx bx-check-double" /> 10:00
                                  </h6>
                                </div>
                              </div>
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-02.jpg"
                                  className="dreams_chat"
                                  alt="img"
                                />
                              </div>
                            </div>
                            <div className="chats">
                              <div className="chat-avatar">
                                <img
                                  src="assets/img/users/user-01.jpg"
                                  className=" dreams_chat"
                                  alt="img"
                                />
                              </div>
                              <div className="chat-content">
                                <div className="message-content">
                                  <h4>
                                    Great.! This is the second new product that
                                    comes in this week.
                                  </h4>
                                </div>
                                <div className="chat-profile-name d-flex justify-content-end">
                                  <h6>10:00 AM</h6>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="chat-footer">
                            <form>
                              <div className="smile-col comman-icon">
                                <Link href="#">
                                  <i className="far fa-smile" />
                                </Link>
                              </div>
                              <div className="attach-col comman-icon">
                                <Link href="#">
                                  <i className="fas fa-paperclip" />
                                </Link>
                              </div>
                              <div className="micro-col comman-icon">
                                <Link href="#">
                                  <i className="bx bx-microphone" />
                                </Link>
                              </div>
                              <input
                                type="text"
                                className="form-control chat_form"
                                placeholder="Enter Message....."
                              />
                              <div className="send-chat comman-icon">
                                <Link href="#">
                                  <i className="feather feather-send" />
                                </Link>
                              </div>
                            </form>
                          </div>
                        </div>
                      </div>
                  </div>
                </div>
                <div className="meet-call-menu-blk">
                  <div className="video-call-action">
                    <ul className="nav">
                      <li>
                        <Link href="#" className="mute-bt ">
                          <i className="bx bx-microphone" />
                        </Link>
                      </li>
                      <li>
                        <Link href="#" className="call-end">
                          <i className="feather feather-phone" />
                        </Link>
                      </li>
                      <li>
                        <Link href="#">
                          <i className="bx bx-video-off" />
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* /product list */}
      </div>
    </div>
  );
};

export default AudioCallComponent;
