// vue/vue/src/views/pages/support/contact-messages.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Page Header -->
          <page-header :title="title" />
          <!-- /Page Header -->

          <div class="card">
            <div class="card-header">
              <!-- Search -->
              <div class="row align-items-center">
                <div class="col-sm-4">
                  <div class="icon-form mb-3 mb-sm-0">
                    <span class="form-icon"><i class="ti ti-search"></i></span>
                    <input type="text" class="form-control" placeholder="Search User" />
                  </div>
                </div>
                <div class="col-sm-8">
                  <div
                    class="d-flex align-items-center flex-wrap row-gap-2 justify-content-sm-end"
                  >
                    <div class="dropdown me-2">
                      <a
                        href="javascript:void(0);"
                        class="dropdown-toggle"
                        data-bs-toggle="dropdown"
                        ><i class="ti ti-package-export me-2"></i>Export</a
                      >
                      <div class="dropdown-menu dropdown-menu-end">
                        <ul>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item"
                              ><i class="ti ti-file-type-pdf text-danger me-1"></i>Export
                              as PDF</a
                            >
                          </li>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item"
                              ><i class="ti ti-file-type-xls text-green me-1"></i>Export
                              as Excel
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <a
                      href="javascript:void(0);"
                      class="btn btn-primary"
                      data-bs-toggle="offcanvas"
                      data-bs-target="#offcanvas_add"
                      ><i class="ti ti-square-rounded-plus me-2"></i>Add Contact
                      Messages</a
                    >
                  </div>
                </div>
              </div>
            </div>
            <!-- /Search -->
            <div class="card-body">
              <!-- Filter -->
              <contact-messages-filter></contact-messages-filter>
              <!-- /Filter -->

              <!-- Contact Messages List -->
              <div class="table-responsive custom-table">
                <a-table
                  class="table thead-light"
                  :columns="columns"
                  :data-source="data"
                  :row-selection="rowSelection"
                >
                  <template #bodyCell="{ column, record }">
                    <template v-if="column.key === 'Star'">
                      <div class="set-star rating-select">
                        <i class="fa fa-star"></i>
                      </div>
                    </template>
                    <template v-else-if="column.key === 'Name'">
                      <h2 class="d-flex align-items-center">
                        <a href="javascript:void(0);" class="avatar avatar-sm me-2"
                          ><img
                            class="w-auto h-auto"
                            :src="require(`@/assets/img/profiles/${record.Image}`)"
                            alt="User Image" /></a
                        ><a href="javascript:void(0);" class="d-flex flex-column"
                          >{{ record.Name }}
                          <span class="text-default">{{ record.Posting }}</span></a
                        >
                      </h2>
                    </template>
                    <template v-else-if="column.key === 'action'">
                      <div class="dropdown table-action">
                        <a
                          href="#"
                          class="action-icon"
                          data-bs-toggle="dropdown"
                          aria-expanded="false"
                          ><i class="fa fa-ellipsis-v"></i
                        ></a>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvas_edit"
                            ><i class="ti ti-edit text-blue"></i> Edit</a
                          ><a
                            class="dropdown-item"
                            href="#"
                            data-bs-toggle="modal"
                            data-bs-target="#delete_contact"
                            ><i class="ti ti-trash text-danger"></i> Delete</a
                          >
                        </div>
                      </div>
                    </template>
                  </template>
                </a-table>
              </div>
              <div class="row align-items-center">
                <div class="col-md-6">
                  <div class="datatable-length"></div>
                </div>
                <div class="col-md-6">
                  <div class="datatable-paginate"></div>
                </div>
              </div>
              <!-- /Contact Messages List -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <contact-message-modal></contact-message-modal>
</template>
<script>
const columns = [
  {
    title: "",
    dataIndex: "",
    sorter: false,
  },
  {
    title: "",
    dataIndex: "",
    key: "Star",
    sorter: false,
  },
  {
    title: "Name",
    dataIndex: "Name",
    key: "Name",
    sorter: {
      compare: (a, b) => {
        a = a.Name.toLowerCase();
        b = b.Name.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Phone",
    dataIndex: "Phone",
    sorter: {
      compare: (a, b) => {
        a = a.Phone.toLowerCase();
        b = b.Phone.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Email",
    dataIndex: "Email",
    sorter: {
      compare: (a, b) => {
        a = a.Email.toLowerCase();
        b = b.Email.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Message",
    dataIndex: "Message",
    sorter: {
      compare: (a, b) => {
        a = a.Message.toLowerCase();
        b = b.Message.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Created",
    dataIndex: "Created",
    sorter: {
      compare: (a, b) => {
        a = a.Created.toLowerCase();
        b = b.Created.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Action",
    key: "action",
    sorter: true,
  },
];
const data = [
  {
    key: 1,
    Name: "Darlee Robertson",
    Posting: "Facility Manager",
    Phone: "1234567890",
    Email: "robertson@example.com",
    Message: "Duis aute irure dolor in reprehenderit",
    Created: "25 Sep 2023, 12:12 pm",
    Action: "Edit Delete",
    Image: "avatar-19.jpg",
  },
  {
    key: 2,
    Name: "Sharon Roy",
    Posting: "Installer",
    Phone: "+1 989757485",
    Email: "sharon@example.com",
    Message: "Excepteur sint occaecat cupidatat",
    Created: "27 Sep 2023, 07:40 am",
    Action: "Edit Delete",
    Image: "avatar-20.jpg",
  },
  {
    key: 3,
    Name: "Vaughan",
    Posting: "Senior Manager",
    Phone: "+1 546555455",
    Email: "vaughan12@example.com",
    Message: "Lorem ipsum dolor sit consectetur",
    Created: "29 Sep 2023, 08:20 am",
    Action: "Edit Delete",
    Image: "avatar-21.jpg",
  },
  {
    key: 4,
    Name: "Jessica",
    Posting: "Test Engineer",
    Phone: "+1 454478787",
    Email: "jessica13@example.com",
    Message: "Nemo enim ipsam voluptatem quia",
    Created: "25 Sep 2023, 12:12 pm",
    Action: "Edit Delete",
    Image: "avatar-23.jpg",
  },
  {
    key: 5,
    Name: "Carol Thomas",
    Posting: "UI /UX Designer",
    Phone: "+1 124547845",
    Email: "caroltho3@example.com",
    Message: "Sed ut perspiciatis unde omnis iste",
    Created: "02 Oct 2023, 10:10 am",
    Action: "Edit Delete",
    Image: "avatar-16.jpg",
  },
  {
    key: 6,
    Name: "Dawn Mercha",
    Posting: "Technician",
    Phone: "+1 478845447",
    Email: "dawnmercha@example.com",
    Message: "Ut enim ad minim veniam, quis",
    Created: "17 Oct 2023, 04:25 pm",
    Action: "Edit Delete",
    Image: "avatar-22.jpg",
  },
  {
    key: 7,
    Name: "Rachel Hampton",
    Posting: "Software Developer",
    Phone: "+1 215544845",
    Email: "rachel@example.com",
    Message: "Duis aute irure dolor in reprehenderit",
    Created: "28 Oct 2023, 07:16 am",
    Action: "Edit Delete",
    Image: "avatar-24.jpg",
  },
  {
    key: 8,
    Name: "Jonelle Curtiss",
    Posting: "Supervisor",
    Phone: "+1 121145471",
    Email: "jonelle@example.com",
    Message: "Ut enim ad minim veniam, quis",
    Created: "08 Nov 2023, 06:10 am",
    Action: "Edit Delete",
    Image: "avatar-25.jpg",
  },
  {
    key: 9,
    Name: "Jonathan",
    Posting: "Team Lead Dev",
    Phone: "+1 321454789",
    Email: "jonathan@example.com",
    Message: "Excepteur sint occaecat cupidatat",
    Created: "15 Nov 2023, 11:50 am",
    Action: "Edit Delete",
    Image: "avatar-26.jpg",
  },
  {
    key: 10,
    Name: "Brook",
    Posting: "Team Lead Dev",
    Phone: "+1 278907145",
    Email: "brook@example.com",
    Message: "Ut enim ad minim veniam, quis",
    Created: "25 Nov 2023, 06:34 pm",
    Action: "Edit Delete",
    Image: "avatar-01.jpg",
  },
];
const rowSelection = {
  onChange: () => {},
  onSelect: () => {},
  onSelectAll: () => {},
};
export default {
  data() {
    return {
      title: "Contact Messages",
      data,
      columns,
      rowSelection,
    };
  },
};
</script>

// angular/angular/src/app/feature-module/support/contact-messages/contact-messages.component.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';
import { apiResultFormat, contactMessage, pageSelection } from '../../../../shared/model/pages.model';
import { MatTableDataSource } from '@angular/material/table';
import { DataService } from '../../../../shared/data/data.service';
import { PaginationService, tablePageSize } from '../../../../shared/custom-pagination/pagination.service';
import { Router } from '@angular/router';
import { Sort } from '@angular/material/sort';

@Component({
    selector: 'app-contact-messages',
    templateUrl: './contact-messages.component.html',
    styleUrl: './contact-messages.component.scss',
    standalone: false
})
export class ContactMessagesComponent {
  public routes = routes;
  // pagination variables
  public tableData: contactMessage[] = [];
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<contactMessage>;
  public searchDataValue = '';
  public tableDataCopy: contactMessage[] = [];
  public actualData: contactMessage[] = [];
  //** pagination variables
  
  public sidebarPopup = false;
  public sidebarPopup2 = false;

  initChecked = false;

  bsValue = new Date();
  bsRangeValue: Date[];
  maxDate = new Date();

  

  constructor(
    private data: DataService,
    private pagination: PaginationService,
    private router: Router
  ) {
    this.data.getContactMessage().subscribe((apiRes: apiResultFormat) => {
      this.actualData = apiRes.data;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.contactMessage) {
          this.getTableData({ skip: res.skip, limit: res.limit });
          this.pageSize = res.pageSize;
        }
      });
    });
    this.maxDate.setDate(this.maxDate.getDate() + 7);
    this.bsRangeValue = [this.bsValue, this.maxDate];
    
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getContactMessage().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.tableDataCopy = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: contactMessage, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.id = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
          this.tableDataCopy.push(res);
        }
      });
      this.dataSource = new MatTableDataSource<contactMessage>(this.actualData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        tableDataCopy: this.tableDataCopy,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public searchData(value: string): void {
    if (value == '') {
      this.tableData = this.tableDataCopy;
    } else {
      this.dataSource.filter = value.trim().toLowerCase();
      this.tableData = this.dataSource.filteredData;
    }
  }
  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }

  openSidebarPopup() {
    this.sidebarPopup = !this.sidebarPopup;
  }
  openSidebarPopup2() {
    this.sidebarPopup2 = !this.sidebarPopup2;
  }
  selectedUser: any;
  selectedUser2: any;
  onClickStar(item: contactMessage) {
    item.isStarActive = !item.isStarActive;
  }

 
 
}

<!-- Page Wrapper -->
<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h4 class="page-title">
                Contact Messages<span class="count-title">123</span>
              </h4>
            </div>
            <div class="col-4 text-end">
              <div class="head-icons">
                <a
                  [routerLink] = "routes.contactMessage"
                  data-bs-toggle="tooltip"
                  data-bs-placement="top"
                  data-bs-original-title="Refresh"
                  ><i class="ti ti-refresh-dot"></i
                ></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <div class="card">
          <div class="card-header">
            <div class="row align-items-center">
              <div class="col-sm-4">
                <div class="icon-form mb-3 mb-sm-0">
                  <span class="form-icon"><i class="ti ti-search"></i></span>
                  <input type="text" class="form-control" placeholder="Search User">
                </div>							
              </div>		
              <div class="col-sm-8">					
                <div class="d-flex align-items-center flex-wrap row-gap-2 justify-content-sm-end">
                  <div class="dropdown me-2">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown"><i class="ti ti-package-export me-2"></i>Export</a>
                    <div class="dropdown-menu  dropdown-menu-end">
                      <ul>
                        <li>
                          <a href="javascript:void(0);" class="dropdown-item"><i class="ti ti-file-type-pdf text-danger me-1"></i>Export as PDF</a>
                        </li>
                        <li>
                          <a href="javascript:void(0);" class="dropdown-item"><i class="ti ti-file-type-xls text-green me-1"></i>Export as Excel </a>
                        </li>
                      </ul>
                    </div>
                  </div>	
                  <a href="javascript:void(0);" class="btn btn-primary" data-bs-toggle="offcanvas" data-bs-target="#offcanvas_add"><i class="ti ti-square-rounded-plus me-2"></i>Add Contact Messages</a>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
           

            <!-- Filter -->
								<div class="d-flex align-items-center justify-content-between flex-wrap row-gap-2 mb-4">
									<div class="d-flex align-items-center flex-wrap row-gap-2">
										<div class="dropdown me-2">
											<a href="javascript:void(0);" class="dropdown-toggle" data-bs-toggle="dropdown"><i class="ti ti-sort-ascending-2 me-2"></i>Sort </a>
											<div class="dropdown-menu  dropdown-menu-start">
												<ul>
													<li>
														<a href="javascript:void(0);" class="dropdown-item">
															<i class="ti ti-circle-chevron-right me-1"></i>Ascending
														</a>
													</li>
													<li>
														<a href="javascript:void(0);" class="dropdown-item">
															<i class="ti ti-circle-chevron-right me-1"></i>Descending
														</a>
													</li>
													<li>
														<a href="javascript:void(0);" class="dropdown-item">
															<i class="ti ti-circle-chevron-right me-1"></i>Recently Viewed
														</a>
													</li>
													<li>
														<a href="javascript:void(0);" class="dropdown-item">
															<i class="ti ti-circle-chevron-right me-1"></i>Recently Added
														</a>
													</li>
												</ul>
											</div>
										</div>
										<app-date-range-picker></app-date-range-picker>
									</div>
									<div class="d-flex align-items-center flex-wrap row-gap-2">
										<div class="dropdown me-2">
											<a href="javascript:void(0);" class="btn bg-soft-purple text-purple" data-bs-toggle="dropdown" data-bs-auto-close="outside"><i class="ti ti-columns-3 me-2"></i>Manage Columns</a>
											<div class="dropdown-menu  dropdown-menu-md-end dropdown-md p-3">
												<h4 class="mb-2 fw-semibold">Want to manage datatables?</h4>
												<p class="mb-3">Please drag and drop your column to reorder your table and enable see option as you want.</p>
												<div class="border-top pt-3">
													<div class="d-flex align-items-center justify-content-between mb-3">
														<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Name</p>
														<div class="status-toggle">
															<input type="checkbox" id="col-name" class="check">
															<label for="col-name" class="checktoggle"></label>
														</div>
													</div>
													<div class="d-flex align-items-center justify-content-between mb-3">
														<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Phone</p>
														<div class="status-toggle">
															<input type="checkbox" id="col-phone" class="check">
															<label for="col-phone" class="checktoggle"></label>
														</div>
													</div>
													<div class="d-flex align-items-center justify-content-between mb-3">
														<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Email</p>
														<div class="status-toggle">
															<input type="checkbox" id="col-email" class="check">
															<label for="col-email" class="checktoggle"></label>
														</div>
													</div>
													<div class="d-flex align-items-center justify-content-between mb-3">
														<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Created Date</p>
														<div class="status-toggle">
															<input type="checkbox" id="col-tag" class="check">
															<label for="col-tag" class="checktoggle"></label>
														</div>
													</div>
													<div class="d-flex align-items-center justify-content-between mb-3">
														<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Location</p>
														<div class="status-toggle">
															<input type="checkbox" id="col-loc" class="check">
															<label for="col-loc" class="checktoggle"></label>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="form-sorts dropdown">
											<a href="javascript:void(0);" data-bs-toggle="dropdown" data-bs-auto-close="outside"><i class="ti ti-filter-share"></i>Filter</a>
											<div class="filter-dropdown-menu dropdown-menu  dropdown-menu-md-end p-3">
												<div class="filter-set-view">
													<div class="filter-set-head">
														<h4><i class="ti ti-filter-share"></i>Filter</h4>
													</div>
													<div class="accordion" id="accordionExample">
														<div class="filter-set-content">
															<div class="filter-set-content-head">
																<a href="javascript:void(0);" class="collapsed" data-bs-toggle="collapse" data-bs-target="#owner" aria-expanded="false" aria-controls="owner">Name</a>
															</div>
															<div class="filter-set-contents accordion-collapse collapse" id="owner" data-bs-parent="#accordionExample">
																<div class="filter-content-list">
																	<div class="mb-2 icon-form">
																		<span class="form-icon"><i class="ti ti-search"></i></span>
																		<input type="text" class="form-control" placeholder="Search Owner">
																	</div>
																	<ul>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox" checked="">
																					<span class="checkmarks"></span>
																					Darlee Robertson
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					Sharon Roy
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					Vaughan
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					Jessica
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					Carol Thomas
																				</label>
																			</div>
																		</li>
																	</ul>
																</div>
															</div>
														</div>
														<div class="filter-set-content">
															<div class="filter-set-content-head">
																<a href="javascript:void(0);" class="collapsed" data-bs-toggle="collapse" data-bs-target="#Status" aria-expanded="false" aria-controls="Status">Phone</a>
															</div>
															<div class="filter-set-contents accordion-collapse collapse" id="Status" data-bs-parent="#accordionExample">
																<div class="filter-content-list">
																	<ul>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox" checked="">
																					<span class="checkmarks"></span>
																					+1 875455453
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					+1 989757485
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					+1 546555455
																				</label>
																			</div>
																		</li>
																	</ul>
																</div>
															</div>
														</div>
														<div class="filter-set-content">
															<div class="filter-set-content-head">
																<a href="javascript:void(0);" class="collapsed" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Email</a>
															</div>
															<div class="filter-set-contents accordion-collapse collapse" id="collapseTwo" data-bs-parent="#accordionExample">
																<div class="filter-content-list">
																	<ul>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox" checked="">
																					<span class="checkmarks"></span>
																					robertson&#64;example.com
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					sharon&#64;example.com
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					vaughan12&#64;example.com
																				</label>
																			</div>
																		</li>
																	</ul>
																</div>
															</div>
														</div>
														<div class="filter-set-content">
															<div class="filter-set-content-head">
																<a href="javascript:void(0);" class="collapsed" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">Created Date</a>
															</div>
															<div class="filter-set-contents accordion-collapse collapse" id="collapseThree" data-bs-parent="#accordionExample">
																<div class="filter-content-list">
																	<ul>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox" checked="">
																					<span class="checkmarks"></span>
																					25 Sep 2023, 12:12 pm
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					27 Sep 2023, 07:40 am		
																				</label>
																			</div>
																		</li>
																		<li>
																			<div class="filter-checks">
																				<label class="checkboxs">
																					<input type="checkbox">
																					<span class="checkmarks"></span>
																					29 Sep 2023, 08:20 am
																				</label>
																			</div>
																		</li>
																	</ul>
																</div>
															</div>
														</div>
													</div>													
													<div class="filter-reset-btns">
														<div class="row">
															<div class="col-6">
																<a href="javascript:void(0);" class="btn btn-light">Reset</a>
															</div>
															<div class="col-6">
																<a [routerLink]="routes.contactMessage" class="btn btn-primary">Filter</a>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- /Filter -->

            <!-- Contact Messages List -->
            <div class="table-responsive custom-table">
              <table class="table" id="contact-messages-list" matSort
              (matSortChange)="sortData($event)">
                <thead class="thead-light">
                  <tr>
                    <th class="no-sort">
                       <label class="checkboxs" (click)="selectAll(initChecked)"  (keydown.enter)="selectAll(initChecked)" tabindex="0"
                      ><input type="checkbox" [(ngModel)]="initChecked" /><span
                        class="checkmarks"
                      ></span
                    ></label>
                    </th>
                    <th class="no-sort"></th>
                    <th mat-sort-header="Name">Name</th>
                    <th mat-sort-header="Phone">Phone</th>
                    <th mat-sort-header="Email">Email</th>
                    <th mat-sort-header="Message">Message</th>
                    <th mat-sort-header="Created">Created</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    @for (data of tableData; track data) {
                  <tr class="odd">
                    <td class="sorting_1">
                      <label class="checkboxs"
                          ><input type="checkbox" [(ngModel)]="data.isSelected" /><span
                            class="checkmarks"
                          ></span
                        ></label>
                    </td>
                    <td>
                      <div class="set-star rating-select" (click)="onClickStar(data)"  tabindex="0" (keydown.enter)="onClickStar(data)"[class.filled]="data.isStarActive">
                        <i class="fa fa-star"></i>
                      </div>

                    </td>
                    <td>
                      <h2 class="table-avatar d-flex align-items-center">
                        <a href="javascript:void(0);" class="avatar avatar-sm border me-2"
                          ><img
                            class="w-auto h-auto"
                            [src]="data.customer_image"
                            alt="User Image" /></a
                        ><a
                          href="javascript:void(0);"
                          class="profile-split d-flex flex-column"
                          >{{data.customer_name}}<span>{{data.customer_no}} </span></a
                        >
                      </h2>
                    </td>
                    <td>{{data.phone}}</td>
                    <td>{{data.email}}</td>
                    <td>{{data.message}}</td>
                    <td>{{data.created}}</td>
                    <td>
                      <div class="dropdown table-action">
                        <a
                          href="javascript:void(0);"
                          class="action-icon"
                          data-bs-toggle="dropdown"
                          aria-expanded="false"
                          ><i class="fa fa-ellipsis-v"></i
                        ></a>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a class="dropdown-item" href="javascript:void(0);" data-bs-toggle="offcanvas" data-bs-target="#offcanvas_edit"><i class="ti ti-edit text-blue"></i> Edit</a><a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="modal"
                            data-bs-target="#delete_contact"
                            ><i class="ti ti-trash text-danger"></i> Delete</a
                          >
                        </div>
                      </div>
                    </td>
                  </tr>
                }
                 
                  
                </tbody>
              </table>
            </div>
            <app-custom-pagination></app-custom-pagination>
            <div class="row align-items-center">
              <div class="col-md-6">
                <div class="datatable-length"></div>
              </div>
              <div class="col-md-6">
                <div class="datatable-paginate"></div>
              </div>
            </div>
            <!-- /Contact Messages List -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Page Wrapper -->

<!-- Add Contact Message -->
<div class="offcanvas offcanvas-end offcanvas-large" tabindex="-1" id="offcanvas_add">
  <div class="offcanvas-header border-bottom">
    <h5 class="fw-semibold">Add Contact Messages</h5>
    <button type="button" class="btn-close custom-btn-close border p-1 me-0 d-flex align-items-center justify-content-center rounded-circle" data-bs-dismiss="offcanvas" aria-label="Close">
      <i class="ti ti-x"></i>
    </button>
  </div>
  <div class="offcanvas-body">
    <form >	
      <div class="row">
        <div class="col-md-12">
          <div class="mb-3">
            <label class="col-form-label" for="reason"> Name <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
        </div>									
        <div class="col-md-6">
          <div class="mb-3">
            <div class="d-flex justify-content-between align-items-center">
              <label class="col-form-label" for="reason">Email <span class="text-danger">*</span></label>
              <div class="status-toggle small-toggle-btn d-flex align-items-center">
                <span class="me-2 label-text">Email Opt Out</span>
                <input type="checkbox" id="user" class="check" checked="">
                <label for="user" class="checktoggle"></label>
              </div>
            </div>
            <input type="text" class="form-control">
          </div>
        </div>
        <div class="col-md-6">
          <div class="mb-3">
            <label class="col-form-label" for="reason">Phone <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
        </div>
        <div class="col-md-12">
          <div class="mb-3">
            <label class="col-form-label" for="reason">Message <span class="text-danger">*</span></label>
            <textarea class="form-control"></textarea>
          </div>
        </div>
      </div>
      <div class="d-flex align-items-center justify-content-end">
        <a href="javascript:void(0);" class="btn btn-light me-2">Cancel</a>
        <button  type="submit" class="btn btn-primary">Create</button>
      </div>
    </form>
  </div>			
</div>
<!-- /Add Contact Message -->
<!-- Edit Contact Message -->
<div class="offcanvas offcanvas-end offcanvas-large" tabindex="-1" id="offcanvas_edit">
  <div class="offcanvas-header border-bottom">
    <h5 class="fw-semibold">Edit Contact Messages</h5>
    <button type="button" class="btn-close custom-btn-close border p-1 me-0 d-flex align-items-center justify-content-center rounded-circle" data-bs-dismiss="offcanvas" aria-label="Close">
      <i class="ti ti-x"></i>
    </button>
  </div>
  <div class="offcanvas-body">
    <form >	
      <div>						
        <div class="row">
          <div class="col-md-12">
            <div class="mb-3">
              <label class="col-form-label" for="reason"> Name <span class="text-danger">*</span></label>
              <input type="text" class="form-control" value="Darlee Robertson">
            </div>
          </div>									
          <div class="col-md-6">
            <div class="mb-3">
              <div class="d-flex justify-content-between align-items-center">
                <label class="col-form-label" for="reason">Email <span class="text-danger">*</span></label>
                <div class="status-toggle small-toggle-btn d-flex align-items-center">
                  <span class="me-2 label-text">Email Opt Out</span>
                  <input type="checkbox" id="email" class="check" checked="">
                  <label for="email" class="checktoggle"></label>
                </div>
              </div>
              <input type="text" class="form-control" value="robertson@example.com">
            </div>
          </div>
          <div class="col-md-6">
            <div class="mb-3">
              <label class="col-form-label" for="reason">Phone <span class="text-danger">*</span></label>
              <input type="text" class="form-control" value="+1 989757485">
            </div>
          </div>
          <div class="col-md-12">
            <div class="mb-3">
              <label class="col-form-label" for="reason">Message <span class="text-danger">*</span></label>
              <textarea class="form-control">Duis aute irure dolor in reprehenderit</textarea>
            </div>
          </div>
        </div>
      </div>
      <div class="submit-button text-end">
        <a href="javascript:void(0);" class="btn btn-light sidebar-close1">Cancel</a>
        <button  type="submit" class="btn btn-primary">Save Changes</button>
      </div>					
    </form>
  </div>			
</div>
<!-- /Edit Contact Message -->

<!-- Delete User -->
<div class="modal fade" id="delete_contact" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <div class="text-center">
          <div class="avatar avatar-xl bg-danger-light rounded-circle mb-3">
            <i class="ti ti-trash-x fs-36 text-danger"></i>
          </div>
          <h4 class="mb-2">Remove Contact Messages</h4>
          <p class="mb-0">Are you sure you want to remove it</p>
          <div class="d-flex align-items-center justify-content-center mt-4">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <a [routerLink]="routes.contactMessage" class="btn btn-danger">Yes, Delete it</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Delete User -->
