// vue/vue/src/views/pages/pages/authentication/two-step-verification.vue
<template>
  <div class="account-page">
    <div class="main-wrapper">
      <div class="account-content">
        <div class="d-flex flex-wrap w-100 vh-100 overflow-hidden account-bg-04">
          <div
            class="d-flex align-items-center justify-content-center flex-wrap vh-100 overflow-auto p-4 w-50 bg-backdrop"
          >
            <form
              method="get"
              class="digit-group login-form-control"
              data-group-name="digits"
              data-autosubmit="false"
              autocomplete="off"
              @submit.prevent="submitForm"
            >
              <div class="mx-auto mw-450">
                <div class="text-center mb-4">
                  <img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo" />
                </div>
                <div class="mb-4">
                  <h4 class="mb-2 fs-20">Login With Your Email Address</h4>
                  <p>
                    We sent a verification code to your email. Enter the code from the
                    email in the field below
                  </p>
                </div>
                <div class="d-flex align-items-center mb-4">
                  <input
                    type="text"
                    class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold me-3"
                    id="digit-1"
                    name="digit-1"
                    data-next="digit-2"
                    maxlength="1"
                  />
                  <input
                    type="text"
                    class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold me-3"
                    id="digit-2"
                    name="digit-2"
                    data-next="digit-3"
                    data-previous="digit-1"
                    maxlength="1"
                  />
                  <input
                    type="text"
                    class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold me-3"
                    id="digit-3"
                    name="digit-3"
                    data-next="digit-4"
                    data-previous="digit-2"
                    maxlength="1"
                  />
                  <input
                    type="text"
                    class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold"
                    id="digit-4"
                    name="digit-4"
                    data-next="digit-5"
                    data-previous="digit-3"
                    maxlength="1"
                  />
                </div>
                <div class="text-center mb-3">
                  <p class="badge badge-soft-purple shadow-none">
                    Otp will expire in 09 :10
                  </p>
                </div>
                <div class="mb-3">
                  <button type="submit" class="btn btn-primary w-100">
                    Verify My Account
                  </button>
                </div>
                <div class="text-center">
                  <p class="fw-medium text-gray">Copyright &copy; 2024 - CRMS</p>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {};
  },
  methods: {
    submitForm() {
      this.$router.push("/dashboard");
    },
  },
};
</script>

// angular/angular/src/app/auth/two-step-verification/two-step-verification/two-step-verification.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { routes } from '../../../../shared/routes/routes';

@Component({
    selector: 'app-two-step-verification',
    templateUrl: './two-step-verification.component.html',
    styleUrl: './two-step-verification.component.scss',
    standalone: false
})
export class TwoStepVerificationComponent {
  public routes = routes;
  constructor(private router: Router) {}

  public oneTimePassword = {
    data1: "",
    data2: "",
    data3: "",
    data4: ""
  };
  public ValueChanged(data: string, box: string): void {
    if (box == 'digit-1' && data.length > 0) {
      document.getElementById('digit-2')?.focus();
    } else if (box == 'digit-2' && data.length > 0) {
      document.getElementById('digit-3')?.focus();
    } else if (box == 'digit-3' && data.length > 0) {
      document.getElementById('digit-4')?.focus();
    } else {
      return
    }
  }
  public tiggerBackspace(data: string, box: string) {
    let StringyfyData;
    if (data) {
      StringyfyData = data.toString();
    } else {
      StringyfyData = null;
    }
    if (box == 'digit-4' && StringyfyData == null) {
      document.getElementById('digit-3')?.focus();
    } else if (box == 'digit-3' && StringyfyData == null) {
      document.getElementById('digit-2')?.focus();
    } else if (box == 'digit-2' && StringyfyData == null) {
      document.getElementById('digit-1')?.focus();
    }
  }
  navigation() {
    this.router.navigate([routes.dealsDashboard])
  }
}

<div class="account-content">
    <div class="d-flex flex-wrap w-100 vh-100 overflow-hidden account-bg-04">
        <div class="d-flex align-items-center justify-content-center flex-wrap vh-100 overflow-auto p-4 w-50 bg-backdrop">
            <form method="get" class="digit-group login-form-control" data-group-name="digits" data-autosubmit="false" autocomplete="off" >
                <div class="mx-auto mw-450">
                    <div class="text-center mb-4">
                        <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
                    </div>
                   <div class="mb-4">
                       <h4 class="mb-2 fs-20">Login With Your Email Address</h4>
                       <p>We sent a verification code to your email. Enter the code from the email in the field below</p>
                    </div>
                    <div class="d-flex align-items-center mb-4">
                        <input  class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold me-3" placeholder="0" [(ngModel)]="oneTimePassword.data1" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data1 , 'digit-1')" (input)="ValueChanged(oneTimePassword.data1 , 'digit-1')" type="text" id="digit-1" name="digit-1" data-next="digit-2" maxlength="1">
                        <input  class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold me-3" placeholder="0" [(ngModel)]="oneTimePassword.data2" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data2 , 'digit-2')" (input)="ValueChanged(oneTimePassword.data2 , 'digit-2')" type="text" id="digit-2" name="digit-2" data-next="digit-3" data-previous="digit-1" maxlength="1">
                        <input  class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold me-3" placeholder="0" [(ngModel)]="oneTimePassword.data3" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data3 , 'digit-3')" (input)="ValueChanged(oneTimePassword.data3 , 'digit-3')" type="text" id="digit-3" name="digit-3" data-next="digit-4" data-previous="digit-2" maxlength="1">
                        <input  class="border rounded w-100 py-sm-3 py-2 text-center fs-26 hw-bold me-3" placeholder="0" [(ngModel)]="oneTimePassword.data4" maxlength="1" (keydown.backspace)="tiggerBackspace(oneTimePassword.data4 , 'digit-4')"  (input)="ValueChanged(oneTimePassword.data4 , 'digit-4')" type="text" id="digit-4" name="digit-4" data-next="digit-5" data-previous="digit-3" maxlength="1">
                    </div>
                    <div class="text-center mb-3">
                       <p class="badge badge-soft-purple shadow-none">Otp will expire in 09 :10</p>
                    </div>
                    <div class="mb-3">
                       <button type="submit" class="btn btn-primary w-100" (click)="navigation()">Verify My Account</button>
                    </div>
                    <div class="text-center">
                        <p class="fw-medium text-gray">Copyright &copy; 2024 - CRMS</p>
                    </div>
               </div>
            </form>
        </div>
    </div>
</div>
