// angular/angular/src/app/feature-module/main-menu/application/call/call-history/call-history.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import Swal from 'sweetalert2';
import { routes } from '../../../../../../shared/routes/routes';
import { apiResultFormat, callHistory, pageSelection } from '../../../../../../shared/model/pages.model';
import { DataService } from '../../../../../../shared/data/data.service';
import { PaginationService, tablePageSize } from '../../../../../../shared/shared.index';
import { SidebarService } from '../../../../../../shared/sidebar/sidebar.service';
interface data {
  value: string;
}
@Component({
    selector: 'app-call-history',
    templateUrl: './call-history.component.html',
    styleUrl: './call-history.component.scss',
    standalone: false
})
export class CallHistoryComponent {
  initChecked = false;
  public routes = routes;
  public selectedValue1 = '';
  public selectedValue2 = '';
  public selectedValue3 = '';

  selectedList1: data[] = [
    { value: 'Sort by Date' },
    { value: 'Newest' },
    { value: 'Oldest' },
  ];
  selectedList2: data[] = [
    { value: 'Choose Name' },
    { value: 'Thomas' },
    { value: 'Rose' },
  ];
  selectedList3: data[] = [
    { value: 'Choose Calls' },
    { value: 'All Calls' },
    { value: 'Missed Calls' },
    { value: 'Outgoing Calls' },
    { value: 'Incoming Calls' },
  ];

  // pagination variables
  public tableData: callHistory[] = [];
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<callHistory>;
  public searchDataValue = '';
  //** / pagination variables

  constructor(
    private data: DataService,
    private pagination: PaginationService,
    private router: Router,
    private sidebar: SidebarService
  ) {
    this.data.getCallHistory().subscribe((apiRes: apiResultFormat) => {
      this.totalData = apiRes.totalData;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.callHistory) {
          this.getTableData({ skip: res.skip, limit: this.totalData });
          this.pageSize = res.pageSize;
        }
      });
    });
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getCallHistory().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: callHistory, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.sNo = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<callHistory>(this.tableData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }

  public searchData(value: string): void {
    this.dataSource.filter = value.trim().toLowerCase();
    this.tableData = this.dataSource.filteredData;
  }
  confirmColor() {
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: ' btn btn-success',
        cancelButton: 'me-2 btn btn-danger',
      },
      buttonsStyling: false,
    });

    swalWithBootstrapButtons
      .fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        confirmButtonText: 'Yes, delete it!',
        showCancelButton: true,
        cancelButtonText: 'Cancel',
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          swalWithBootstrapButtons.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          );
        } else if (result.dismiss === Swal.DismissReason.cancel) {
          swalWithBootstrapButtons.fire(
            'Cancelled',
            'Your imaginary file is safe :)',
            'error'
          );
        }
      });
  }
  public filter = false;
  openFilter() {
    this.filter = !this.filter;
  }


  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
}

<div class="page-wrapper">
  <div class="content">
    <div class="page-header">
      <div class="page-header menu">
        <div class="page-title">
          <h4>Call History</h4>
          <h6>Manage your products</h6>
        </div>
      </div>
    </div>
    <!-- /product list -->
    <div class="card table-list-card">
      <div class="card-body">
        <div class="table-responsive product-list">
          <table class="table  datanew list" matSort (matSortChange)="sortData($event)">
            <thead>
              <tr>
                <th class="no-sort">
                   <label class="checkboxs" (click)="selectAll(initChecked)"  (keydown.enter)="selectAll(initChecked)" tabindex="0"> 
                    <input type="checkbox" id="select-all" [(ngModel)]="initChecked">
                    <span class="checkmarks"></span>
                  </label>
                </th>
                <th mat-sort-header="username">Username</th>
                <th mat-sort-header="phoneNumber">Phone Number</th>
                <th mat-sort-header="callType">Call Type</th>
                <th mat-sort-header="duration">Duration</th>
                <th mat-sort-header="dateTime">Date & Time</th>
                <th class="no-sort">Action</th>
              </tr>
            </thead>
            <tbody>
              @for (data of tableData; track data) {
              <tr>
                <td>
                  <label class="checkboxs">
                    <input type="checkbox" [(ngModel)]="data.isSelected">
                    <span class="checkmarks"></span>
                  </label>
                </td>
                <td>
                  <div class="userimgname">
                    <a href="javascript:void(0);" class="product-img">
                      <img [src]="data.img" alt="product">
                    </a>
                    <a href="javascript:void(0);">{{data.username}}</a>
                  </div>
                </td>
                <td>{{data.phoneNumber}}</td>
                @if (data.audio === true) {
                <td class="phone-call-icon"><i class="feather icon-phone income-calls me-1"></i><i class="feather me-1"
                    [ngClass]="{'icon-arrow-down-left income-success': data.callType === 'Incoming Call' || data.callType === 'Outgoing Call', 'icon-arrow-down-right income-success-missed': data.callType === 'Missed Call'}"></i>{{data.callType}}
                </td>
                }
                @if (data.video === true) {
                <td class="phone-call-icon"><i class="feather icon-video income-calls me-1"></i><i class="feather me-1"
                    [ngClass]="{'icon-arrow-down-left income-success': data.callType === 'Incoming Call' || data.callType === 'Outgoing Call', 'icon-arrow-down-right income-success-missed': data.callType === 'Missed Call'}"></i>{{data.callType}}
                </td>
                }
                <td>{{data.duration}}</td>
                <td>{{data.dateTime}}</td>
                <td class="action-table-data">
                  <div class="edit-delete-action">
                    <a class="me-3 p-2" href="javascript:void(0);" data-bs-toggle="modal"
                      data-bs-target="#user-profile-new">
                      <i class="feather icon-eye feather-eye"></i>
                    </a>
                    <a class="confirm-text p-2" href="javascript:void(0);" (click)=confirmColor()>
                      <i class="feather icon-trash-2 feather-trash-2"></i>
                    </a>
                  </div>
                </td>
              </tr>
              }
            </tbody>
          </table>
        </div>
        <app-custom-pagination></app-custom-pagination>
      </div>
    </div>
    <!-- /product list -->
  </div>
</div>
<!-- details popup -->
<div class="modal fade" id="user-profile-new">
  <div class="modal-dialog history-modal-profile">
    <div class="modal-content">
      <div class="page-wrapper details-blk">
        <div class="content">
          <div class="text-center right-sidebar-profile mb-3">
            <figure class="avatar">
              <img src="assets/img/users/user-23.jpg" alt="image">
            </figure>
            <div class="chat-options chat-option-profile">
              <ul class="list-inline">
                <li class="list-inline-item">
                  <a [routerLink]="routes.audioCall" data-bs-dismiss class="btn btn-outline-light "
                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Voice Call"
                    matTooltip="Voice Call">
                    <i class="bx bx-phone"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a [routerLink]="routes.chat" class="btn btn-outline-light" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="" data-bs-original-title="Chat" matTooltip="Chat">
                    <i class="bx bx-message-square-dots"></i>
                  </a>
                </li>
                <li class="list-inline-item ">
                  <a [routerLink]="routes.videoCall" class="btn btn-outline-light profile-open" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" matTooltip="Video Call" data-bs-original-title="Video Call">
                    <i class="bx bx-video"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="modal-profile-detail">
            <div class="row">
              <div class="col-lg-6">
                <div class="modal-userlist">
                  <ul>
                    <li>Name<span>Thomas</span></li>
                    <li>Phone<span>+1 25182 94528</span></li>
                    <li>Email<span>thomas&#64;example.com</span></li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="modal-userlist d-flex justify-content-center">
                  <ul>
                    <li>Total Calls<span>20</span></li>
                    <li>Average Call Timing<span>0.30</span></li>
                    <li>Average Waiting Time<span>00.5</span></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /details popup -->

// vue/vue/src/views/pages/application/call/call-history.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>

  <div class="page-wrapper">
    <div class="content">
      <div class="page-header">
        <div class="page-header menu">
          <div class="page-title">
            <h4>Call History</h4>
            <h6>Manage your products</h6>
          </div>
        </div>
      </div>

      <!-- /product list -->
      <div class="card table-list-card">
        <div class="card-body">
          <div class="table-responsive product-list">
            <a-table :columns="columns" :data-source="data" :row-selection="{}">
              <template #bodyCell="{ column, record }">
                <template v-if="column.key === 'Username'">
                  <div class="userimgname d-flex align-items-center">
                    <a href="javascript:void(0);" class="product-img me-2">
                      <img
                        :src="require(`@/assets/img/users/${record.Image}`)"
                        alt="product"
                      />
                    </a>
                    <a href="javascript:void(0);">{{ record.Username }}</a>
                  </div>
                </template>
                <template v-else-if="column.key === 'Call_Type'">
                  <div class="phone-call-icon">
                    <vue-feather
                      :type="record.Icon"
                      class="income-calls me-1"
                    ></vue-feather
                    ><vue-feather
                      :type="record.Arrow_icon"
                      :class="record.Class"
                    ></vue-feather
                    >{{ record.Call_Type }}
                  </div>
                </template>
                <template v-else-if="column.key === 'action'">
                  <td class="action-table-data">
                    <div class="edit-delete-action">
                      <a
                        class="me-3 p-2"
                        href="javascript:void(0);"
                        data-bs-toggle="modal"
                        data-bs-target="#user-profile-new"
                      >
                        <vue-feather type="eye" class="eye"></vue-feather>
                      </a>
                      <a
                        class="confirm-text p-2"
                        @click="confirmDelete"
                        href="javascript:void(0);"
                      >
                        <vue-feather
                          type="trash-2"
                          class="trash-2"
                        ></vue-feather>
                      </a>
                    </div>
                  </td>
                </template>
              </template>
            </a-table>
          </div>
        </div>
      </div>
      <!-- /product list -->
    </div>
  </div>
</template>

<script>
const columns = [
  {
    sorter: true,
  },
  {
    title: "Username",
    dataIndex: "Username",
    key: "Username",
    sorter: {
      compare: (a, b) => {
        a = a.Username.toLowerCase();
        b = b.Username.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Phone Number",
    dataIndex: "Phone_Number",
    sorter: {
      compare: (a, b) => {
        a = a.Phone_Number.toLowerCase();
        b = b.Phone_Number.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Call Type",
    dataIndex: "Call_Type",
    key: "Call_Type",
    sorter: {
      compare: (a, b) => {
        a = a.Call_Type.toLowerCase();
        b = b.Call_Type.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Duration",
    dataIndex: "Duration",
    sorter: {
      compare: (a, b) => {
        a = a.Duration.toLowerCase();
        b = b.Duration.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Date & Time",
    dataIndex: "Date_Time",
    sorter: {
      compare: (a, b) => {
        a = a.Date_Time.toLowerCase();
        b = b.Date_Time.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Action",
    key: "action",
    sorter: true,
  },
];
const data = [
  {
    id: "",
    Image: "user-01.jpg",
    Username: "Arroon",
    Phone_Number: "+1 25182 94528",
    Icon: "phone",
    Arrow_icon: "arrow-down-left",
    Class: "income-success me-1",
    Call_Type: "Incoming Call",
    Duration: "0.25",
    Date_Time: "19 Jan 2023 - 01:16 PM",
  },
  {
    id: "",
    Image: "user-02.jpg",
    Username: "Rose",
    Phone_Number: "+1 93016 81932",
    Icon: "phone",
    Arrow_icon: "arrow-up-right",
    Class: "income-success-missed me-1",
    Call_Type: "Missed Call",
    Duration: "0",
    Date_Time: "24 Jan 2023 - 02:50 PM",
  },
  {
    id: "",
    Image: "user-03.jpg",
    Username: "Benjamin",
    Phone_Number: "+1 25182 94528",
    Icon: "video",
    Arrow_icon: "arrow-down-left",
    Class: "income-success me-1",
    Call_Type: "Incoming Call",
    Duration: "0.15",
    Date_Time: "03 Feb 2023 - 10:37 AM",
  },
  {
    id: "",
    Image: "user-04.jpg",
    Username: "Kaitlin",
    Phone_Number: "+1 70328 96042",
    Icon: "phone",
    Arrow_icon: "arrow-down-left",
    Class: "income-success-missed me-1",
    Call_Type: "Missed Call",
    Duration: "0",
    Date_Time: "17 Feb 2023 - 11:25 AM",
  },
  {
    id: "",
    Image: "user-05.jpg",
    Username: "Lilly",
    Phone_Number: "+1 83610 45175",
    Icon: "video",
    Arrow_icon: "arrow-up-right",
    Class: "income-success me-1",
    Call_Type: "Outgoing Call",
    Duration: "0.45",
    Date_Time: "14 Mar 2023 - 09:12 AM",
  },
  {
    id: "",
    Image: "user-08.jpg",
    Username: "Freda",
    Phone_Number: "+1 46217 84294",
    Icon: "phone",
    Arrow_icon: "arrow-down-left",
    Class: "income-success me-1",
    Call_Type: "Incoming Call",
    Duration: "0.3",
    Date_Time: "27 Mar 2023 - 04:32 PM",
  },
  {
    id: "",
    Image: "user-06.jpg",
    Username: "Alwin",
    Phone_Number: "+1 62573 84301",
    Icon: "phone",
    Arrow_icon: "arrow-up-right",
    Class: "income-success me-1",
    Call_Type: "Outgoing Call",
    Duration: "1.17",
    Date_Time: "13 Apr 2023 - 02:46 PM",
  },
  {
    id: "",
    Image: "user-07.jpg",
    Username: "Maybelle",
    Phone_Number: "+1 14693 63826",
    Icon: "video",
    Arrow_icon: "arrow-down-left",
    Class: "income-success-missed me-1",
    Call_Type: "Missed Call",
    Duration: "0",
    Date_Time: "11 Apr 2023 - 10:29 AM",
  },
  {
    id: "",
    Image: "user-10.jpg",
    Username: "Ellen",
    Phone_Number: "+1 83710 43827",
    Icon: "phone",
    Arrow_icon: "arrow-down-left",
    Class: "income-success me-1",
    Call_Type: "Incoming Call",
    Duration: "0.5",
    Date_Time: "14 May 2023 - 03:06 PM",
  },
  {
    id: "",
    Image: "user-12.jpg",
    Username: "Grace",
    Phone_Number: "+1 42695 07322",
    Icon: "video",
    Arrow_icon: "arrow-down-left",
    Class: "income-success-missed me-1",
    Call_Type: "Missed Call",
    Duration: "0",
    Date_Time: "29 May 2023 - 11:23 AM",
  },
];

import "sweetalert2/dist/sweetalert2.min.css";
import Swal from "sweetalert2";

export default {
  data() {
    return {
      columns,
      data,
      filter: false,
      Sort: ["Sort by Date", "Newest", "Oldest"],
      Choose: ["Choose Name", "Thomas", "Rose"],
      Calls: [
        "Choose Calls",
        "All Calls",
        "Missed Calls",
        "Outgoing Calls",
        "Incoming Calls",
      ],
    };
  },
  methods: {
    confirmDelete() {
      Swal.fire({
        title: "Are you sure?",
        text: "You won't be able to revert this!",
        showCancelButton: true,
        confirmButtonColor: "#3085d6",
        cancelButtonColor: "#d33",
        confirmButtonText: "Yes, delete it!",
        confirmButtonClass: "btn btn-primary",
        cancelButtonClass: "btn btn-danger ml-1",
        buttonsStyling: false,
      }).then((result) => {
        if (result.value) {
          Swal.fire({
            icon: "success",
            title: "Deleted!",
            text: "Your file has been deleted.",
            confirmButtonClass: "btn btn-success",
          });
        }
      });
    },
  },
};
</script>
