// nextjs/nextjs/template/src/components/auth/login.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import { all_routes } from "@/data/all_routes";

import Link from "next/link";
import React, { useState } from "react";


const Login = () => {
  const route = all_routes;
  const [isPasswordVisible, setPasswordVisible] = useState(false);

  const togglePasswordVisibility = () => {
    setPasswordVisible((prevState) => !prevState);
  };

  return (
    <div className="account-content">
      <div className="d-flex flex-wrap w-100 vh-100 overflow-hidden account-bg-01">
        <div className="d-flex align-items-center justify-content-center flex-wrap vh-100 overflow-auto p-4 w-50 bg-backdrop">
          <form className="flex-fill">
            <div className="mx-auto mw-450">
              <div className="text-center mb-4">
                <img
                  src="assets/img/logo.svg"
                  className="img-fluid"
                  alt="Logo"
                />
              </div>
              <div className="mb-4">
                <h4>Sign In</h4>
                <p>Access the CRMS panel using your email and passcode.</p>
              </div>
              <div className="mb-3">
                <label className="col-form-label">Email Address</label>
                <div className="position-relative">
                  <span className="input-icon-addon">
                    <i className="ti ti-mail"></i>
                  </span>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="mb-3">
                <label className="col-form-label">Password</label>
                <div className="pass-group">
                  <input
                    type={isPasswordVisible ? "text" : "password"}
                    className="pass-input form-control"
                  />
                  <span
                    className={`ti toggle-password ${
                      isPasswordVisible ? "ti-eye" : "ti-eye-off"
                    }`}
                    onClick={togglePasswordVisibility}
                  ></span>
                </div>
              </div>
              <div className="d-flex align-items-center justify-content-between mb-3">
                <div className="form-check form-check-md d-flex align-items-center">
                  <input
                    className="form-check-input"
                    type="checkbox"
                    value=""
                    id="checkebox-md"
                    defaultChecked
                  />
                  <label className="form-check-label" htmlFor="checkebox-md">
                    Remember Me
                  </label>
                </div>
                <div className="text-end">
                  <Link
                    href={route.forgotPassword}
                    className="text-primary fw-medium link-hover"
                  >
                    Forgot Password?
                  </Link>
                </div>
              </div>
              <div className="mb-3">
                <Link
                  href={route.dealsDashboard}
                  className="btn btn-primary w-100"
                >
                  Sign In
                </Link>
              </div>
              <div className="mb-3">
                <h6>
                  New on our platform?
                  <Link href={route.register} className="text-purple link-hover">
                    {" "}
                    Create an account
                  </Link>
                </h6>
              </div>
              <div className="form-set-login or-text mb-3">
                <h4>OR</h4>
              </div>
              <>
                <div className="d-flex align-items-center justify-content-center flex-wrap mb-3">
                  <div className="text-center me-2 flex-fill">
                    <Link
                      href="#"
                      className="br-10 p-2 px-4 btn bg-pending  d-flex align-items-center justify-content-center"
                    >
                      <img
                        className="img-fluid m-1"
                        src="assets/img/icons/facebook-logo.svg"
                        alt="Facebook"
                      />
                    </Link>
                  </div>
                  <div className="text-center me-2 flex-fill">
                    <Link
                      href="#"
                      className="br-10 p-2 px-4 btn bg-white d-flex align-items-center justify-content-center"
                    >
                      <img
                        className="img-fluid  m-1"
                        src="assets/img/icons/google-logo.svg"
                        alt="Facebook"
                      />
                    </Link>
                  </div>
                  <div className="text-center flex-fill">
                    <Link
                      href="#"
                      className="bg-dark br-10 p-2 px-4 btn btn-dark d-flex align-items-center justify-content-center"
                    >
                      <img
                        className="img-fluid  m-1"
                        src="assets/img/icons/apple-logo.svg"
                        alt="Apple"
                      />
                    </Link>
                  </div>
                </div>
                <div className="text-center">
                  <p className="fw-medium text-gray">Copyright © 2025 - CRMS</p>
                </div>
              </>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
};

export default Login;

// angular/angular/src/app/auth/login/login/login.component.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { routes } from '../../../../shared/routes/routes';

@Component({
    selector: 'app-login',
    templateUrl: './login.component.html',
    styleUrl: './login.component.scss',
    standalone: false
})
export class LoginComponent {
  public routes = routes;
  constructor(private router: Router) {}

  public navigate() {
    this.router.navigate([routes.dealsDashboard]);
  }
  public password : boolean[] = [false];

  public togglePassword(index: any){
    this.password[index] = !this.password[index]
  }
}

<div class="account-content">
    <div class="d-flex flex-wrap w-100 vh-100 overflow-hidden account-bg-01">
        <div class="d-flex align-items-center justify-content-center flex-wrap vh-100 overflow-auto p-4 w-50 bg-backdrop">
            <form  class="flex-fill">
                <div class="mx-auto mw-450">
                    <div class="text-center mb-4">
                       <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
                   </div>
                   <div class="mb-4">
                       <h4 class="mb-2 fs-20">Sign In</h4>
                       <p>Access the CRMS panel using your email and passcode.</p>
                   </div>
                   <div class="mb-3">
                       <label class="col-form-label" for="email">Email Address</label>
                       <div class="position-relative">
                            <span class="input-icon-addon">
                                <i class="ti ti-mail"></i>
                            </span>
                            <input type="text" value="" class="form-control">
                        </div>
                   </div>
                   <div class="mb-3">
                       <label class="col-form-label" for="Password">Password</label>
                       <div class="pass-group">
                        <input [type]="password[1] ? 'text' : 'password' " class="pass-input form-control">
                        <span class="ti toggle-password " [ngClass]=" password[1] ? 'ti-eye' : 'ti-eye-off'" (click)="togglePassword(1)"  (keydown.enter)="togglePassword(1)" tabindex="0"></span>
                    </div>
                   </div>
                   <div class="d-flex align-items-center justify-content-between mb-3">
                        <div class="form-check form-check-md d-flex align-items-center">
                            <input class="form-check-input" type="checkbox" value="" id="checkebox-md" checked="">
                            <label class="form-check-label" for="checkebox-md">
                                Remember Me
                            </label>
                        </div>
                       <div class="text-end">
                           <a [routerLink]="routes.forgotPassword"  class="text-primary fw-medium link-hover">Forgot Password?</a>
                       </div>
                   </div>
                   <div class="mb-3">
                       <button type="submit" class="btn btn-primary w-100" (click)="navigate()">Sign In</button>
                   </div>
                   <div class="mb-3">
                       <h6>New on our platform?<a [routerLink]="routes.register" class="text-purple link-hover"> Create an account</a></h6>
                   </div>
                   <div class="form-set-login or-text mb-3">
                       <h4>OR</h4>
                   </div>
                   <div class="d-flex align-items-center justify-content-center flex-wrap mb-3">
                        <div class="text-center me-2 flex-fill">
                            <a href="javascript:void(0);" class="br-10 p-2 px-4 btn bg-pending  d-flex align-items-center justify-content-center">
                                <img class="img-fluid m-1" src="assets/img/icons/facebook-logo.svg" alt="Facebook">
                            </a>
                        </div>
                        <div class="text-center me-2 flex-fill">
                            <a href="javascript:void(0);" class="br-10 p-2 px-4 btn bg-white d-flex align-items-center justify-content-center">
                                <img class="img-fluid  m-1" src="assets/img/icons/google-logo.svg" alt="Facebook">
                            </a>
                        </div>
                        <div class="text-center flex-fill">
                            <a href="javascript:void(0);" class="bg-dark br-10 p-2 px-4 btn btn-dark d-flex align-items-center justify-content-center">
                                <img class="img-fluid  m-1" src="assets/img/icons/apple-logo.svg" alt="Apple">
                            </a>
                        </div>
                    </div>
                    <div class="text-center">
                        <p class="fw-medium text-gray">Copyright &copy; 2024 - CRMS</p>
                    </div>
               </div>
            </form>
        </div>
    </div>
</div>
