// angular/angular/src/app/feature-module/main-menu/dashboard/deals-dashboard/deals-dashboard.component.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Component, Renderer2, ViewChild } from '@angular/core';
import {
  ApexAxisChartSeries,
  ApexChart,
  ChartComponent,
  ApexDataLabels,
  ApexXAxis,
  ApexPlotOptions,
} from 'ng-apexcharts';
import { routes } from '../../../../../shared/routes/routes';
import { CommonService } from '../../../../../shared/common/common.service';
export interface ChartOptions {
  series: ApexAxisChartSeries | any;
  chart: ApexChart | any;
  dataLabels: ApexDataLabels | any;
  plotOptions: ApexPlotOptions | any;
  xaxis: ApexXAxis | any;
}
@Component({
    selector: 'app-deals-dashboard',
    templateUrl: './deals-dashboard.component.html',
    styleUrl: './deals-dashboard.component.scss',
    standalone: false
})
export class DealsDashboardComponent {
  public routes =  routes
  bsValue = new Date();
  bsRangeValue: Date[];
  maxDate = new Date();
  base = '';
  page = '';
  last = '';
  @ViewChild('chart') chart!: ChartComponent;
  public chartOptions: Partial<ChartOptions>;
  public chartOptions2: Partial<ChartOptions> | any;
  public chartOptions3: Partial<ChartOptions> | any;
  public chartOptions4: Partial<ChartOptions> | any;

  constructor( private common: CommonService, private renderer: Renderer2,) {
    this.chartOptions = {
      series: [
        {
          data: [400, 220, 448],
          color: '#FC0027',
        },
      ],
      chart: {
        type: 'bar',
        height: 150,
      },
      plotOptions: {
        bar: {
          horizontal: true,
        },
      },
      dataLabels: {
        enabled: false,
      },

      xaxis: {
        categories: ['Conversation', 'Follow Up', 'Inpipeline'],
      },
    };
    this.chartOptions2 = {
      series: [
        {
          data: [400, 220, 448],
          color: '#77D882',
        },
      ],
      chart: {
        type: 'bar',
        height: 150,
      },
      plotOptions: {
        bar: {
          horizontal: true,
        },
      },
      dataLabels: {
        enabled: false,
      },

      xaxis: {
        categories: ['Conversation', 'Follow Up', 'Inpipeline'],
      },
    };
    this.chartOptions3 = {
      series: [
        {
          name: 'sales',
          colors: ['#FFC38F'],
          data: [
            {
              x: 'Inpipeline',
              y: 400,
            },
            {
              x: 'Follow Up',
              y: 130,
            },
            {
              x: 'Schedule',
              y: 248,
            },
            {
              x: 'Conversation',
              y: 470,
            },
            {
              x: 'Won',
              y: 470,
            },
            {
              x: 'Lost',
              y: 180,
            },
          ],
        },
      ],
      colors: ['#00918E'],
      chart: {
        type: 'bar',
        height: 275,
      },
      plotOptions: {
        bar: {
          borderRadiusApplication: 'around',
          columnWidth: '40%',
        },
      },

      xaxis: {
        type: 'category',
        group: {
          style: {
            fontSize: '7px',
            fontWeight: 700,
          },
        },
      },
      yaxis: {
        min: 0,
        max: 500,
        tickAmount: 5,
      }
    };
    this.chartOptions4 = {
      series: [
        {
          name: 'Deals',
          data: [10, 20, 30, 15, 22, 40, 30, 20, 30, 18, 30, 60],
        },
      ],
      colors: ['#E41F07'],
      chart: {
        height: 273,
        type: 'area',
        zoom: {
          enabled: false,
        },
      },
      dataLabels: {
        enabled: false,
      },
      stroke: {
        curve: 'straight',
      },
      xaxis: {
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
      },
    };
    this.maxDate.setDate(this.maxDate.getDate() + 7);
    this.bsRangeValue = [this.bsValue, this.maxDate];
    this.common.base.subscribe((base: string) => {
      this.base = base;
    });
    this.common.page.subscribe((page: string) => {
      this.page = page;
    });
    this.common.last.subscribe((last: string) => {
      this.last = last;
    });
    if (this.page == 'deals-dashboard') {
      this.renderer.addClass(document.body, 'date-picker-dashboard');
    }
  }

}

<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-md-4">
              <h3 class="page-title">Deals Dashboard</h3>
            </div>
            <div class="col-md-8 float-end ms-auto">
              <div class="d-flex title-head">
                <div
                  class="daterange-picker d-flex align-items-center justify-content-center"
                >
                  <div class="form-sort me-2">
                    <i class="ti ti-calendar"></i>
                    <input
                      type="text"
                      class="form-control date-range bookingrange"
                      bsDaterangepicker
                      [bsConfig]="{ adaptivePosition: true }"
                      [(ngModel)]="bsRangeValue"
                    />
                  </div>
                  <div class="head-icons mb-0">
                    <a
                      [routerLink]="routes.dealsDashboard"
                      data-bs-toggle="tooltip"
                      data-bs-placement="top"
                      data-bs-original-title="Refresh"
                      matTooltip="Refresh"
                      ><i class="ti ti-refresh-dot"></i
                    ></a>
                    <app-collapse-header></app-collapse-header>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 d-flex">
        <div class="card flex-fill">
          <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
              <h4><i class="ti ti-grip-vertical me-1"></i>Recently Created Deals</h4>
              <div class="dropdown">
                <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                  <i class="ti ti-calendar-check me-2"></i>Last 30 days
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                  <a href="javascript:void(0);" class="dropdown-item">
                    Last 15 days
                  </a>
                  <a href="javascript:void(0);" class="dropdown-item">
                    Last 30 days
                  </a>
                </div>
              </div>
            </div>
            
          </div>
          <div class="card-body">
           
            <div class="table-responsive custom-table">
              <table class="table dataTable" id="deals-project">
                <thead class="thead-light">
                  <tr>
                    <th>Deal Name</th>
                    <th>Stage</th>
                    <th>Deal Value</th>
                    <th>Probability</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <tr class="odd">
                    <td>Collins</td>
                    <td>Conversation</td>
                    <td>$04,51,000</td>
                    <td>85%</td>
                    <td>
                      <span class="badge badge-pill bg-danger">Lost</span>
                    </td>
                  </tr>
                  <tr class="even">
                    <td>Konopelski</td>
                    <td>Pipeline</td>
                    <td>$14,51,000</td>
                    <td>56%</td>
                    <td>
                      <span class="badge badge-pill bg-success">Won</span>
                    </td>
                  </tr>
                  <tr class="odd">
                    <td>Adams</td>
                    <td>Won</td>
                    <td>$12,51,000</td>
                    <td>15%</td>
                    <td>
                      <span class="badge badge-pill bg-success">Won</span>
                    </td>
                  </tr>
                  <tr class="even">
                    <td>Schumm</td>
                    <td>Lost</td>
                    <td>$51,000</td>
                    <td>45%</td>
                    <td>
                      <span class="badge badge-pill bg-danger">Lost</span>
                    </td>
                  </tr>
                  <tr class="odd">
                    <td>Wisozk</td>
                    <td>Follow Up</td>
                    <td>$67,000</td>
                    <td>5%</td>
                    <td>
                      <span class="badge badge-pill bg-success">Won</span>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 d-flex">
        <div class="card flex-fill">
          <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
              <h4><i class="ti ti-grip-vertical me-1"></i>Deals By Stage</h4>
              <div class="d-flex align-items-center flex-wrap row-gap-2">
                <div class="dropdown me-2">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Sales Pipeline
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">														
                    <a href="javascript:void(0);" class="dropdown-item">
                      Marketing Pipeline
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Sales Pipeline
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Email
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Chats
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Operational
                    </a>
                  </div>										
                </div>
                <div class="dropdown">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Last 30 Days
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 30 Days
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 15 Days
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 7 Days
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div id="deals-chart">
              <apx-chart
                [series]="chartOptions3.series"
                [chart]="chartOptions3.chart"
                [dataLabels]="chartOptions3.dataLabels"
                [plotOptions]="chartOptions3.plotOptions"
                [yaxis]="chartOptions3.yaxis"
                [xaxis]="chartOptions3.xaxis"
                [stroke]="chartOptions3.stroke"
                [grid]="chartOptions3.grid"
                [fill]="chartOptions3.fill"
                [annotations]="chartOptions3.annotations"
                [colors]="chartOptions3.colors"
              ></apx-chart>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 d-flex">
        <div class="card flex-fill">
          <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
              <h4><i class="ti ti-grip-vertical me-1"></i>Leads By Stage</h4>
              <div class="d-flex align-items-center flex-wrap row-gap-2">
                <div class="dropdown me-2">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Marketing Pipeline
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">														
                    <a href="javascript:void(0);" class="dropdown-item">
                      Marketing Pipeline
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Sales Pipeline
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Email
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Chats
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Operational
                    </a>
                  </div>										
                </div>
                <div class="dropdown">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Last 3 months
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 3 months
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 6 months
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 12 months
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div id="last-chart">
              <apx-chart
                [series]="chartOptions.series"
                [chart]="chartOptions.chart"
                [dataLabels]="chartOptions.dataLabels"
                [plotOptions]="chartOptions.plotOptions"
                [xaxis]="chartOptions.xaxis"
              ></apx-chart>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 d-flex">
        <div class="card flex-fill">
          <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
              <h4><i class="ti ti-grip-vertical me-1"></i>Won Deals Stage</h4>
              <div class="d-flex align-items-center flex-wrap row-gap-2">
                <div class="dropdown me-2">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Marketing Pipeline
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">														
                    <a href="javascript:void(0);" class="dropdown-item">
                      Marketing Pipeline
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Sales Pipeline
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Email
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Chats
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Operational
                    </a>
                  </div>										
                </div>
                <div class="dropdown">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Last 3 months
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 3 months
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 6 months
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 12 months
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
           
            <div id="won-chart">
              <apx-chart
                [series]="chartOptions2.series"
                [chart]="chartOptions2.chart"
                [dataLabels]="chartOptions2.dataLabels"
                [plotOptions]="chartOptions2.plotOptions"
                [xaxis]="chartOptions2.xaxis"
              ></apx-chart>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
      <div class="col-md-12 d-flex">
        <div class="card w-100">
          <div class="card-header border-0 pb-0">
            <div class="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
              <h4><i class="ti ti-grip-vertical me-1"></i>Deals by Year</h4>
              <div class="d-flex align-items-center flex-wrap row-gap-2">
                <div class="dropdown me-2">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Sales Pipeline
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">
                        
                    <a href="javascript:void(0);" class="dropdown-item">
                      Marketing Pipeline
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Sales Pipeline
                    </a>
                  </div>						
                </div>
                <div class="dropdown">
                  <a class="dropdown-toggle" data-bs-toggle="dropdown" href="javascript:void(0);">
                    Last 3 months
                  </a>
                  <div class="dropdown-menu dropdown-menu-end">
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 3 months
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 6 months
                    </a>
                    <a href="javascript:void(0);" class="dropdown-item">
                      Last 12 months
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div id="deals-year">
              <apx-chart
                [series]="chartOptions4.series"
                [chart]="chartOptions4.chart"
                [xaxis]="chartOptions4.xaxis"
                [dataLabels]="chartOptions4.dataLabels"
                [grid]="chartOptions4.grid"
                [stroke]="chartOptions4.stroke"
                [title]="chartOptions4.title"
                [colors]="chartOptions4.colors"
              ></apx-chart>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

// nextjs/nextjs/template/src/components/mainMenu/dealsDashboard/index.tsx
"use client";
/* eslint-disable @next/next/no-img-element */

import ApexCharts from "apexcharts";
import React, { useEffect, useRef, useState } from "react";
import DateRangePicker from "react-bootstrap-daterangepicker";
import "bootstrap-daterangepicker/daterangepicker.css";
import CollapseHeader from "@/core/common/collapse-header";
import Link from "next/link";
import ChartRef from "@/components/charts/chartsRef";
import LeadsByStage from "@/components/charts/LeadsBySatge";
import WonChart from "@/components/charts/wonChat";
import DealsByYears from "@/components/charts/dealsByYear";

const DealsDashboard = () => {
  const initialSettings = {
    endDate: new Date("2020-08-11T12:30:00.000Z"),
    ranges: {
      "Last 30 Days": [
        new Date("2020-07-12T04:57:17.076Z"),
        new Date("2020-08-10T04:57:17.076Z"),
      ],
      "Last 7 Days": [
        new Date("2020-08-04T04:57:17.076Z"),
        new Date("2020-08-10T04:57:17.076Z"),
      ],
      "Last Month": [
        new Date("2020-06-30T18:30:00.000Z"),
        new Date("2020-07-31T18:29:59.999Z"),
      ],
      "This Month": [
        new Date("2020-07-31T18:30:00.000Z"),
        new Date("2020-08-31T18:29:59.999Z"),
      ],
      Today: [
        new Date("2020-08-10T04:57:17.076Z"),
        new Date("2020-08-10T04:57:17.076Z"),
      ],
      Yesterday: [
        new Date("2020-08-09T04:57:17.076Z"),
        new Date("2020-08-09T04:57:17.076Z"),
      ],
    },
    startDate: new Date("2020-08-04T04:57:17.076Z"), // Set "Last 7 Days" as default
    timePicker: false,
  };

  return (
    <>
      <div className="page-wrapper">
        <div className="content">
          <div className="row">
            <div className="col-md-12">
              <div className="page-header">
                <div className="row align-items-center ">
                  <div className="col-md-4">
                    <h3 className="page-title">Deals Dashboard</h3>
                  </div>
                  <div className="col-md-8 float-end ms-auto">
                    <div className="d-flex title-head">
                      <div className="daterange-picker d-flex align-items-center justify-content-center">
                        <div className="form-sort me-2">
                          <i className="ti ti-calendar" />
                          <DateRangePicker initialSettings={initialSettings}>
                            <input
                              className="form-control bookingrange"
                              type="text"
                            />
                          </DateRangePicker>
                        </div>
                        <div className="head-icons mb-0">
                          <CollapseHeader />
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6 d-flex">
              <div className="card flex-fill">
                <div className="card-header border-0 pb-0">
                  <div className="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                    <h4>
                      <i className="ti ti-grip-vertical me-1" />
                      Recently Created Deals
                    </h4>
                    <div className="dropdown">
                      <Link
                        className="dropdown-toggle"
                        data-bs-toggle="dropdown"
                        href="#"
                      >
                        <i className="ti ti-calendar-check me-2" />
                        Last 30 days
                      </Link>
                      <div className="dropdown-menu dropdown-menu-end">
                        <Link href="#" className="dropdown-item">
                          Last 15 days
                        </Link>
                        <Link href="#" className="dropdown-item">
                          Last 30 days
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card-body">
                  <div className="table-responsive custom-table">
                    <table className="table dataTable" id="deals-project">
                      <thead className="thead-light">
                        <tr>
                          <th>Deal Name</th>
                          <th>Stage</th>
                          <th>Deal Value</th>
                          <th>Probability</th>
                          <th>Status</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr className="odd">
                          <td>Collins</td>
                          <td>Conversation</td>
                          <td>$04,51,000</td>
                          <td>85%</td>
                          <td>
                            <span className="badge badge-pill  bg-danger">
                              Lost
                            </span>
                          </td>
                        </tr>
                        <tr className="even">
                          <td>Konopelski</td>
                          <td>Pipeline</td>
                          <td>$14,51,000</td>
                          <td>56%</td>
                          <td>
                            <span className="badge badge-pill  bg-success">
                              Won
                            </span>
                          </td>
                        </tr>
                        <tr className="odd">
                          <td>Adams</td>
                          <td>Won</td>
                          <td>$12,51,000</td>
                          <td>15%</td>
                          <td>
                            <span className="badge badge-pill  bg-success">
                              Won
                            </span>
                          </td>
                        </tr>
                        <tr className="even">
                          <td>Schumm</td>
                          <td>Lost</td>
                          <td>$51,000</td>
                          <td>45%</td>
                          <td>
                            <span className="badge badge-pill  bg-danger">
                              Lost
                            </span>
                          </td>
                        </tr>
                        <tr className="odd">
                          <td>Wisozk</td>
                          <td>Follow Up</td>
                          <td>$67,000</td>
                          <td>5%</td>
                          <td>
                            <span className="badge badge-pill  bg-success">
                              Won
                            </span>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-6 d-flex">
              <div className="card flex-fill">
                <div className="card-header border-0 pb-0">
                  <div className="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                    <h4>
                      <i className="ti ti-grip-vertical me-1" />
                      Deals By Stage
                    </h4>
                    <div className="d-flex align-items-center flex-wrap row-gap-2">
                      <div className="dropdown me-2">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Sales Pipeline
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Marketing Pipeline
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Sales Pipeline
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Email
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Chats
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Operational
                          </Link>
                        </div>
                      </div>
                      <div className="dropdown">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Last 30 Days
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Last 30 Days
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 15 Days
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 7 Days
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card-body">
                  <div id="deals-chart">
                    <ChartRef />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6 d-flex">
              <div className="card flex-fill">
                <div className="card-header border-0 pb-0">
                  <div className="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                    <h4>
                      <i className="ti ti-grip-vertical me-1" />
                      Leads By Stage
                    </h4>
                    <div className="d-flex align-items-center flex-wrap row-gap-2">
                      <div className="dropdown me-2">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Marketing Pipeline
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Marketing Pipeline
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Sales Pipeline
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Email
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Chats
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Operational
                          </Link>
                        </div>
                      </div>
                      <div className="dropdown">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Last 3 months
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Last 3 months
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 6 months
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 12 months
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card-body">
                  <div id="last-chart">
                    <LeadsByStage />
                  </div>
                </div>
              </div>
            </div>
            <div className="col-md-6 d-flex">
              <div className="card flex-fill">
                <div className="card-header border-0 pb-0">
                  <div className="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                    <h4>
                      <i className="ti ti-grip-vertical me-1" />
                      Won Deals Stage
                    </h4>
                    <div className="d-flex align-items-center flex-wrap row-gap-2">
                      <div className="dropdown me-2">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Marketing Pipeline
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Marketing Pipeline
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Sales Pipeline
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Email
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Chats
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Operational
                          </Link>
                        </div>
                      </div>
                      <div className="dropdown">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Last 3 months
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Last 3 months
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 6 months
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 12 months
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card-body">
                  <div id="won-chart">
                    <WonChart />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-12 d-flex">
              <div className="card w-100">
                <div className="card-header border-0 pb-0">
                  <div className="d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                    <h4>
                      <i className="ti ti-grip-vertical me-1" />
                      Deals by Year
                    </h4>
                    <div className="d-flex align-items-center flex-wrap row-gap-2">
                      <div className="dropdown me-2">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Sales Pipeline
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Marketing Pipeline
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Sales Pipeline
                          </Link>
                        </div>
                      </div>
                      <div className="dropdown">
                        <Link
                          className="dropdown-toggle"
                          data-bs-toggle="dropdown"
                          href="#"
                        >
                          Last 3 months
                        </Link>
                        <div className="dropdown-menu dropdown-menu-end">
                          <Link href="#" className="dropdown-item">
                            Last 3 months
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 6 months
                          </Link>
                          <Link href="#" className="dropdown-item">
                            Last 12 months
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="card-body">
                  <div id="deals-year">
                    <DealsByYears />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default DealsDashboard;
