// nextjs/nextjs/template/src/components/uiinterface/table/data-tables.tsx
"use client";
/* eslint-disable @next/next/no-img-element */

import React, { useState } from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import { pageDataTablesData } from "@/data/json/pageDataTables";
import Table from "../../../core/common/dataTable/index";

const DataTablesComponent = () => {
  const data = pageDataTablesData;
  const route = all_routes;
  const columns = [
    {
      title: "Name",
      dataIndex: "name",
      key: "name",
      sorter: (a:any, b:any) => a.name.length - b.name.length,
    },
    {
      title: "Position",
      dataIndex: "position",
      key: "position",
      sorter: (a:any, b:any) => a.position.length - b.position.length,
    },
    {
      title: "Office",
      dataIndex: "office",
      key: "office",
      sorter: (a:any, b:any) => a.office.length - b.office.length,
    },
    {
      title: "Age",
      dataIndex: "age",
      key: "age",
      sorter: (a:any, b:any) => a.age.length - b.age.length,
    },
    {
      title: "Start Date",
      dataIndex: "startDate",
      key: "startDate",
      sorter: (a:any, b:any) => a.startDate.length - b.startDate.length,
    },
    {
      title: "Salary",
      dataIndex: "salary",
      key: "salary",
      sorter: (a:any, b:any) => a.salary.length - b.salary.length,
    },
  ];
  const [searchText, setSearchText] = useState("");
  const handleSearch = (e:any) => {
    setSearchText(e.target.value);
  };

  const filteredData = data.filter((entry:any) => {
    return Object.keys(entry).some((key:any) => {
      return String(entry[key])
        .toLowerCase()
        .includes(searchText.toLowerCase());
    });
  });
  return (
    <div>
      <div className="page-wrapper">
        <div className="content container-fluid">
          {/* Page Header */}
          <div className="page-header">
            <div className="row">
              <div className="col">
                <h3 className="page-title">Data Tables</h3>
                <ul className="breadcrumb">
                  <li className="breadcrumb-item">
                    <Link href={route.dealsDashboard}>Dashboard</Link>
                  </li>
                  <li className="breadcrumb-item active">Data Tables</li>
                </ul>
              </div>
            </div>
          </div>
          {/* /Page Header */}
          <div className="row">
            <div className="col-sm-12">
              <div className="card">
                <div className="card-header">
                  <h4 className="card-title">Default Datatable</h4>
                  <p className="card-text">
                    This is the most basic example of the datatables with zero
                    configuration. Use the <code>.datatable</code> class to
                    initialize datatables.
                  </p>
                </div>
                <div className="card-body">
                  <div className="table-responsive">
                    <div
                      id="DataTables_Table_0_filter"
                      className="dataTables_filter custom-data-table-react"
                    >
                      <label>
                        {" "}
                        <input
                          type="search"
                          className="form-control form-control-sm"
                          placeholder="Search"
                          aria-controls="DataTables_Table_0"
                          value={searchText}
                          onChange={handleSearch}
                        />
                      </label>
                    </div>
                    <Table columns={columns} dataSource={filteredData}  />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DataTablesComponent;

// angular/angular/src/app/feature-module/ui-interface/table/data-tables/data-tables.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { DataService } from '../../../../../shared/data/data.service';
import { dataTables, apiResultFormat } from '../../../../../shared/model/pages.model';
import { routes } from '../../../../../shared/routes/routes';
import { PaginationService, tablePageSize, pageSelection } from '../../../../../shared/shared.index';


@Component({
    selector: 'app-data-tables',
    templateUrl: './data-tables.component.html',
    styleUrls: ['./data-tables.component.scss'],
    standalone: false
})
export class DataTablesComponent {
  initChecked = false;
  public tableData: dataTables[] = [];
  public tableDataCopy: dataTables[] = [];
  public actualData: dataTables[] = [];
  public routes = routes;
  // pagination variables
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<dataTables>;
  public searchDataValue = '';

  constructor(
    private data: DataService,
    private router: Router,
    private pagination: PaginationService
  ) {
    this.data.getDataTable().subscribe((apiRes: apiResultFormat) => {
      this.actualData = apiRes.data;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.dataTable) {
          this.getTableData({ skip: res.skip, limit: res.limit });
          this.pageSize = res.pageSize;
        }
      });
    });
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getDataTable().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.tableDataCopy = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: dataTables, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.sNo = serialNumber;
          this.tableData.push(res);
          this.tableDataCopy.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<dataTables>(this.actualData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        tableDataCopy: this.tableDataCopy,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public searchData(value: string): void {
    if (value == '') {
      this.tableData = this.tableDataCopy;
    } else {
      this.dataSource.filter = value.trim().toLowerCase();
      this.tableData = this.dataSource.filteredData;
    }
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();

    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];

        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }

  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
}

<!-- Page Header -->
<div class="page-header">
  <div class="row">
    <div class="col">
      <h3 class="page-title">Data Tables</h3>
    </div>
  </div>
</div>
<!-- /Page Header -->
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Default Datatable</h4>
        <p class="card-text">
          This is the most basic example of the datatables with zero configuration. Use the
          <code>.datatable</code> class to initialize datatables.
        </p>
      </div>
      <div class="card-body">
        <div class="table-top">
          <div class="dataTables_filter">
            <label>
              <input
                [(ngModel)]="searchDataValue" [ngModelOptions]="{standalone: true}"
                (ngModelChange)="searchData(searchDataValue)"
                type="search"
                class="form-control"
                placeholder="Search..."
                />
              </label>
            </div>
          </div>
          <div class="table-responsive">
            <table (matSortChange)="sortData($event)" matSort matSortActive="Sno" matSortDirection="asc"
              matSortDisableClear class="table datanew">
              <thead>
                <tr>
                  <th mat-sort-header="Name">Name</th>
                  <th mat-sort-header="Position">Position</th>
                  <th mat-sort-header="Office">Office</th>
                  <th mat-sort-header="Age">Age</th>
                  <th mat-sort-header="Startdate">Start date</th>
                  <th mat-sort-header="Salary">Salary</th>
                </tr>
              </thead>
              <tbody>
                @for (table of tableData; track table) {
                  <tr>
                    <td>{{table.name}}</td>
                    <td>{{table.position}}</td>
                    <td>{{table.office}}</td>
                    <td>{{table.age}}</td>
                    <td>{{table.startDate}}</td>
                    <td>{{table.salary}}</td>
                  </tr>
                }
                @if (tableData.length === 0) {
                  <tr>
                    <td colspan="12">
                      <h5 class="no-record">No matching records found</h5>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
            
          </div>
          <app-custom-pagination></app-custom-pagination>
        </div>
      </div>
    </div>
  </div>
