// nextjs/nextjs/template/src/core/common/sidebar/index.tsx
"use client";
/* eslint-disable @next/next/no-img-element */

import React, { useEffect, useState } from "react";
import Scrollbars from "react-custom-scrollbars-2";
import { SidebarData } from "../../../data/json/sidebarData";
import { useDispatch, useSelector } from "react-redux";
import { setExpandMenu } from "../../../data/redux/commonSlice";
import Link from "next/link";
import { all_routes } from "@/data/all_routes";
import { usePathname } from "next/navigation";
import Cookies from "js-cookie";



const Sidebar = () => {
  const pathname = usePathname();
  const dispatch = useDispatch();

  const [subOpen, setSubopen] = useState<string | null>("");
  const [subsidebar, setSubsidebar] = useState<string>("");

  const toggleSidebar = (title: string) => {
    Cookies.set("menuOpened", title);
    if (title === subOpen) {
      setSubopen("");
    } else {
      setSubopen(title);
    }
  };

  const toggleSubsidebar = (subitem: string) => {
    if (subitem === subsidebar) {
      setSubsidebar("");
    } else {
      setSubsidebar(subitem);
    }
  };

  const toggle = () => {
    dispatch(setExpandMenu(true));
  };

  const toggle2 = () => {
    dispatch(setExpandMenu(false));
  };

  useEffect(() => {
    const savedMenu = Cookies.get("menuOpened");
    setSubopen(savedMenu || "");

    const submenus = document.querySelectorAll(".submenu");
    submenus.forEach((submenu) => {
      submenu.classList.remove("active");
      const listItems = submenu.querySelectorAll("li");
      listItems.forEach((item) => {
        if (item.classList.contains("active")) {
          submenu.classList.add("active");
        }
      });
    });
  }, [pathname]);

  
  const [expandMenus, setExpandMenus] = useState(false); 
  const expandMenu = () => {
    setExpandMenus(false);
    document.body.classList.remove("expand-menu");
  };

  const expandMenuOpen = () => {
    setExpandMenus(true);
    document.body.classList.add("expand-menu");
  };

  return (
    <>
      <div
        className="sidebar"
        id="sidebar"
        onMouseLeave={expandMenu}
        onMouseOver={expandMenuOpen}
      >
        <Scrollbars className="react-scrollbar">
          <div className="sidebar-inner slimscroll">
            <>
              <div className="modern-profile p-3 pb-0">
                <div className="sidebar-nav mb-3">
                  <ul
                    className="nav nav-tabs nav-tabs-solid nav-tabs-rounded nav-justified bg-transparent"
                    role="tablist"
                  >
                    <li className="nav-item">
                      <Link className="nav-link active border-0" href="#">
                        Menu
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link
                        className="nav-link border-0"
                        href={all_routes.chat}
                      >
                        Chats
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link
                        className="nav-link border-0"
                        href={all_routes.email}
                      >
                        Inbox
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              <div className="sidebar-header p-3 pb-0 pt-2">
                <div className="d-flex align-items-center justify-content-between menu-item mb-3">
                  <div className="me-3">
                    <Link
                      href={all_routes.calendar}
                      className="btn btn-icon border btn-menubar"
                    >
                      <i className="ti ti-layout-grid-remove" />
                    </Link>
                  </div>
                  <div className="me-3">
                    <Link
                      href={all_routes.chat}
                      className="btn btn-icon border btn-menubar position-relative"
                    >
                      <i className="ti ti-brand-hipchat" />
                    </Link>
                  </div>
                  <div className="me-3 notification-item">
                    <Link
                      href={all_routes.activities}
                      className="btn btn-icon border btn-menubar position-relative me-1"
                    >
                      <i className="ti ti-bell" />
                      <span className="notification-status-dot" />
                    </Link>
                  </div>
                  <div className="me-0">
                    <Link
                      href={all_routes.email}
                      className="btn btn-icon border btn-menubar"
                    >
                      <i className="ti ti-message" />
                    </Link>
                  </div>
                </div>
              </div>
            </>
            <div id="sidebar-menu" className="sidebar-menu">
              <ul>
                <li className="clinicdropdown theme">
                  <Link href="/profile">
                    <img
                      src="assets/img/profiles/avatar-14.jpg"
                      className="img-fluid"
                      alt="Profile"
                    />
                    <div className="user-names">
                      <h5>Adrian Davies</h5>
                      <h6>Tech Lead</h6>
                    </div>
                  </Link>
                </li>
              </ul>

              <ul>
                {SidebarData?.map((mainLabel, index) => (
                  <li className="clinicdropdown" key={index}>
                    <h6 className="submenu-hdr">{mainLabel?.label}</h6>
                    <ul>
                      {mainLabel?.submenuItems?.map((title: any, i) => {
                        let link_array: any = [];
                        if ("submenuItems" in title) {
                          title.submenuItems?.forEach((link: any) => {
                            link_array.push(link?.link);
                            if (link?.submenu && "submenuItems" in link) {
                              link.submenuItems?.forEach((item: any) => {
                                link_array.push(item?.link);
                              });
                            }
                          });
                        }
                        title.links = link_array;

                        return (
                          <li className="submenu" key={title.label}>
                            <Link
                              href={title?.submenu ? "#" : title?.link || "#"}
                              onClick={() => toggleSidebar(title?.label)}
                              className={`  ${
                                subOpen === title?.label ? "subdrop" : ""
                              } 
                             ${
                               title?.links?.includes(pathname) ? "active" : ""
                             }  ${
                                [
                                  ...(title?.submenuItems?.map(
                                    (link: any) => link?.link
                                  ) || []),
                                  title?.link,
                                  title?.subLink1,
                                  title?.subLink2,
                                  title?.subLink3,
                                  title?.subLink4,
                                ].includes(pathname)
                                  ? "active"
                                  : ""
                              }
  `}
                            >
                              <i className={title?.icon}></i>
                              <span>{title?.label}</span>
                              {title?.submenu && (
                                <span className="menu-arrow" />
                              )}
                            </Link>

                            <ul
                              style={{
                                display:
                                  subOpen === title?.label ? "block" : "none",
                              }}
                            >
                              {title?.submenuItems?.map((item: any) => (
                                <li
                                  className="submenu submenu-two"
                                  key={item.label}
                                >
                                  <Link
                                    href={item?.link || "#"}
                                    className={`${
                                      item?.submenuItems
                                        ?.map((link: any) => link?.link)
                                        .includes(pathname) ||
                                      item?.link === pathname
                                        ? "active"
                                        : ""
                                    }
                                    ${
                                      subsidebar === item?.label ? "subdrop" : ""
                                      } `}
                                    onClick={() => {
                                      toggleSubsidebar(item?.label);
                                    }}
                                  >
                                    {item?.label}
                                    <span
                                      className={
                                        item?.submenu ? "menu-arrow" : ""
                                      }
                                    />
                                  </Link>
                                  <ul
                                    style={{
                                      display:
                                        subsidebar === item?.label
                                          ? "block"
                                          : "none",
                                    }}
                                  >
                                    {item?.submenuItems?.map((items: any) => (
                                      <li key={items.label}>
                                        <Link
                                          href={items?.link || "#"}
                                          className={`${
                                            subsidebar === items?.label
                                              ? "submenu-two subdrop"
                                              : "submenu-two"
                                          } ${
                                            items?.submenuItems
                                              ?.map((link: any) => link.link)
                                              .includes(pathname) ||
                                            items?.link === pathname
                                              ? "active"
                                              : ""
                                          }`}
                                        >
                                          {items?.label}
                                        </Link>
                                      </li>
                                    ))}
                                  </ul>
                                </li>
                              ))}
                            </ul>
                          </li>
                        );
                      })}
                    </ul>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </Scrollbars>
      </div>
    </>
  );
};

export default Sidebar;

// angular/angular/src/app/feature-module/common/sidebar/sidebar.component.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';
import { MenuItem, SubMenu, url } from '../../../../shared/model/sidebar.model';
import {  NavigationStart, Router, Event as RouterEvent } from '@angular/router';
import { SidebarService } from '../../../../shared/sidebar/sidebar.service';
import { DataService } from '../../../../shared/data/data.service';
import { CommonService } from '../../../../shared/common/common.service';

@Component({
    selector: 'app-sidebar',
    templateUrl: './sidebar.component.html',
    styleUrl: './sidebar.component.scss',
    standalone: false
})
export class SidebarComponent  {
  public routes = routes;
  base = '';
  page = '';
  last = '';

  currentUrl = '';

   
  public side_bar_data: any[] = [];

  constructor(
    private sidebar: SidebarService,
    private data: DataService,
    private router: Router,
    private common: CommonService
  ) {
    router.events.subscribe((event: RouterEvent) => {
      if (event instanceof NavigationStart) {
        this.getRoutes(event);
        const splitVal = event.url.split('/');
        this.currentUrl = event.url;
        this.base = splitVal[1];
        this.page = splitVal[2];
      }
    });
    this.getRoutes(this.router);
    this.side_bar_data = this.data.sidebarData1;
    this.common.base.subscribe((res: string) => {
      this.base = res;
    });
    this.common.page.subscribe((res: string) => {
      this.page = res;
    });
    this.common.page.subscribe((res: string) => {
      this.last = res;
    });
  }

  private getRoutes(route: url): void {
    const splitVal = route.url.split('/');
    this.currentUrl = route.url;
    this.base = splitVal[1];
    this.page = splitVal[2];
  }

  public miniSideBarMouseHover(position: string): void {
    if (position == 'over') {
      this.sidebar.expandSideBar.next(true);
    } else {
      this.sidebar.expandSideBar.next(false);
    }
  }
  currentOpenSecondMenu: MenuItem | null = null;

  expandSubMenus(menu: MenuItem): void {
    sessionStorage.setItem('menuValue', menu.menuValue);
    this.side_bar_data.forEach((mainMenus: MenuItem) => {
      mainMenus.menu.forEach((resMenu: SubMenu) => {
        if (resMenu.menuValue === menu.menuValue) {
          menu.showSubRoute = !menu.showSubRoute;
        } else {
          resMenu.showSubRoute = false;
        }
      });
    });
    // this.side_bar_data.forEach((mainMenu: any) => {
    //   mainMenu.menu.forEach((submenu: any) => {
    //     if (submenu !== menu) {
    //       submenu.showSubRoute = false;
    //     }
    //   });
    // });
    // menu.showSubRoute = !menu.showSubRoute;

  }

  openMenuItem: MenuItem | null = null;
  openSubmenuOneItem: SubMenu[] | null = null;
  multiLevel1 = false;
  multiLevel2 = false;
  multiLevel3 = false;

  openMenu(menu: MenuItem): void {
    this.side_bar_data.forEach((mainMenu: any) => {
      if (mainMenu !== menu) {
        mainMenu.menu.forEach((submenu: any) => {
          submenu.showSubRoute = false;
        });
      }
    });
    if (this.openMenuItem === menu) {
      this.openMenuItem = null;
    } else {
      this.openMenuItem = menu;
    }
  }

  openSubmenuOne(subMenus: SubMenu[]): void {
    if (this.openSubmenuOneItem === subMenus) {
      this.openSubmenuOneItem = null;
    } else {
      this.openSubmenuOneItem = subMenus;
    }
  }

  multiLevelOne() {
    this.multiLevel1 = !this.multiLevel1;
  }
  multiLevelTwo() {
    this.multiLevel2 = !this.multiLevel2;
  }
  multiLevelThree() {
    this.multiLevel3 = !this.multiLevel3;
  }
 
}

<!-- Sidebar -->
<div class="sidebar" id="sidebar" (mouseover)="miniSideBarMouseHover('over')" (mouseout)="miniSideBarMouseHover('out')" (focus)="miniSideBarMouseHover('over')" (blur)="miniSideBarMouseHover('out')" tabindex="0"     >
  <div class="modern-profile p-3 pb-0">

    <div class="sidebar-nav mb-3">
      <ul class="nav nav-tabs nav-tabs-solid nav-tabs-rounded nav-justified bg-transparent"
        role="tablist">
        <li class="nav-item"><a class="nav-link active border-0" href="#">Menu</a></li>
        <li class="nav-item"><a class="nav-link border-0" [routerLink]="routes.chat">Chats</a></li>
        <li class="nav-item"><a class="nav-link border-0" [routerLink]="routes.email">Inbox</a></li>
      </ul>
    </div>
  </div>
  <div class="sidebar-header p-3 pb-0 pt-2">

    <div class="d-flex align-items-center justify-content-between menu-item mb-3">
      <div class="me-3">
        <a [routerLink]="routes.calendar" class="btn btn-icon border btn-menubar">
          <i class="ti ti-layout-grid-remove"></i>
        </a>
      </div>
      <div class="me-3">
        <a [routerLink]="routes.chat" class="btn btn-icon border btn-menubar position-relative">
          <i class="ti ti-brand-hipchat"></i>
        </a>
      </div>
      <div class="me-3 notification-item">
        <a [routerLink]="routes.activities" class="btn btn-icon border btn-menubar position-relative me-1">
          <i class="ti ti-bell"></i>
          <span class="notification-status-dot"></span>
        </a>
      </div>
      <div class="me-0">
        <a [routerLink]="routes.email" class="btn btn-icon border btn-menubar">
          <i class="ti ti-message"></i>
        </a>
      </div>
    </div>
  </div>
  <div class="sidebar-inner slimscroll">
    <ng-scrollbar>
      <div id="sidebar-menu" class="sidebar-menu">
        <ul>
          <li class="clinicdropdown">
            <a [routerLink] = "routes.generalSettings">
              <img src="assets/img/profiles/avatar-14.jpg" class="img-fluid" alt="Profile">
              <div class="user-names">
                <h5>Adrian Davies</h5>
                <h6>Tech Lead</h6>
              </div>
            </a>
          </li>
        </ul>
        <ul>
          @for (mainTittle of side_bar_data; track mainTittle) {
          <li class="submenu-open">
            <h6 class="submenu-hdr">{{ mainTittle.tittle }}</h6>
            <ul>
              @for (menu of mainTittle?.menu; track menu) {
              @if (menu?.hasSubRoute === false) {
              <li>
                <a   [routerLink]="menu?.route" [class.active]="base === menu.base || page === menu.base"><i class="ti" [class]="'ti-' + menu.icon"></i>
                  <span>{{ menu?.menuValue }}</span>
                </a>
              </li>
              }
              @if (menu.hasSubRoute === true) {
              <li class="submenu">
                <a  href="javascript:void(0)" (click)="expandSubMenus(menu)"
                  [ngClass]="{ 'subdrop': menu.showSubRoute === true}"
                  [class.active]="base === menu.base1 || base === menu.base || page === menu.page">
                  <i class="ti" [class]="'ti-' + menu.icon"></i>
                  <span>{{ menu.menuValue }}</span>
                  <span class="menu-arrow"></span>
                </a>
                <ul [ngClass]="
                          menu.showSubRoute === true
                            ? 'show-sub-menu'
                            : 'hide-sub-menu'
                        ">
                  @for (subMenus of menu.subMenus; track subMenus) {
                  <li>
                    <a [routerLink]="subMenus.route" routerLinkActive="active">{{ subMenus.menuValue }}</a>
                  </li>
                  }
                </ul>
              </li>
              }
              @if (menu.hasSubRouteTwo === true) {
              <li class="submenu">
                <a href="javascript:void(0);" (click)="openMenu(menu)" [ngClass]="{'subdrop' : openMenuItem === menu}"
                  [class.active]="base === menu.base"><i class="ti" [class]="'ti-' + menu.icon"></i><span>
                    {{menu.menuValue }}</span><span class="menu-arrow"></span></a>
                <ul [ngClass]="openMenuItem === menu ? 'show-sub-menu' : 'hide-sub-menu'">
                  @for (subMenus of menu.subMenus; track subMenus) {
                  @if (subMenus.customSubmenuTwo === false) {
                  <li><a [routerLink]="subMenus.route" routerLinkActive="active">{{ subMenus.menuValue }}</a></li>
                  }
                  @if (subMenus.customSubmenuTwo === true) {
                  <li class="submenu submenu-two">
                    <a href="javascript:void(0);"
                      [class.active]="page === subMenus.page1 || page === subMenus.page2 || page === subMenus.page3 || page === subMenus.page4 || page === subMenus.page5 || page === subMenus.page6 || page === subMenus.page7 || page === subMenus.page8"
                      (click)="openSubmenuOne(subMenus)" [ngClass]="{'subdrop' : openSubmenuOneItem === subMenus}">
                      {{ subMenus.menuValue }}
                      <span class="menu-arrow inside-submenu"></span>
                    </a>
                    <ul [ngClass]="openSubmenuOneItem === subMenus ? 'show-sub-menu' : 'hide-sub-menu'">
                      @for (subMenuTwo of subMenus.subMenusTwo; track subMenuTwo) {
                      <li>
                        <a [routerLink]="subMenuTwo.route" routerLinkActive="active">{{ subMenuTwo.menuValue
                          }}</a>
                      </li>
                      }
                    </ul>
                  </li>
                  }
                  }
                </ul>
              </li>
              }
              @if (menu.hasSubRouteThree === true) {
              <li class="submenu">
                <a href="javascript:void(0);" (click)="multiLevelOne()"
                  [ngClass]="{'subdrop' : multiLevel1 === true}"><i class="ti"
                    [class]="'ti-' + menu.icon"></i><span>{{menu.menuValue }}</span><span class="menu-arrow"></span></a>
                <ul [ngClass]="multiLevel1 ? 'show-sub-menu' : 'hide-sub-menu'">
                  @for (subMenus of menu.subMenus; track subMenus) {
                  @if (subMenus.customSubmenuThree === false) {
                  <li><a href="javascript:void(0);">{{ subMenus.menuValue }}</a></li>
                  }
                  @if (subMenus.customSubmenuThree === true) {
                  <li class="submenu submenu-two"><a href="javascript:void(0);" (click)="multiLevelTwo()"
                      [ngClass]="{'subdrop' : multiLevel2 === true}">{{
                      subMenus.menuValue }}<span class="menu-arrow inside-submenu"></span></a>
                    <ul [ngClass]="multiLevel2 ? 'show-sub-menu' : 'hide-sub-menu'">
                      @for (subMenuTwo of subMenus.subMenusTwo; track subMenuTwo) {
                      @if (subMenuTwo.customSubmenuFour === false) {
                      <li><a href="javascript:void(0);">{{ subMenuTwo.menuValue }}</a></li>
                      }
                      @if (subMenuTwo.customSubmenuFour === true) {
                      <li class="submenu submenu-two submenu-three">
                        <a href="javascript:void(0);" (click)="multiLevelThree()"
                          [ngClass]="{'subdrop' : multiLevel3 === true}">
                          {{ subMenuTwo.menuValue }}
                          <span class="menu-arrow inside-submenu inside-submenu-two"></span>
                        </a>
                        <ul [ngClass]="multiLevel3 ? 'show-sub-menu' : 'hide-sub-menu'">
                          @for (subMenusThree of subMenuTwo.subMenusThree; track subMenusThree) {
                          <li><a href="javascript:void(0);">{{ subMenusThree.menuValue }}</a></li>
                          }
                        </ul>
                      </li>
                      }
                      }
                    </ul>
                  </li>
                  }
                  }
                </ul>
              </li>
              }
              }
            </ul>
          </li>
          }
        </ul>
      </div>
    </ng-scrollbar>
  </div>
</div>
<!-- /Sidebar -->
