// vue/vue/src/views/pages/pages/authentication/lock-screen.vue
<template>
  <div class="account-page">
    <div class="main-wrapper">
      <div class="account-content">
        <div class="d-flex flex-wrap w-100 vh-100 overflow-hidden">
          <div
            class="d-flex align-items-center justify-content-center flex-fill flex-wrap vh-100 overflow-auto"
          >
            <div class="login-shapes">
              <div class="login-right-shape">
                <img src="@/assets/img/authentication/shape-01.png" alt="Shape" />
              </div>
              <div class="login-left-shape">
                <img src="@/assets/img/authentication/shape-02.png" alt="Shape" />
              </div>
            </div>
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-md-5">
                  <div class="login-content user-login">
                    <div class="text-center mb-4">
                      <img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo" />
                    </div>
                    <form @submit.prevent="submitForm">
                      <div class="card border p-sm-3">
                        <div class="card-body p-4">
                          <div class="text-center">
                            <p class="text-default mb-3">Welcome back!</p>
                            <div class="mb-3">
                              <span class="avatar avatar-xxxl rounded-circle mb-4"
                                ><img
                                  src="@/assets/img/profiles/avatar-14.jpg"
                                  class="img-fluid rounded-circle"
                                  alt="Profile"
                              /></span>
                              <h5 class="fs-18 fw-semibold">Adrian Davies</h5>
                            </div>
                          </div>
                          <div class="mb-3">
                            <label class="col-form-label">Enter Password</label>
                            <div class="pass-group">
                              <input type="password" class="pass-input form-control" />
                              <span class="ti toggle-password ti-eye-off"></span>
                            </div>
                          </div>
                          <div class="mb-0">
                            <button type="submit" class="btn btn-primary w-100">
                              Log In
                            </button>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                  <div
                    class="d-flex align-items-center flex-wrap row-gap-2 justify-content-center mb-4"
                  >
                    <a href="javascript:void(0);" class="fw-medium me-3"
                      >Terms & Condition</a
                    >
                    <a href="javascript:void(0);" class="fw-medium me-3">Privacy</a>
                    <a href="javascript:void(0);" class="fw-medium me-3">Help</a>
                    <div class="dropdown">
                      <a
                        href="javascript:void(0);"
                        class="dropdown-toggle fw-medium border-0 p-0 bg-transparent shadow-none"
                        data-bs-toggle="dropdown"
                        >English</a
                      >
                      <div class="dropdown-menu dropdown-menu-end">
                        <a href="javascript:void(0);" class="dropdown-item">French</a>
                        <a href="javascript:void(0);" class="dropdown-item">Spanish</a>
                      </div>
                    </div>
                  </div>
                  <div class="text-center">
                    <p class="fw-medium text-gray">Copyright &copy; 2024 - CRMS</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {};
  },
  methods: {
    submitForm() {
      this.$router.push("/dashboard");
    },
  },
};
</script>

// angular/angular/src/app/auth/lock-screen/lock-screen.component.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Component, Renderer2, OnDestroy } from '@angular/core';
import { routes } from '../../../shared/routes/routes';
import { CommonService } from '../../../shared/common/common.service';
import { Router } from '@angular/router';


@Component({
    selector: 'app-lock-screen',
    templateUrl: './lock-screen.component.html',
    styleUrl: './lock-screen.component.scss',
    standalone: false
})
export class LockScreenComponent implements OnDestroy {
  public routes = routes;
  public password : boolean[] = [false];

  public togglePassword(index: any){
    this.password[index] = !this.password[index]
  }

  base = '';
  page = '';
  last = '';
  constructor(
    private common: CommonService,
    private renderer: Renderer2,
    private router: Router
  ) {
    this.common.base.subscribe((res: string) => {
      this.base = res;
    });
    this.common.page.subscribe((res: string) => {
      this.page = res;
    });
    this.common.last.subscribe((res: string) => {
      this.last = res;
    });
    if (this.base == 'lock-screen') {
      this.renderer.addClass(document.body, 'account-page');
    }
  }
  ngOnDestroy(): void {
    this.renderer.removeClass(document.body, 'account-page');
  }
  
  public navigate() {
    this.router.navigate([routes.login]);
  }
}

<div class="account-content">
    <div class="d-flex flex-wrap w-100 vh-100 overflow-hidden">
        <div class="d-flex align-items-center justify-content-center flex-fill flex-wrap vh-100 overflow-auto">
            <div class="login-shapes">
                <div class="login-right-shape">
                    <img src="assets/img/authentication/shape-01.png" alt="Shape">
                </div>
                <div class="login-left-shape">
                    <img src="assets/img/authentication/shape-02.png" alt="Shape"> 
                </div> 
            </div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-5">
                        <div class="login-content user-login">
                            <div class="text-center mb-4">
                            <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
                        </div>
                            <form >
                                <div class="card border p-sm-3">
                                    <div class="card-body p-4">
                                        <div class="text-center">
                                            <p class="text-default mb-3">Welcome back!</p>
                                            <div class="mb-3">
                                                <span class="avatar avatar-xxxl rounded-circle mb-4"><img src="assets/img/profiles/avatar-14.jpg" class="img-fluid rounded-circle" alt="Profile"></span>
                                                <h5 class="fs-18 fw-semibold">Adrian Davies</h5>
                                            </div>
                                        </div>
                                        <div class="mb-3">
                                            <label class="col-form-label" for="password">Enter Password</label>
                                            <div class="pass-group">
                                                <input [type]="password[1] ? 'text' : 'password' " class="pass-input form-control">
                                                <span class="ti toggle-password " [ngClass]=" password[1] ? 'ti-eye' : 'ti-eye-off'" (click)="togglePassword(1)"  (keydown.enter)="togglePassword(1)"
                                                tabindex="0"></span>
                                               </div>
                                        </div>
                                        <div class="mb-0">
                                            <button type="submit" class="btn btn-primary w-100" (click)="navigate()">Log In</button>
                                        </div>
                                    </div>
                            </div>
                            </form>
                        </div>
                        <div class="d-flex align-items-center flex-wrap row-gap-2 justify-content-center mb-4">
                            <a href="javascript:void(0);" class="fw-medium me-3">Terms & Condition</a>
                            <a href="javascript:void(0);" class="fw-medium me-3">Privacy</a>
                            <a href="javascript:void(0);" class="fw-medium me-3">Help</a>
                            <div class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle fw-medium border-0 p-0 bg-transparent shadow-none" data-bs-toggle="dropdown">English</a>
                                <div class="dropdown-menu dropdown-menu-end">
                                    <a href="javascript:void(0);" class="dropdown-item">French</a>
                                    <a href="javascript:void(0);" class="dropdown-item">Spanish</a>
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <p class="fw-medium text-gray">Copyright &copy; 2024 - CRMS</p>
                        </div>
                    </div>
                </div>
            
            </div>
        </div>
    </div>
</div>
