// vue/vue/src/views/pages/pages/authentication/email-verification.vue
<template>
  <div class="account-page">
    <div class="main-wrapper">
      <div class="account-content">
        <div class="d-flex flex-wrap w-100 vh-100 overflow-hidden account-bg-04">
          <div
            class="d-flex align-items-center justify-content-center flex-wrap vh-100 overflow-auto p-4 w-50 bg-backdrop"
          >
            <form @submit.prevent="submitForm">
              <div class="mx-auto mw-450">
                <div class="text-center mb-4">
                  <img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo" />
                </div>
                <div class="text-center mb-3">
                  <span class="avatar avatar-xl rounded-circle bg-success mb-4"
                    ><i class="ti ti-check fs-26"></i
                  ></span>
                  <h4 class="mb-2 fs-20">Verify Your Email</h4>
                  <p class="mb-3">
                    We've sent a link to your email ter4@example.com. Please <br />
                    follow the link inside to continue
                  </p>
                  <h6>
                    Didn't receive an email?
                    <a href="javascript:void(0);" class="text-purple link-hover">
                      Resend Link</a
                    >
                  </h6>
                </div>
                <div class="mb-3">
                  <button type="submit" class="btn btn-primary w-100">Skip Now</button>
                </div>
                <div class="text-center">
                  <p class="fw-medium text-gray">Copyright &copy; 2024 - CRMS</p>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {};
  },
  methods: {
    submitForm() {
      this.$router.push("/dashboard/deals-dashboard");
    },
  },
};
</script>

// nextjs/nextjs/template/src/components/auth/emailVerification.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import React from "react";

const EmailVerification = () => {
  const route = all_routes;

  return (
    <div className="account-content">
  <div className="d-flex flex-wrap w-100 vh-100 overflow-hidden account-bg-04">
    <div className="d-flex align-items-center justify-content-center flex-wrap vh-100 overflow-auto p-4 w-50 bg-backdrop">
      <form>
        <div className="mx-auto mw-450">
          <div className="text-center mb-4">
            <img src="assets/img/logo.svg" className="img-fluid" alt="Logo" />
          </div>
          <div className="text-center mb-3">
            <span className="avatar avatar-xl rounded-circle bg-success mb-4">
              <i className="ti ti-check fs-26" />
            </span>
            <h4 className="mb-2 fs-20">Verify Your Email</h4>
            <p className="mb-3">
              We've sent a link to your email ter4@example.com. Please <br />{" "}
              follow the link inside to continue
            </p>
            <h6>
              Didn't receive an email?{" "}
              <Link href="#" className="text-purple link-hover">
                {" "}
                Resend Link
              </Link>
            </h6>
          </div>
          <div className="mb-3">
          
            <Link href={route.dealsDashboard} className="btn btn-primary w-100">
                  Skip Now
                </Link>
          </div>
          <div className="text-center">
            <p className="fw-medium text-gray">Copyright © 2025 - CRMS</p>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

  );
};

export default EmailVerification;
