// angular/angular/src/app/feature-module/settings/website-settings/prefixes/prefixes.component.ts
import { Component } from '@angular/core';
import { DataService } from '../../../../../shared/data/data.service';
import { routes } from '../../../../../shared/routes/routes';

@Component({
    selector: 'app-prefixes',
    templateUrl: './prefixes.component.html',
    styleUrl: './prefixes.component.scss',
    standalone: false
})
export class PrefixesComponent {
  public routes = routes;
  constructor( private data: DataService){}


  
  public filter = false;
  openFilter() {
    this.filter = !this.filter;
  }
}

<!-- Page Wrapper -->
<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">

        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h4 class="page-title">Settings</h4>
            </div>
            <div class="col-4 text-end">
              <div class="head-icons">
                <a [routerLink] = "routes.prefixes" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-original-title="Refresh" matTooltip="Refresh"><i class="ti ti-refresh-dot"></i></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <!-- Settings Menu -->
        <div class="card">
          <div class="card-body pb-0 pt-2">
            <ul class="nav nav-tabs nav-tabs-bottom">
              <li class="nav-item me-3">
                <a [routerLink] = "routes.generalSettings" class="nav-link px-0">
                  <i class="ti ti-settings-cog me-2"></i>General Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.companySettings" class="nav-link px-0 active">
                  <i class="ti ti-world-cog me-2"></i>Website Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.invoiceSettings" class="nav-link px-0">
                  <i class="ti ti-apps me-2"></i>App Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.emailSettings" class="nav-link px-0">
                  <i class="ti ti-device-laptop me-2"></i>System Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.paymentGatewaySettings" class="nav-link px-0">
                  <i class="ti ti-moneybag me-2"></i>Financial Settings
                </a>
              </li>
              <li class="nav-item">
                <a [routerLink] = "routes.storageSettings" class="nav-link px-0">
                  <i class="ti ti-flag-cog me-2"></i>Other Settings
                </a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /Settings Menu -->

        <div class="row">
          <div class="col-xl-3 col-lg-12 theiaStickySidebar">
            <div class="stickybar">
              <!-- Settings Sidebar -->
              <div class="card">
                <div class="card-body">
                  <div class="settings-sidebar">
                    <h4 class="fw-semibold mb-3">Website Settings</h4>
                    <div class="list-group list-group-flush settings-sidebar">
                      <a [routerLink] = "routes.companySettings" class="fw-medium">Company Settings</a>
                      <a [routerLink] = "routes.localizationSettings" class="fw-medium">Localization</a>
                      <a [routerLink] = "routes.prefixes" class="fw-medium active">Prefixes</a>
                      <a [routerLink] = "routes.preference" class="fw-medium">Preference</a>
                      <a [routerLink] = "routes.appearance" class="fw-medium">Appearance</a>
                      <a [routerLink] = "routes.languageSettings"class="fw-medium">Language</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Settings Sidebar -->
            </div>
          </div>

          <div class="col-xl-9 col-lg-12">

            <!-- Prefixes -->
            <div class="card">
              <div class="card-body">
                <h4 class="fw-semibold mb-3">Prefixes</h4>
                <form>
                  <div class="row">
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="products">Products(SKU)</label>
                        <input type="text" class="form-control" value="SKU - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="supplier">Supplier</label>
                        <input type="text" class="form-control" value="SUP - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="purchase">Purchase</label>
                        <input type="text" class="form-control" value="PU - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="purchase">Purchase Return</label>
                        <input type="text" class="form-control" value="PR - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="sales">Sales</label>
                        <input type="text" class="form-control" value="SA - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="salesreturn">Sales Return</label>
                        <input type="text" class="form-control" value="SR -  ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="customer">Customer</label>
                        <input type="text" class="form-control" value="CT - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="expense">Expense</label>
                        <input type="text" class="form-control" value="EX - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="stock">Stock Transfer</label>
                        <input type="text" class="form-control" value="ST -  ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="stock">Stock Adjustment</label>
                        <input type="text" class="form-control" value="SA -  ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="order">Sales Order</label>
                        <input type="text" class="form-control" value="SO - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="invoice">Invoice</label>
                        <input type="text" class="form-control" value="INV -  ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="estimation">Estimation</label>
                        <input type="text" class="form-control" value="EST - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="transaction">Transaction</label>
                        <input type="text" class="form-control" value="TRN - ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="employee">Employee</label>
                        <input type="text" class="form-control" value="EMP -  ">
                      </div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                      <div class="mb-3">
                        <label class="col-form-label" for="purchase">Purchase Return</label>
                        <input type="text" class="form-control" value="PR -  ">
                      </div>
                    </div>
                  </div>
                  <div class="submit-button">
                    <a href="javascript:void(0);" class="btn btn-light">Cancel</a>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                  </div>
                </form>
              </div>
            </div>
            <!-- /Prefixes -->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Page Wrapper -->

<!-- Add Translation -->
<div class="modal custom-modal fade" id="add_translation" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Translation</h5>
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <div class="modal-body">
        <form >
          <div class="mb-3">
            <label class="col-form-label" for="language">Language <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="col-form-label" for="code">Code <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="col-form-label" for="status">Status</label>
            <div class="radio-wrap">
              <div class="d-flex flex-wrap">
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="add-active" name="status" checked="">
                  <label for="add-active">Active</label>
                </div>
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="add-inactive" name="status">
                  <label for="add-inactive">Inactive</label>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-btn">
            <a href="javascript:void(0);" class="btn btn-light" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- /Add Translation -->

<!-- Edit Translation -->
<div class="modal custom-modal fade" id="edit_translation" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Translation</h5>
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <div class="modal-body">
        <form >
          <div class="mb-3">
            <label class="col-form-label" for="language">Language <span class="text-danger">*</span></label>
            <input type="text" class="form-control" value="English">
          </div>
          <div class="mb-3">
            <label class="col-form-label" for="code">Code <span class="text-danger">*</span></label>
            <input type="text" class="form-control" value="en">
          </div>
          <div class="mb-3">
            <label class="col-form-label" for="status">Status</label>
            <div class="radio-wrap">
              <div class="d-flex flex-wrap">
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="edit-active" name="status" checked="">
                  <label for="edit-active">Active</label>
                </div>
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="edit-inactive" name="status">
                  <label for="edit-inactive">Inactive</label>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-btn">
            <a href="javascript:void(0);" class="btn btn-light" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- /Edit Translation -->

<!-- Import Sample -->
<div class="modal custom-modal fade" id="import_sample" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import Sample</h5>
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <div class="modal-body">
        <form >
          <div class="mb-3">
            <label class="col-form-label" for="file">File <span class="text-danger">*</span></label>
            <mat-select class="select custom-mat-select" placeholder="Inventory">
              <mat-option value="inventory">Inventory</mat-option>
              <mat-option value="expense">Expense</mat-option>
              <mat-option value="product">Product</mat-option>
            </mat-select>
          </div>
          <div class="mb-3">
            <label class="col-form-label" for="language">Language <span class="text-danger">*</span></label>
            <mat-select class="select custom-mat-select" placeholder="English">
              <mat-option value="Choose">Choose</mat-option>
                          <mat-option value="English">English</mat-option>
                          <mat-option value="Arabic">Arabic</mat-option>
                          <mat-option value="German">French</mat-option>
                          <mat-option value="German">German</mat-option>
            </mat-select>
          </div>
          <div class="mb-3">
            <div class="drag-attach">
              <input type="file">
              <div class="img-upload">
                <i class="ti ti-file-broken"></i>Upload File
              </div>
            </div>
          </div>
          <div class="mb-3">
            <label class="col-form-label" for="uploaded">Uploaded Files</label>
            <div class="upload-file">
              <h6>Projectneonals teyys.xls</h6>
              <p>4.25 MB</p>
              <div class="progress">
                <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25"
                  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <p class="black-text">45%</p>
            </div>
            <div class="upload-file upload-list">
              <div>
                <h6>tes.txt</h6>
                <p>4.25 MB</p>
              </div>
              <a href="javascript:void(0);" class="text-danger"><i class="ti ti-trash-x"></i></a>
            </div>
          </div>
          <div class="modal-btn">
            <a href="javascript:void(0);" class="btn btn-light" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- /Import Sample -->

<!-- Delete Translation -->
<div class="modal custom-modal fade" id="delete_translation" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header border-0 m-0 justify-content-end">
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <div class="modal-body">
        <form >
          <div class="success-message text-center">
            <div class="success-popup-icon">
              <i class="ti ti-trash-x"></i>
            </div>
            <h3>Remove Translation?</h3>
            <p class="del-info">Are you sure you want to remove it.</p>
            <div class="col-lg-12 text-center modal-btn">
              <a href="javascript:void(0);" class="btn btn-light" data-bs-dismiss="modal">Cancel</a>
              <button type="submit" class="btn btn-danger">Yes, Delete it</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- /Delete Translation -->

// nextjs/nextjs/template/src/components/settings/websiteSettings/prefixes.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import CollapseHeader from "../../../core/common/collapse-header";
import Select from "react-select";

const PrefixesComponent = () => {
  const route = all_routes; 
   const fileData = [
    { value: "Inventory", label: "1" },
    { value: "Expense", label: "2" },
    { value: "Product", label: "3" },
  ];
  const languageOptions = [
    { value: "english", label: "English" },
    { value: "spanish", label: "Spanish" },
  ];
  return (
    <div>
      {/* Page Wrapper */}
      <div className="page-wrapper">
        <div className="content">
          <div className="row">
            <div className="col-md-12">
              {/* Page Header */}
              <div className="page-header">
                <div className="row align-items-center">
                  <div className="col-8">
                    <h4 className="page-title">Settings</h4>
                  </div>
                  <div className="col-4 text-end">
                    <div className="head-icons">
                      <CollapseHeader />
                    </div>
                  </div>
                </div>
              </div>
              {/* /Page Header */}
              {/* Settings Menu */}
              <div className="card">
                <div className="card-body pb-0 pt-2">
                <ul className="nav nav-tabs nav-tabs-bottom">
                    <li className="nav-item me-3">
                      <Link href={route.profile} className="nav-link px-0 ">
                        <i className="ti ti-settings-cog" /> General Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.companySettings}
                        className="nav-link px-0 active"
                      >
                        <i className="ti ti-world-cog" /> Website Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.invoiceSettings}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-apps" /> App Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link href={route.emailSettings} className="nav-link px-0 ">
                        <i className="ti ti-device-laptop" /> System Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.paymentGateways}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-moneybag" /> Financial Settings
                      </Link>
                    </li>
                    <li className="nav-item ">
                      <Link href={route.storage} className="nav-link px-0 ">
                        <i className="ti ti-flag-cog" /> Other Settings
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Settings Menu */}
              <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">Website Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
                          <Link
                            href={route.companySettings}
                            className="fw-medium"
                          >
                            Company Settings
                          </Link>
                          <Link href={route.localization} className="fw-medium">
                            Localization
                          </Link>
                          <Link href={route.prefixes} className="fw-medium active">
                            Prefixes
                          </Link>
                          <Link href={route.preference} className="fw-medium">
                            Preference
                          </Link>
                          <Link
                            href={route.appearance}
                            className="fw-medium "
                          >
                            Appearance
                          </Link>
                          <Link href={route.language} className="fw-medium">
                            Language
                          </Link>
                        </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Prefixes */}
    <div className="card">
      <div className="card-body">
        <h4 className="fw-semibold mb-3">Prefixes</h4>
        <form>
          <div className="row">
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Products(SKU)</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="SKU - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Supplier</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="SUP - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Purchase</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="PU - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Purchase Return</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="PR - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Sales</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="SA - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Sales Return</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="SR -  "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Customer</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="CT - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Expense</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="EX - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Stock Transfer</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="ST -  "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Stock Adjustment</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="SA -  "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Sales Order</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="SO - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Invoice</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="INV -  "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Estimation</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="EST - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Transaction</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="TRN - "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Employee</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="EMP -  "
                />
              </div>
            </div>
            <div className="col-md-3 col-sm-6">
              <div className="mb-3">
                <label className="form-label">Purchase Return</label>
                <input
                  type="text"
                  className="form-control"
                  defaultValue="PR -  "
                />
              </div>
            </div>
          </div>
          <div>
            <Link href="#" className="btn btn-light me-2">
              Cancel
            </Link>
            <button type="button" className="btn btn-primary">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
    {/* /Prefixes */}
  </div>
</div>

            </div>
          </div>
        </div>
      </div>
      {/* /Page Wrapper */}
      <>
  {/* Add Translation */}
  <div className="modal custom-modal fade" id="add_translation" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">Add Translation</h5>
          <button
            className="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <div className="modal-body">
          <form >
            <div className="mb-3">
              <label className="form-label">
                Language <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-3">
              <label className="form-label">
                Code <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-3">
              <label className="form-label">Status</label>
              <div className="radio-wrap">
                <div className="d-flex flex-wrap">
                  <div className="radio-btn">
                    <input
                      type="radio"
                      className="status-radio"
                      id="add-active"
                      name="status"
                      defaultChecked
                    />
                    <label htmlFor="add-active">Active</label>
                  </div>
                  <div className="radio-btn">
                    <input
                      type="radio"
                      className="status-radio"
                      id="add-inactive"
                      name="status"
                    />
                    <label htmlFor="add-inactive">Inactive</label>
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-btn">
              <Link href="#" className="btn btn-light" data-bs-dismiss="modal">
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Save
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {/* /Add Translation */}
  {/* Edit Translation */}
  <div className="modal custom-modal fade" id="edit_translation" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">Edit Translation</h5>
          <button
            className="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <div className="modal-body">
          <form >
            <div className="mb-3">
              <label className="form-label">
                Language <span className="text-danger">*</span>
              </label>
              <input
                type="text"
                className="form-control"
                defaultValue="English"
              />
            </div>
            <div className="mb-3">
              <label className="form-label">
                Code <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" defaultValue="en" />
            </div>
            <div className="mb-3">
              <label className="form-label">Status</label>
              <div className="radio-wrap">
                <div className="d-flex flex-wrap">
                  <div className="radio-btn">
                    <input
                      type="radio"
                      className="status-radio"
                      id="edit-active"
                      name="status"
                      defaultChecked
                    />
                    <label htmlFor="edit-active">Active</label>
                  </div>
                  <div className="radio-btn">
                    <input
                      type="radio"
                      className="status-radio"
                      id="edit-inactive"
                      name="status"
                    />
                    <label htmlFor="edit-inactive">Inactive</label>
                  </div>
                </div>
              </div>
            </div>
            <div className="modal-btn">
              <Link href="#" className="btn btn-light" data-bs-dismiss="modal">
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Save
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {/* /Edit Translation */}
  {/* Import Sample */}
  <div className="modal custom-modal fade" id="import_sample" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">Import Sample</h5>
          <button
            className="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <div className="modal-body">
          <form >
            <div className="mb-3">
              <label className="form-label">
                File <span className="text-danger">*</span>
              </label>
              <Select
                      options={fileData}
                      className="select"
                      placeholder="Select File"
                    />
            </div>
            <div className="mb-3">
              <label className="form-label">
                Language <span className="text-danger">*</span>
              </label>
              <Select
                      options={languageOptions}
                      className="select"
                      placeholder="Select Language"
                    />
            </div>
            <div className="mb-3">
              <div className="drag-attach">
                <input type="file" />
                <div className="img-upload">
                  <i className="ti ti-file-broken" />
                  Upload File
                </div>
              </div>
            </div>
            <div className="mb-3">
              <label className="form-label">Uploaded Files</label>
              <div className="upload-file">
                <h6>Projectneonals teyys.xls</h6>
                <p>4.25 MB</p>
                <div className="progress">
                  <div
                    className="progress-bar bg-success"
                    role="progressbar"
                    style={{ width: "25%" }}
                    aria-valuenow={25}
                    aria-valuemin={0}
                    aria-valuemax={100}
                  />
                </div>
                <p className="black-text">45%</p>
              </div>
              <div className="upload-file upload-list">
                <div>
                  <h6>tes.txt</h6>
                  <p>4.25 MB</p>
                </div>
                <Link href="#" className="text-danger">
                  <i className="ti ti-trash-x" />
                </Link>
              </div>
            </div>
            <div className="modal-btn">
              <Link href="#" className="btn btn-light" data-bs-dismiss="modal">
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Save
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {/* /Import Sample */}
  {/* Delete Translation */}
  <div
    className="modal custom-modal fade"
    id="delete_translation"
    role="dialog"
  >
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header border-0 m-0 justify-content-end">
          <button
            className="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <div className="modal-body">
          <form >
            <div className="success-message text-center">
              <div className="success-popup-icon">
                <i className="ti ti-trash-x" />
              </div>
              <h3>Remove Translation?</h3>
              <p className="del-info">Are you sure you want to remove it.</p>
              <div className="col-lg-12 text-center modal-btn">
                <Link href="#" className="btn btn-light" data-bs-dismiss="modal">
                  Cancel
                </Link>
                <button type="button" data-bs-dismiss="modal" className="btn btn-danger">
                  Yes, Delete it
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {/* /Delete Translation */}
</>

    </div>
  );
};

export default PrefixesComponent;
