// angular/angular/src/app/feature-module/settings/general-settings/connected-apps/connected-apps.component.ts
import { Component } from '@angular/core';
import { DataService } from '../../../../../shared/data/data.service';
import { routes } from '../../../../../shared/routes/routes';

@Component({
    selector: 'app-connected-apps',
    templateUrl: './connected-apps.component.html',
    styleUrl: './connected-apps.component.scss',
    standalone: false
})
export class ConnectedAppsComponent {
  public routes = routes;
  constructor( private data: DataService){}

  

}

<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h4 class="page-title">Settings</h4>
            </div>
            <div class="col-4 text-end">
              <div class="head-icons">
                <a
                  [routerLink]="routes.connectedApps"
                  data-bs-toggle="tooltip"
                  data-bs-placement="top"
                  data-bs-original-title="Refresh"
                  matTooltip="Refresh"
                  ><i class="ti ti-refresh-dot"></i
                ></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <!-- Settings Menu -->
        <div class="card">
          <div class="card-body pb-0 pt-2">
            <div class="settings-menu">
              <ul class="nav nav-tabs nav-tabs-bottom">
                <li class="nav-item me-3">
                  <a
                    [routerLink]="routes.generalSettings"
                    class="nav-link px-0 active"
                  >
                    <i class="ti ti-settings-cog me-2"></i>General Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a
                    [routerLink]="routes.companySettings"
                    class="nav-link px-0"
                  >
                    <i class="ti ti-world-cog me-2"></i>Website Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a
                    [routerLink]="routes.invoiceSettings"
                    class="nav-link px-0"
                  >
                    <i class="ti ti-apps me-2"></i>App Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink]="routes.emailSettings" class="nav-link px-0">
                    <i class="ti ti-device-laptop me-2"></i>System Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a
                    [routerLink]="routes.paymentGatewaySettings"
                    class="nav-link px-0"
                  >
                    <i class="ti ti-moneybag me-2"></i>Financial Settings
                  </a>
                </li>
                <li class="nav-item">
                  <a
                    [routerLink]="routes.storageSettings"
                    class="nav-link px-0"
                  >
                    <i class="ti ti-flag-cog me-2"></i>Other Settings
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- /Settings Menu -->

        <div class="row">
          <div class="col-xl-3 col-lg-12 theiaStickySidebar">
            <div class="stickybar">
              <!-- Settings Sidebar -->
              <div class="card">
                <div class="card-body">
                  <div class="settings-sidebar">
                    <h4 class="fw-semibold mb-3">General Settings</h4>
                    <div class="list-group list-group-flush settings-sidebar">
                      <a [routerLink] = "routes.generalSettings" class="fw-medium">Profile</a>
                      <a [routerLink]="routes.securitySettings"class="fw-medium">Security</a>
                      <a [routerLink]="routes.settingsNotification" class="fw-medium">Notifications</a>
                      <a [routerLink]="routes.connectedApps" class="fw-medium active">Connected Apps</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Settings Sidebar -->
            </div>
          </div>

          <div class="col-xl-9 col-lg-12">
            <!-- Settings Info -->
            <div class="card">
              <div class="card-body pb-0">
                <h4 class="fw-semibold mb-3">Connected Apps</h4>
                <div class="row">

                  <!-- App -->
                  <div class="col-md-4 col-sm-6">
                    <div class="card border mb-3">
                      <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                          <img src="assets/img/icons/integration-01.svg" alt="Icon">
                          <div class="connect-btn">
                            <a href="javascript:void(0);" class="badge badge-soft-success">Connected</a>
                          </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                          <p class="mb-0">Google Calendar</p>
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" checked>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /App -->

                  <!-- App -->
                  <div class="col-md-4 col-sm-6">
                    <div class="card border mb-3">
                      <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                          <img src="assets/img/icons/integration-02.svg" alt="Icon">
                          <div class="connect-btn">
                            <a href="javascript:void(0);" class="badge border bg-white text-default">Connect</a>
                          </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                          <p class="mb-0">Figma</p>
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" checked>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /App -->

                  <!-- App -->
                  <div class="col-md-4 col-sm-6">
                    <div class="card border mb-3">
                      <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                          <img src="assets/img/icons/integration-03.svg" alt="Icon">
                          <div class="connect-btn">
                            <a href="javascript:void(0);" class="badge badge-soft-success">Connected</a>
                          </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                          <p class="mb-0">Dropbox</p>
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" checked>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /App -->

                  <!-- App -->
                  <div class="col-md-4 col-sm-6">
                    <div class="card border mb-3">
                      <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                          <img src="assets/img/icons/integration-04.svg" alt="Icon">
                          <div class="connect-btn">
                            <a href="javascript:void(0);" class="badge border bg-white text-default">Connect</a>
                          </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                          <p class="mb-0">Slack</p>
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" checked>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /App -->

                  <!-- App -->
                  <div class="col-md-4 col-sm-6">
                    <div class="card border mb-3">
                      <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                          <img src="assets/img/icons/integration-05.svg" alt="Icon">
                          <div class="connect-btn">
                            <a href="javascript:void(0);" class="badge badge-soft-success">Connected</a>
                          </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                          <p class="mb-0">Gmail</p>
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" checked>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /App -->

                  <!-- App -->
                  <div class="col-md-4 col-sm-6">
                    <div class="card border mb-3">
                      <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                          <img src="assets/img/icons/integration-06.svg" alt="Icon">
                          <div class="connect-btn">
                            <a href="javascript:void(0);" class="badge border bg-white text-default">Connect</a>
                          </div>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                          <p class="mb-0">Github</p>
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" checked>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /App -->

                </div>
              </div>
            </div>
            <!-- /Settings Info -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// nextjs/nextjs/template/src/components/settings/generalSettings/connectedApps.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import CollapseHeader from "../../../core/common/collapse-header";

const ConnectedAppsComponent = () => {
  const route = all_routes;
  return (
    <>
      {/* Page Wrapper */}
      <div className="page-wrapper">
        <div className="content">
          <div className="row">
            <div className="col-md-12">
              {/* Page Header */}
              <div className="page-header">
                <div className="row align-items-center">
                  <div className="col-8">
                    <h4 className="page-title">Settings</h4>
                  </div>
                  <div className="col-4 text-end">
                    <div className="head-icons">
                      <CollapseHeader />
                    </div>
                  </div>
                </div>
              </div>
              {/* /Page Header */}
              {/* Settings Menu */}
              <div className="card">
                <div className="card-body pb-0 pt-2">
                  <ul className="nav nav-tabs nav-tabs-bottom">
                    <li className="nav-item me-3">
                      <Link href={route.profile} className="nav-link px-0 active">
                        <i className="ti ti-settings-cog" /> General Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.companySettings}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-world-cog" /> Website Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.invoiceSettings}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-apps" /> App Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link href={route.emailSettings} className="nav-link px-0">
                        <i className="ti ti-device-laptop" /> System Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.paymentGateways}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-moneybag" /> Financial Settings
                      </Link>
                    </li>
                    <li className="nav-item ">
                      <Link href={route.storage} className="nav-link px-0">
                        <i className="ti ti-flag-cog" /> Other Settings
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
              {/* /Settings Menu */}
              <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">General Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
            <Link href={route.profile} className="fw-medium">
              Profile
            </Link>
            <Link href={route.security} className="fw-medium">
              Security
            </Link>
            <Link href={route.notification} className="fw-medium">
              Notifications
            </Link>
            <Link href={route.connectedApps} className="fw-medium active">
              Connected Apps
            </Link>
          </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Settings Info */}
    <div className="card">
      <div className="card-body pb-0">
        <h4 className="fw-semibold mb-3">Connected Apps</h4>
        <div className="row">
          {/* App */}
          <div className="col-md-4 col-sm-6">
            <div className="card border mb-3">
              <div className="card-body">
                <div className="d-flex align-items-center justify-content-between mb-3">
                  <img src="assets/img/icons/integration-01.svg" alt="Icon" />
                  <div className="connect-btn">
                    <Link
                      href="#"
                      className="badge badge-soft-success"
                    >
                      Connected
                    </Link>
                  </div>
                </div>
                <div className="d-flex align-items-center justify-content-between">
                  <p className="mb-0">Google Calendar</p>
                  <div className="form-check form-switch">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /App */}
          {/* App */}
          <div className="col-md-4 col-sm-6">
            <div className="card border mb-3">
              <div className="card-body">
                <div className="d-flex align-items-center justify-content-between mb-3">
                  <img src="assets/img/icons/integration-02.svg" alt="Icon" />
                  <div className="connect-btn">
                    <Link
                      href="#"
                      className="badge border bg-white text-default"
                    >
                      Connect
                    </Link>
                  </div>
                </div>
                <div className="d-flex align-items-center justify-content-between">
                  <p className="mb-0">Figma</p>
                  <div className="form-check form-switch">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /App */}
          {/* App */}
          <div className="col-md-4 col-sm-6">
            <div className="card border mb-3">
              <div className="card-body">
                <div className="d-flex align-items-center justify-content-between mb-3">
                  <img src="assets/img/icons/integration-03.svg" alt="Icon" />
                  <div className="connect-btn">
                    <Link
                      href="#"
                      className="badge badge-soft-success"
                    >
                      Connected
                    </Link>
                  </div>
                </div>
                <div className="d-flex align-items-center justify-content-between">
                  <p className="mb-0">Dropbox</p>
                  <div className="form-check form-switch">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /App */}
          {/* App */}
          <div className="col-md-4 col-sm-6">
            <div className="card border mb-3">
              <div className="card-body">
                <div className="d-flex align-items-center justify-content-between mb-3">
                  <img src="assets/img/icons/integration-04.svg" alt="Icon" />
                  <div className="connect-btn">
                    <Link
                      href="#"
                      className="badge border bg-white text-default"
                    >
                      Connect
                    </Link>
                  </div>
                </div>
                <div className="d-flex align-items-center justify-content-between">
                  <p className="mb-0">Slack</p>
                  <div className="form-check form-switch">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /App */}
          {/* App */}
          <div className="col-md-4 col-sm-6">
            <div className="card border mb-3">
              <div className="card-body">
                <div className="d-flex align-items-center justify-content-between mb-3">
                  <img src="assets/img/icons/integration-05.svg" alt="Icon" />
                  <div className="connect-btn">
                    <Link
                      href="#"
                      className="badge badge-soft-success"
                    >
                      Connected
                    </Link>
                  </div>
                </div>
                <div className="d-flex align-items-center justify-content-between">
                  <p className="mb-0">Gmail</p>
                  <div className="form-check form-switch">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /App */}
          {/* App */}
          <div className="col-md-4 col-sm-6">
            <div className="card border mb-3">
              <div className="card-body">
                <div className="d-flex align-items-center justify-content-between mb-3">
                  <img src="assets/img/icons/integration-06.svg" alt="Icon" />
                  <div className="connect-btn">
                    <Link
                      href="#"
                      className="badge border bg-white text-default"
                    >
                      Connect
                    </Link>
                  </div>
                </div>
                <div className="d-flex align-items-center justify-content-between">
                  <p className="mb-0">Github</p>
                  <div className="form-check form-switch">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /App */}
        </div>
      </div>
    </div>
    {/* /Settings Info */}
  </div>
</div>

            </div>
          </div>
        </div>
      </div>
      {/* /Page Wrapper */}
    </>
  );
};

export default ConnectedAppsComponent;
