// angular/angular/src/app/feature-module/ui-interface/advanced-ui/ui-rating/ui-rating.component.ts
import { Component, OnInit } from '@angular/core';
import { routes } from '../../../../../shared/routes/routes';
import { Star } from '../../../../../shared/model/pages.model';
interface StarModel {
  show: boolean;
  half?: boolean;
  hover?: boolean;
}
@Component({
    selector: 'app-ui-rating',
    templateUrl: './ui-rating.component.html',
    styleUrl: './ui-rating.component.scss',
    standalone: false
})
export class UiRatingComponent implements OnInit {
  public routes = routes;

  basicStar = [
    { show: false },
    { show: false },
    { show: false },
    { show: false },
    { show: false },
  ];
  basicStar1 = [
    { show: false },
    { show: false },
    { show: false },
    { show: false },
    { show: false },
  ];
  savedStar = [
    { show: true },
    { show: true },
    { show: true },
    { show: false },
    { show: false },
  ];
  maxStar = [
    { show: false },
    { show: false },
    { show: false },
    { show: false },
    { show: false },
  ];
  readOnlyStar = [
    { show: true },
    { show: true },
    { show: true },
    { show: true },
    { show: true },
    { show: true },
    { show: false },
    { show: false },
    { show: false },
    { show: false },
  ];
  halfRatingStar = [
    { show: true, half: false },
    { show: true, half: false },
    { show: false, half: true },
    { show: false, half: false },
    { show: false, half: false },
  ];
  heartIcon = [
    { show: false },
    { show: false },
    { show: false },
    { show: false },
    { show: false },
  ];

  clickBasicStar(item: Star, i: number, array: Star[]): void {
    if (item.show == false) {
      array.map((res: Star, index: number) => {
        if (index <= i) {
          res.show = true;
        }
      });
    } else {
      array.map((res: Star, index: number) => {
        if (index >= i && index != 0) {
          res.show = false;
        }
      });
    }

    if (array === this.halfRatingStar) {
      array.map((res: Star) => {
        res.half = false;
      });
    }
  }
  clickBasicStar1(item: Star, i: number, array: StarModel[]): void {
    if (item.show == false) {
      array.map((res: Star, index: number) => {
        if (index <= i) {
          res.show = true;
        }
      });
    } else {
      array.map((res: Star, index: number) => {
        if (index >= i && index != 0) {
          res.show = false;
        }
      });
    }
    this.increaseRating();
    if (array === this.halfRatingStar) {
      array.map((res: Star) => {
        res.half = false;
      });
    }
  }

  liveRating = 1;
  increaseRating() {
    this.liveRating++;
  }
  resetStars(): void {
    this.heartIcon.forEach((item) => {
      item.show = false;
    });
  }

  hoverStar1(isHovered: boolean, index: number, halfRatingStar: StarModel[]): void {
    const item = halfRatingStar[index];
    if (item && item.half) {
      item.hover = isHovered;
    }
  }
  hoverStar(index: number, array: Star[]): void {
    for (let i = 0; i <= index; i++) {
      if (array[i]) {
        array[i].show = true;
      }
    }

    for (let i = index + 1; i < array.length; i++) {
      if (array[i]) {
        array[i].show = false;
      }
    }
  }
  // bread crumb items
  breadCrumbItems!: object[];
  readonly = false;
  defaultSelect = 3;
  currentRate = 2;
  customColor = 4;
  hoverSelect = 2;
  hovered = 0;
  clearRate = 2;

  
  ngOnInit(): void {
    this.breadCrumbItems = [
      { label: 'Advance UI' },
      { label: 'Ratings', active: true },
    ];
  }
  handleKeydown(event: KeyboardEvent): void {
    if (event.key === 'Enter' || event.key === ' ') {
      this.increaseRating();
      event.preventDefault(); // Prevent default behavior to avoid scrolling when space is pressed
    }
  }
}

<div class="cardhead">
    <!-- Page Header -->
    <div class="page-header">
      <div class="row">
        <div class="col-sm-12">
          <h3 class="page-title">Rating</h3>
        </div>
      </div>
    </div>
    <!-- /Page Header -->
    <div class="row">
      <div class="col-xxl-4 col-xl-6">
        <div class="card custom-card">
          <div class="card-header">
          <div class="card-title">
              Basic Rater
          </div> 
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <p class="fs-14 mb-0 fw-semibold">Show Some <span class="text-danger">&#10084;</span> with rating :</p>
              <div id="rater-basic">
                <ngb-rating [(rate)]="defaultSelect" [readonly]="readonly" class="stars" [max]=5></ngb-rating>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xxl-4 col-xl-6">
        <div class="card custom-card">
          <div class="card-header">
            <div class="card-title">
              5 star rater with steps
            </div> 
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <p class="fs-14 mb-0 fw-semibold">Dont forget to rate the product :</p>
              <div id="rater-steps">
                 
                @for (item of halfRatingStar; track item; let i = $index) {
                  @if (item.show === false && item.half === false) {
                    <img
                      (click)="clickBasicStar(item, i, halfRatingStar)"
                      (keydown.enter)="clickBasicStar(item, i, halfRatingStar)"
                      (keyup.enter)="clickBasicStar(item, i, halfRatingStar)"
                      (keydown.space)="clickBasicStar(item, i, halfRatingStar)"
                      (keyup.space)="clickBasicStar(item, i, halfRatingStar)"
                      class="me-1"
                      alt="Inactive star rating"
                      tabindex="0"
                      src="assets/img/ratings/star-off.png" />
                  }
                  @if (item.show === true) {
                    <img
                      (click)="clickBasicStar(item, i, halfRatingStar)"
                      (keydown.enter)="clickBasicStar(item, i, halfRatingStar)"
                      (keyup.enter)="clickBasicStar(item, i, halfRatingStar)"
                      (keydown.space)="clickBasicStar(item, i, halfRatingStar)"
                      (keyup.space)="clickBasicStar(item, i, halfRatingStar)"
                      class="me-1"
                      alt="Active star rating"
                      tabindex="0"
                      src="assets/img/ratings/star-on.png" />
                  }
                  @if (item.half === true) {
                    <img
                      src="assets/img/ratings/star-half.png"
                      alt="Half star rating"
                      tabindex="0"
                      (keydown.enter)="clickBasicStar(item, i, halfRatingStar)"
                      (keyup.enter)="clickBasicStar(item, i, halfRatingStar)"
                      (keydown.space)="clickBasicStar(item, i, halfRatingStar)"
                      (keyup.space)="clickBasicStar(item, i, halfRatingStar)" />
                  }
                }
                
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xxl-4 col-xl-12">
        <div class="card custom-card">
          <div class="card-header">
            <div class="card-title">
              Custom messages
            </div> 
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <p class="fs-14 mb-0 fw-semibold">Your rating is much appreciated:</p>
              <div id="custom-messages">
                 
                @for (item of maxStar; track item; let i = $index) {
                  <img 
                    (click)="clickBasicStar(item, i, maxStar)"
                    (keydown.enter)="clickBasicStar(item, i, maxStar)"
                    (keydown.space)="clickBasicStar(item, i, maxStar)"
                    (mouseover)="hoverStar(i, maxStar)" 
                    (focus)="hoverStar(i, maxStar)"
                    (mouseout)="hoverStar(-1, maxStar)"
                    (blur)="hoverStar(-1, maxStar)"
                    class="me-1"
                    [attr.alt]="'Rating star ' + (i + 1)"
                    tabindex="0"
                    [src]="item.show ? 'assets/img/ratings/star-on.png' : 'assets/img/ratings/star-off.png'" />
                }
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xxl-6 col-xl-6">
        <div class="card custom-card">
          <div class="card-header">
            <div class="card-title">
              Unlimited number of stars readOnly
            </div> 
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <p class="fs-14 mb-0 fw-semibold">Thanks for rating :</p>
              <div id="stars-unlimited">
                @for (item of readOnlyStar; track item; let i = $index) {
                  @if (item.show === false) {
                    <img src="assets/img/ratings/star-off.png" class="me-1" alt="rating"/>
                  }
                  @if (item.show === true) {
                    <img src="assets/img/ratings/star-on.png" class="me-1" alt="rating"/>
                  }
                }
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xxl-6 col-xl-6">
        <div class="card custom-card">
          <div class="card-header">
            <div class="card-title">
              5 Star rater with custom isBusyText and simulated backend
            </div> 
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <p class="fs-14 mb-0 fw-semibold">Thanks for rating :</p>
              <div id="stars-busytext">
                @for (item of savedStar; track item; let i = $index) {
                  @if (item.show === false) {
                    <img 
                      (click)="clickBasicStar(item, i, savedStar)"
                      (keydown.enter)="clickBasicStar(item, i, savedStar)"
                      (keyup.enter)="clickBasicStar(item, i, savedStar)"
                      (keydown.space)="clickBasicStar(item, i, savedStar)"
                      (keyup.space)="clickBasicStar(item, i, savedStar)"
                      class="me-1"
                      alt="Rating star off"
                      src="assets/img/ratings/star-off.png"
                      tabindex="0"
                    />
                  }
                  @if (item.show === true) {
                    <img 
                      (click)="clickBasicStar(item, i, savedStar)"
                      (keydown.enter)="clickBasicStar(item, i, savedStar)"
                      (keyup.enter)="clickBasicStar(item, i, savedStar)"
                      (keydown.space)="clickBasicStar(item, i, savedStar)"
                      (keyup.space)="clickBasicStar(item, i, savedStar)"
                      class="me-1"
                      alt="Rating star on"
                      src="assets/img/ratings/star-on.png"
                      tabindex="0"
                    />
                  }
                }
              </div>
              
            </div>
          </div>
        </div>
      </div>
      <div class="col-xxl-4 col-xl-6">
        <div class="card custom-card">
          <div class="card-header">
            <div class="card-title">
              On hover event
            </div> 
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <p class="fs-14 mb-0 fw-semibold">Please give your valuable rating :</p>
              <div class="d-flex flex-wrap align-items-center">
                <div id="stars-hover">
                  <ngb-rating [(rate)]="hoverSelect" (hover)="hovered=$event" (leave)="hovered=0" [readonly]="readonly" class="stars" [max]=5></ngb-rating>
                    
                </div>
                <span
                class="live-rating badge bg-success-transparent ms-3"
                (click)="increaseRating()"
                (keydown)="handleKeydown($event)"
                tabindex="0"
              >
                {{hovered}}
              </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xxl-4 col-xl-6">
        <div class="card custom-card">
          <div class="card-header">
            <div class="card-title">
              Clear/reset rater
            </div> 
          </div>
          <div class="card-body">
            <div class="d-flex flex-wrap align-items-center justify-content-between">
              <p class="fs-14 mb-0 fw-semibold">Thank You so much for your support :</p>
              <div class="d-flex flex-wrap align-items-center">
                <div id="rater-reset">
                  <ngb-rating [(rate)]="clearRate" [readonly]="readonly" class="stars align-middle star-rating" [max]=5></ngb-rating>
                </div>
                <button class="btn btn-icon btn-sm btn-danger-light ms-3" id="rater-reset-button" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="Reset" (click)="clearRate = 0">
                  <i  class="feather icon-rotate-cw feather-16"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  
  
  </div>

// vue/vue/src/views/pages/uiinterface/advancedUI/ui-rating.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <!-- Page Wrapper -->
  <div class="page-wrapper cardhead">
    <div class="content">
      <!-- Page Header -->
      <div class="page-header">
        <div class="row">
          <div class="col-sm-12">
            <h3 class="page-title">Rating</h3>
          </div>
        </div>
      </div>
      <!-- /Page Header -->

      <div class="row">
        <div class="col-xxl-4 col-xl-6">
          <div class="card custom-card">
            <div class="card-header">
              <div class="card-title">Basic Rater</div>
            </div>
            <div class="card-body">
              <div class="d-flex flex-wrap align-items-center justify-content-between">
                <p class="fs-14 mb-0 fw-semibold">
                  Show Some <span class="text-danger">&#10084;</span> with rating :
                </p>
                <star-rating v-bind:star-size="20" v-bind:show-rating="false" />
              </div>
            </div>
          </div>
        </div>
        <div class="col-xxl-4 col-xl-6">
          <div class="card custom-card">
            <div class="card-header">
              <div class="card-title">5 star rater with steps</div>
            </div>
            <div class="card-body">
              <div class="d-flex flex-wrap align-items-center justify-content-between">
                <p class="fs-14 mb-0 fw-semibold">Dont forget to rate the product :</p>
                <star-rating
                  v-bind:star-size="20"
                  v-bind:rating="3"
                  v-bind:show-rating="false"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="col-xxl-4 col-xl-12">
          <div class="card custom-card">
            <div class="card-header">
              <div class="card-title">Custom messages</div>
            </div>
            <div class="card-body">
              <div class="d-flex flex-wrap align-items-center justify-content-between">
                <p class="fs-14 mb-0 fw-semibold">
                  Your rating is much appreciated&#128079; :
                </p>
                <star-rating
                  v-bind:star-size="20"
                  v-bind:max-rating="10"
                  v-bind:show-rating="false"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="col-xxl-6 col-xl-6">
          <div class="card custom-card">
            <div class="card-header">
              <div class="card-title">Unlimited number of stars readOnly</div>
            </div>
            <div class="card-body">
              <div class="d-flex flex-wrap align-items-center justify-content-between">
                <p class="fs-14 mb-0 fw-semibold">Thanks for rating :</p>
                <star-rating
                  v-bind:star-size="20"
                  v-bind:read-only="true"
                  v-bind:rating="3"
                  v-bind:show-rating="false"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="col-xxl-6 col-xl-6">
          <div class="card custom-card">
            <div class="card-header">
              <div class="card-title">
                5 Star rater with custom isBusyText and simulated backend
              </div>
            </div>
            <div class="card-body">
              <div class="d-flex flex-wrap align-items-center justify-content-between">
                <p class="fs-14 mb-0 fw-semibold">Thanks for rating :</p>
                <star-rating
                  v-bind:star-size="20"
                  v-bind:increment="0.5"
                  v-bind:rating="3.5"
                  v-bind:show-rating="false"
                />
              </div>
            </div>
          </div>
        </div>
        <div class="col-xxl-4 col-xl-6">
          <div class="card custom-card">
            <div class="card-header">
              <div class="card-title">On hover event</div>
            </div>
            <div class="card-body">
              <div class="d-flex flex-wrap align-items-center justify-content-between">
                <p class="fs-14 mb-0 fw-semibold">Please give your valuable rating :</p>
                <div class="d-flex flex-wrap align-items-center">
                  <star-rating v-bind:star-size="20" v-bind:show-rating="false" />
                  <span class="live-rating badge bg-success-transparent ms-3"> 1 </span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xxl-4 col-xl-6">
          <div class="card custom-card">
            <div class="card-header">
              <div class="card-title">Clear/reset rater</div>
            </div>
            <div class="card-body">
              <div class="d-flex flex-wrap align-items-center justify-content-between">
                <p class="fs-14 mb-0 fw-semibold">Thank You so much for your support :</p>
                <div class="d-flex flex-wrap align-items-center">
                  <star-rating v-bind:star-size="20" v-bind:show-rating="false" />
                  <button
                    class="btn btn-icon btn-sm btn-danger-light ms-3"
                    id="rater-reset-button"
                    data-bs-toggle="tooltip"
                    data-bs-placement="top"
                    data-bs-title="Reset"
                  >
                    <vue-feather type="rotate-cw" class="feather-16"></vue-feather>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /Page Wrapper -->
</template>
<script>
export default {
  data() {
    return {};
  },
};
</script>
