// nextjs/nextjs/template/src/components/settings/generalSettings/profile.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import CollapseHeader from "../../../core/common/collapse-header";
const route = all_routes;
const ProfileComponent = () => {
  return (
    <div className="page-wrapper">
      <div className="content">
        <div className="row">
          <div className="col-md-12">
            {/* Page Header */}
            <div className="page-header">
              <div className="row align-items-center">
                <div className="col-sm-4">
                  <h4 className="page-title">Settings</h4>
                </div>
                <div className="col-sm-8 text-sm-end">
                  <div className="head-icons">
                    <CollapseHeader />
                  </div>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Settings Menu */}
            <div className="card">
              <div className="card-body pb-0 pt-2">
              <ul className="nav nav-tabs nav-tabs-bottom">
                      <li className="nav-item me-3">
                        <Link href={route.profile} className="nav-link px-0 active">
                          <i className="ti ti-settings-cog" /> General Settings
                        </Link>
                      </li>
                      <li  className="nav-item me-3">
                        <Link href={route.companySettings} className='nav-link px-0'>
                          <i className="ti ti-world-cog" /> Website Settings
                        </Link>
                      </li>
                      <li  className="nav-item me-3">
                        <Link href={route.invoiceSettings} className='nav-link px-0'>
                          <i className="ti ti-apps" /> App Settings
                        </Link>
                      </li>
                      <li  className="nav-item me-3">
                        <Link href={route.emailSettings} className='nav-link px-0'>
                          <i className="ti ti-device-laptop" /> System Settings
                        </Link>
                      </li>
                      <li  className="nav-item me-3">
                        <Link href={route.paymentGateways} className='nav-link px-0'>
                          <i className="ti ti-moneybag" /> Financial Settings
                        </Link>
                      </li>
                      <li  className="nav-item ">
                        <Link href={route.storage} className='nav-link px-0'>
                          <i className="ti ti-flag-cog" /> Other Settings
                        </Link>
                      </li>
                    </ul>
              </div>
            </div>
            {/* /Settings Menu */}
            <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">General Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
            <Link href={route.profile} className="fw-medium active">
              Profile
            </Link>
            <Link href={route.security} className="fw-medium">
              Security
            </Link>
            <Link href={route.notification} className="fw-medium">
              Notifications
            </Link>
            <Link href={route.connectedApps} className="fw-medium">
              Connected Apps
            </Link>
          </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Settings Info */}
    <div className="card">
      <div className="card-body">
        <h4 className="fw-semibold mb-3">Profile Settings</h4>
        <form>
          <div className="border-bottom mb-3 pb-3">
            <h5 className="fw-semibold mb-1">Employee Information</h5>
            <p>Provide the information below</p>
          </div>
          <div className="mb-3">
            <div className="profile-upload">
              <div className="profile-upload-img">
                <span>
                  <i className="ti ti-photo" />
                </span>
                <img
                  id="ImgPreview"
                  src="assets/img/profiles/avatar-02.jpg"
                  alt="img"
                  className="preview1"
                />
                <button
                  type="button"
                  id="removeImage1"
                  className="profile-remove"
                >
                  <i className="feather-x" />
                </button>
              </div>
              <div className="profile-upload-content">
                <label className="profile-upload-btn">
                  <i className="ti ti-file-broken" /> Upload File
                  <input type="file" id="imag" className="input-img" />
                </label>
                <p>JPG, GIF or PNG. Max size of 800K</p>
              </div>
            </div>
          </div>
          <div className="border-bottom mb-3">
            <div className="row">
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">
                    First Name <span className="text-danger">*</span>
                  </label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">
                    Last Name <span className="text-danger">*</span>
                  </label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">
                    User Name <span className="text-danger">*</span>
                  </label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">
                    Phone Number <span className="text-danger">*</span>
                  </label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">
                    Email <span className="text-danger">*</span>
                  </label>
                  <input type="text" className="form-control" />
                </div>
              </div>
            </div>
          </div>
          <div className="border-bottom mb-3 pb-3">
            <h5 className="fw-semibold mb-1">Address</h5>
            <p>Please enter the address details</p>
          </div>
          <div className="row">
            <div className="col-md-12">
              <div className="mb-3">
                <label className="form-label">
                  Address <span className="text-danger">*</span>
                </label>
                <input type="text" className="form-control" />
              </div>
            </div>
            <div className="col-lg-3 col-md-6">
              <div className="mb-3">
                <label className="form-label">
                  Country <span className="text-danger">*</span>
                </label>
                <input type="text" className="form-control" />
              </div>
            </div>
            <div className="col-lg-3 col-md-6">
              <div className="mb-3">
                <label className="form-label">
                  State / Province <span className="text-danger">*</span>
                </label>
                <input type="text" className="form-control" />
              </div>
            </div>
            <div className="col-lg-3 col-md-6">
              <div className="mb-3">
                <label className="form-label">
                  City <span className="text-danger">*</span>
                </label>
                <input type="text" className="form-control" />
              </div>
            </div>
            <div className="col-lg-3 col-md-6">
              <div className="mb-3">
                <label className="form-label">
                  Postal Code <span className="text-danger">*</span>
                </label>
                <input type="text" className="form-control" />
              </div>
            </div>
          </div>
          <div>
            <Link href="#" className="btn btn-light me-2">
              Cancel
            </Link>
            <button type="button" className="btn btn-primary">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
    {/* /Settings Info */}
  </div>
</div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default ProfileComponent;

// angular/angular/src/app/feature-module/settings/general-settings/profile/profile.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { DataService } from '../../../../../shared/data/data.service';
import { routes } from '../../../../../shared/routes/routes';

@Component({
    selector: 'app-profile',
    templateUrl: './profile.component.html',
    styleUrl: './profile.component.scss',
    standalone: false
})
export class ProfileComponent {
  public routes = routes;
  constructor(private data: DataService, private router: Router) {}


  
  navigation() {
    this.router.navigate([routes.generalSettings])
  }
}

<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">

        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-sm-4">
              <h4 class="page-title">Settings</h4>
            </div>
            <div class="col-sm-8 text-sm-end">
              <div class="head-icons">
                <a [routerLink] = "routes.generalSettings" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-original-title="Refresh" matTooltip="Refresh"><i class="ti ti-refresh-dot"></i></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <!-- Settings Menu -->
        <div class="card">
          <div class="card-body pb-0 pt-2">
          
              <ul class="nav nav-tabs nav-tabs-bottom">
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.generalSettings" class="nav-link px-0 active">
                    <i class="ti ti-settings-cog"></i> General Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.companySettings" class="nav-link px-0">
                    <i class="ti ti-world-cog"></i> Website Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.invoiceSettings" class="nav-link px-0">
                    <i class="ti ti-apps"></i> App Settings
                  </a>
                </li>
                <li class="nav-item me-3"> 
                  <a [routerLink] = "routes.emailSettings" class="nav-link px-0">
                    <i class="ti ti-device-laptop"></i> System Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.paymentGatewaySettings" class="nav-link px-0">
                    <i class="ti ti-moneybag"></i> Financial Settings
                  </a>
                </li>
                <li class="nav-item">
                  <a [routerLink] = "routes.storageSettings" class="nav-link px-0">
                    <i class="ti ti-flag-cog"></i> Other Settings
                  </a>
                </li>
              </ul>
           
          </div>
        </div>
        <!-- /Settings Menu -->

        <div class="row">
          <div class="col-xl-3 col-lg-12 theiaStickySidebar">
            <div class="stickybar">
              <!-- Settings Sidebar -->
              <div class="card">
                <div class="card-body">
                  <div class="settings-sidebar">
                    <h4 class="fw-semibold mb-3">General Settings</h4>
                    <div class="list-group list-group-flush settings-sidebar">
                      <a [routerLink] = "routes.generalSettings" class="fw-medium active">Profile</a>
                      <a [routerLink] = "routes.securitySettings" class="fw-medium">Security</a>
                      <a [routerLink] = "routes.settingsNotification" class="fw-medium">Notifications</a>
                      <a [routerLink] = "routes.connectedApps" class="fw-medium">Connected Apps</a>
                    </div>
                    
                  </div>
                </div>
              </div>
              <!-- /Settings Sidebar -->
            </div>
          </div>

          <div class="col-xl-9 col-lg-12">

            <!-- Settings Info -->
            <div class="card">
              <div class="card-body">
                <h4 class="fw-semibold mb-3">Profile Settings</h4>
                <form>
                  <div class="border-bottom mb-3 pb-3">
                    <h5 class="fw-semibold mb-1">Employee Information</h5>
                    <p>Provide the information below</p>
                  </div>
                  <div class="mb-3">
                    <div class="profile-upload">
                      <div class="profile-upload-img">
                        <span><i class="ti ti-photo"></i></span>
                        <img id="ImgPreview" src="assets/img/profiles/avatar-02.jpg" alt="img" class="preview1">
                        <button type="button" id="removeImage1" class="profile-remove">
                          <i class="feather-x"></i>
                        </button>
                      </div>
                      <div class="profile-upload-content">
                        <label class="profile-upload-btn">
                          <i class="ti ti-file-broken"></i> Upload File 
                          <input type="file" id="imag" class="input-img">
                        </label>
                        <p>JPG, GIF or PNG. Max size of 800K</p>
                      </div>
                    </div>
                  </div>
                  <div class="border-bottom mb-3">
                    <div class="row">
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label" for=firstname>
                            First Name  <span class="text-danger">*</span>
                          </label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label" for="last">
                            Last Name  <span class="text-danger">*</span>
                          </label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label" for="user">
                            User Name  <span class="text-danger">*</span>
                          </label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label" for="phone">
                            Phone Number  <span class="text-danger">*</span>
                          </label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <label class="form-label" for="email">
                            Email  <span class="text-danger">*</span>
                          </label>
                          <input type="text" class="form-control">
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="border-bottom mb-3 pb-3">
                    <h5 class="fw-semibold mb-1">Address</h5>
                    <p>Please enter the address details</p>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="mb-3">
                        <label class="form-label" for="address">
                          Address  <span class="text-danger">*</span>
                        </label>
                        <input type="text" class="form-control">
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label" for="country">
                          Country <span class="text-danger">*</span>
                        </label>
                        <input type="text" class="form-control">
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label" for="state">
                          State / Province <span class="text-danger">*</span>
                        </label>
                        <input type="text" class="form-control">
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label" for="city">
                          City <span class="text-danger">*</span>
                        </label>
                        <mat-select class="select custom-mat-select" placeholder="Choose">
													<mat-option value="1">Choose</mat-option>
													<mat-option value="1">Los Angeles</mat-option>
													<mat-option value="1">San Diego</mat-option>
													<mat-option value="1">Fresno</mat-option>
													<mat-option value="1">San Francisco</mat-option>
												</mat-select>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label" for="postal">
                          Postal Code <span class="text-danger">*</span>
                        </label>
                        <input type="text" class="form-control">
                      </div>
                    </div>
                  </div>
                  <div>
                    <a href="javascript:void(0);" class="btn btn-light me-2">Cancel</a>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                  </div>
                </form>
               
              </div>
            </div>
            <!-- /Settings Info -->

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
