// nextjs/nextjs/template/src/components/application/call/callHistory.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import  Table  from "@/core/common/dataTable/index";
import Link from "next/link";
import { callhistorydata } from "@/data/json/callHistoryData";

const CallHistoryComponent = () => {
  const route = all_routes;
  const data = callhistorydata;
  const columns = [
    {
      title: "UserName",
      dataIndex: "username",
      render: (text: any, record: any) => (
        <span className="userimgname">
          <Link href="#" className="product-img">
            <img alt="" src={record.image_url} />
          </Link>
          <Link href="#">{text}</Link>
        </span>
      ),
      sorter: (a: any, b: any) => a.username.length - b.username.length,
    },
    {
      title: "Phone Number",
      dataIndex: "phone_number",
      sorter: (a: any, b: any) => a.phone_number.length - b.phone_number.length,
    },

    {
      title: "Call Type",
      dataIndex: "call_type",
      sorter: (a: any, b: any) => a.call_type.length - b.call_type.length,
    },

    {
      title: "Phone",
      dataIndex: "phone",
      sorter: (a: any, b: any) => a.phone.length - b.phone.length,
    },

    {
      title: "Duration",
      dataIndex: "duration",
      sorter: (a: any, b: any) => a.duration.length - b.duration.length,
    },
    {
      title: "Date & Time",
      dataIndex: "date_time",
      sorter: (a: any, b: any) => a.duration.length - b.duration.length,
    },
    {
      title: "Actions",
      dataIndex: "actions",
      render: () => (
        <div className="dropdown table-action">
          <Link
            href="#"
            className="action-icon"
            data-bs-toggle="dropdown"
            aria-expanded="true"
          >
            <i className="fa fa-ellipsis-v"></i>
          </Link>
          <div
            className="dropdown-menu dropdown-menu-right"
            data-bs-toggle="modal"
            data-bs-target="#user-profile-new"
            style={{
              position: "absolute",
              inset: "0px auto auto 0px",
              margin: "0px",
              transform: "translate3d(-99.3333px, 35.3333px, 0px)",
            }}
            data-popper-placement="bottom-start"
          >
            <Link className="dropdown-item edit-popup" href="#">
              <i className="ti ti-edit text-blue"></i> Edit
            </Link>
            <Link
              className="dropdown-item"
              href="#"
              data-bs-toggle="modal"
              data-bs-target="#delete_campaign"
            >
              <i className="ti ti-trash text-danger"></i> Delete
            </Link>
          </div>
        </div>
      ),
    },
  ];

  return (
    <div className="page-wrapper">
      <div className="content">
        <div className="page-header">
          <div className="page-header menu">
            <div className="page-title">
              <h4>Call History</h4>
              <h6>Manage your products</h6>
            </div>
          </div>
        </div>
        {/* /product list */}
        <div className="card table-list-card">
          <div className="card-body">
            {/* /Filter */}
            <div className="table-responsive product-list">
              <Table columns={columns} dataSource={data} />
            </div>
          </div>
        </div>
        {/* /product list */}
      </div>
      {/* details popup */}
      <div className="modal fade" id="user-profile-new">
        <div className="modal-dialog history-modal-profile">
          <div className="modal-content">
            <div className="page-wrapper details-blk">
              <div className="content">
                <div className="text-center right-sidebar-profile mb-3">
                  <figure className="avatar">
                    <img
                      src="assets/img/users/user-23.jpg"
                      alt="img"
                    />
                  </figure>
                  <div className="chat-options chat-option-profile">
                    <ul className="list-inline">
                      <li className="list-inline-item">
                        <Link
                          href={route.audioCall}
                          className="btn btn-outline-light "
                          data-bs-toggle="tooltip"
                          data-bs-placement="bottom"
                          title=""
                          data-bs-original-title="Voice Call"
                        >
                          <i className="bx bx-phone" />
                        </Link>
                      </li>
                      <li className="list-inline-item">
                        <Link
                          href={route.chat}
                          className="btn btn-outline-light"
                          data-bs-toggle="tooltip"
                          data-bs-placement="bottom"
                          title=""
                          data-bs-original-title="Chat"
                        >
                          <i className="bx bx-message-square-dots" />
                        </Link>
                      </li>
                      <li className="list-inline-item ">
                        <Link
                          href={route.videoCall}
                          className="btn btn-outline-light profile-open"
                          data-bs-toggle="tooltip"
                          data-bs-placement="bottom"
                          title=""
                          data-bs-original-title="Video Call"
                        >
                          <i className="bx bx-video" />
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="modal-profile-detail">
                  <div className="row">
                    <div className="col-lg-6">
                      <div className="modal-userlist">
                        <ul>
                          <li>
                            Name<span>Thomas</span>
                          </li>
                          <li>
                            Phone<span>+1 25182 94528</span>
                          </li>
                          <li>
                            Email<span>thomas@example.com</span>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div className="col-lg-6">
                      <div className="modal-userlist d-flex justify-content-center">
                        <ul>
                          <li>
                            Total Calls<span>20</span>
                          </li>
                          <li>
                            Average Call Timing<span>0.30</span>
                          </li>
                          <li>
                            Average Waiting Time<span>00.5</span>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* /details popup */}
      <div
        className="modal custom-modal fade"
        id="delete_campaign"
        role="dialog"
      >
        <div className="modal-dialog modal-dialog-centered">
          <div className="modal-content">
            <div className="modal-header border-0 m-0 justify-content-end">
              <button
                className="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              >
                <i className="ti ti-x" />
              </button>
            </div>
            <div className="modal-body">
              <div className="success-message text-center">
                <div className="success-popup-icon">
                  <i className="ti ti-trash-x" />
                </div>
                <h3>Are you sure?</h3>
                <p className="del-info">You won't be able to revert this!</p>
                <div className="col-lg-12 text-center modal-btn">
                  <Link
                    href="#"
                    className="btn btn-light"
                    data-bs-dismiss="modal"
                  >
                    Cancel
                  </Link>
                  <Link
                    href="#"
                    className="btn btn-danger"
                    data-bs-dismiss="modal"
                  >
                    Yes, Delete it
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CallHistoryComponent;

// angular/angular/src/app/feature-module/main-menu/application/call/call-history/call-history.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import Swal from 'sweetalert2';
import { routes } from '../../../../../../shared/routes/routes';
import { apiResultFormat, callHistory, pageSelection } from '../../../../../../shared/model/pages.model';
import { DataService } from '../../../../../../shared/data/data.service';
import { PaginationService, tablePageSize } from '../../../../../../shared/shared.index';
import { SidebarService } from '../../../../../../shared/sidebar/sidebar.service';
interface data {
  value: string;
}
@Component({
    selector: 'app-call-history',
    templateUrl: './call-history.component.html',
    styleUrl: './call-history.component.scss',
    standalone: false
})
export class CallHistoryComponent {
  initChecked = false;
  public routes = routes;
  public selectedValue1 = '';
  public selectedValue2 = '';
  public selectedValue3 = '';

  selectedList1: data[] = [
    { value: 'Sort by Date' },
    { value: 'Newest' },
    { value: 'Oldest' },
  ];
  selectedList2: data[] = [
    { value: 'Choose Name' },
    { value: 'Thomas' },
    { value: 'Rose' },
  ];
  selectedList3: data[] = [
    { value: 'Choose Calls' },
    { value: 'All Calls' },
    { value: 'Missed Calls' },
    { value: 'Outgoing Calls' },
    { value: 'Incoming Calls' },
  ];

  // pagination variables
  public tableData: callHistory[] = [];
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<callHistory>;
  public searchDataValue = '';
  //** / pagination variables

  constructor(
    private data: DataService,
    private pagination: PaginationService,
    private router: Router,
    private sidebar: SidebarService
  ) {
    this.data.getCallHistory().subscribe((apiRes: apiResultFormat) => {
      this.totalData = apiRes.totalData;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.callHistory) {
          this.getTableData({ skip: res.skip, limit: this.totalData });
          this.pageSize = res.pageSize;
        }
      });
    });
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getCallHistory().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: callHistory, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.sNo = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
        }
      });
      this.dataSource = new MatTableDataSource<callHistory>(this.tableData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }

  public searchData(value: string): void {
    this.dataSource.filter = value.trim().toLowerCase();
    this.tableData = this.dataSource.filteredData;
  }
  confirmColor() {
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: ' btn btn-success',
        cancelButton: 'me-2 btn btn-danger',
      },
      buttonsStyling: false,
    });

    swalWithBootstrapButtons
      .fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        confirmButtonText: 'Yes, delete it!',
        showCancelButton: true,
        cancelButtonText: 'Cancel',
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          swalWithBootstrapButtons.fire(
            'Deleted!',
            'Your file has been deleted.',
            'success'
          );
        } else if (result.dismiss === Swal.DismissReason.cancel) {
          swalWithBootstrapButtons.fire(
            'Cancelled',
            'Your imaginary file is safe :)',
            'error'
          );
        }
      });
  }
  public filter = false;
  openFilter() {
    this.filter = !this.filter;
  }


  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
}

<div class="page-wrapper">
  <div class="content">
    <div class="page-header">
      <div class="page-header menu">
        <div class="page-title">
          <h4>Call History</h4>
          <h6>Manage your products</h6>
        </div>
      </div>
    </div>
    <!-- /product list -->
    <div class="card table-list-card">
      <div class="card-body">
        <div class="table-responsive product-list">
          <table class="table  datanew list" matSort (matSortChange)="sortData($event)">
            <thead>
              <tr>
                <th class="no-sort">
                   <label class="checkboxs" (click)="selectAll(initChecked)"  (keydown.enter)="selectAll(initChecked)" tabindex="0"> 
                    <input type="checkbox" id="select-all" [(ngModel)]="initChecked">
                    <span class="checkmarks"></span>
                  </label>
                </th>
                <th mat-sort-header="username">Username</th>
                <th mat-sort-header="phoneNumber">Phone Number</th>
                <th mat-sort-header="callType">Call Type</th>
                <th mat-sort-header="duration">Duration</th>
                <th mat-sort-header="dateTime">Date & Time</th>
                <th class="no-sort">Action</th>
              </tr>
            </thead>
            <tbody>
              @for (data of tableData; track data) {
              <tr>
                <td>
                  <label class="checkboxs">
                    <input type="checkbox" [(ngModel)]="data.isSelected">
                    <span class="checkmarks"></span>
                  </label>
                </td>
                <td>
                  <div class="userimgname">
                    <a href="javascript:void(0);" class="product-img">
                      <img [src]="data.img" alt="product">
                    </a>
                    <a href="javascript:void(0);">{{data.username}}</a>
                  </div>
                </td>
                <td>{{data.phoneNumber}}</td>
                @if (data.audio === true) {
                <td class="phone-call-icon"><i class="feather icon-phone income-calls me-1"></i><i class="feather me-1"
                    [ngClass]="{'icon-arrow-down-left income-success': data.callType === 'Incoming Call' || data.callType === 'Outgoing Call', 'icon-arrow-down-right income-success-missed': data.callType === 'Missed Call'}"></i>{{data.callType}}
                </td>
                }
                @if (data.video === true) {
                <td class="phone-call-icon"><i class="feather icon-video income-calls me-1"></i><i class="feather me-1"
                    [ngClass]="{'icon-arrow-down-left income-success': data.callType === 'Incoming Call' || data.callType === 'Outgoing Call', 'icon-arrow-down-right income-success-missed': data.callType === 'Missed Call'}"></i>{{data.callType}}
                </td>
                }
                <td>{{data.duration}}</td>
                <td>{{data.dateTime}}</td>
                <td class="action-table-data">
                  <div class="edit-delete-action">
                    <a class="me-3 p-2" href="javascript:void(0);" data-bs-toggle="modal"
                      data-bs-target="#user-profile-new">
                      <i class="feather icon-eye feather-eye"></i>
                    </a>
                    <a class="confirm-text p-2" href="javascript:void(0);" (click)=confirmColor()>
                      <i class="feather icon-trash-2 feather-trash-2"></i>
                    </a>
                  </div>
                </td>
              </tr>
              }
            </tbody>
          </table>
        </div>
        <app-custom-pagination></app-custom-pagination>
      </div>
    </div>
    <!-- /product list -->
  </div>
</div>
<!-- details popup -->
<div class="modal fade" id="user-profile-new">
  <div class="modal-dialog history-modal-profile">
    <div class="modal-content">
      <div class="page-wrapper details-blk">
        <div class="content">
          <div class="text-center right-sidebar-profile mb-3">
            <figure class="avatar">
              <img src="assets/img/users/user-23.jpg" alt="image">
            </figure>
            <div class="chat-options chat-option-profile">
              <ul class="list-inline">
                <li class="list-inline-item">
                  <a [routerLink]="routes.audioCall" data-bs-dismiss class="btn btn-outline-light "
                    data-bs-toggle="tooltip" data-bs-placement="bottom" title="" data-bs-original-title="Voice Call"
                    matTooltip="Voice Call">
                    <i class="bx bx-phone"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a [routerLink]="routes.chat" class="btn btn-outline-light" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" title="" data-bs-original-title="Chat" matTooltip="Chat">
                    <i class="bx bx-message-square-dots"></i>
                  </a>
                </li>
                <li class="list-inline-item ">
                  <a [routerLink]="routes.videoCall" class="btn btn-outline-light profile-open" data-bs-toggle="tooltip"
                    data-bs-placement="bottom" matTooltip="Video Call" data-bs-original-title="Video Call">
                    <i class="bx bx-video"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="modal-profile-detail">
            <div class="row">
              <div class="col-lg-6">
                <div class="modal-userlist">
                  <ul>
                    <li>Name<span>Thomas</span></li>
                    <li>Phone<span>+1 25182 94528</span></li>
                    <li>Email<span>thomas&#64;example.com</span></li>
                  </ul>
                </div>
              </div>
              <div class="col-lg-6">
                <div class="modal-userlist d-flex justify-content-center">
                  <ul>
                    <li>Total Calls<span>20</span></li>
                    <li>Average Call Timing<span>0.30</span></li>
                    <li>Average Waiting Time<span>00.5</span></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /details popup -->
