// nextjs/nextjs/template/src/components/settings/financialSettings/bankAccounts.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React, { useState } from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import BankAccountsModal from "../../../core/modals/bank_accounts";
import CollapseHeader from "../../../core/common/collapse-header";

const BankAccountsComponent = () => {
  const route = all_routes;
  const [isActive, setIsActive] = useState("HDFC");

  const setActive = (theme:any) => {
    setIsActive(theme);
  };

  return (
    <div className="page-wrapper">
      <div className="content">
        <div className="row">
          <div className="col-md-12">
            {/* Page Header */}
            <div className="page-header">
              <div className="row align-items-center">
                <div className="col-8">
                  <h4 className="page-title">Settings</h4>
                </div>
                <div className="col-4 text-end">
                  <div className="head-icons">
                    <CollapseHeader />
                  </div>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Settings Menu */}
            <div className="card">
              <div className="card-body pb-0 pt-2">
              <ul className="nav nav-tabs nav-tabs-bottom">
                    <li className="nav-item me-3">
                      <Link href={route.profile} className="nav-link px-0 ">
                        <i className="ti ti-settings-cog" /> General Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.companySettings}
                        className="nav-link px-0 "
                      >
                        <i className="ti ti-world-cog" /> Website Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.invoiceSettings}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-apps" /> App Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link href={route.emailSettings} className="nav-link px-0 ">
                        <i className="ti ti-device-laptop" /> System Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.paymentGateways}
                        className="nav-link px-0 active"
                      >
                        <i className="ti ti-moneybag" /> Financial Settings
                      </Link>
                    </li>
                    <li className="nav-item ">
                      <Link href={route.storage} className="nav-link px-0 ">
                        <i className="ti ti-flag-cog" /> Other Settings
                      </Link>
                    </li>
                  </ul>
              </div>
            </div>
            {/* /Settings Menu */}
            <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">Financial Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
            <Link href={route.paymentGateways} className="fw-medium">
              Payment Gateways
            </Link>
            <Link href={route.bankAccounts} className="fw-medium active">
              Bank Accounts
            </Link>
            <Link href={route.taxRates} className="fw-medium">
              Tax Rates
            </Link>
            <Link href={route.currencies} className="fw-medium">
              Currencies
            </Link>
          </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Settings Info */}
    <div className="card">
      <div className="card-body pb-0">
        <div className="d-flex align-items-center justify-content-between mb-4">
          <h4 className="fs-20">Bank Accounts</h4>
          <Link
            href="#"
            className="btn btn-sm btn-icon rounded border"
            data-bs-toggle="modal"
            data-bs-target="#add_bank"
          >
            <i className="ti ti-plus" />
          </Link>
        </div>
        <div className="row">
          {/* Bank Account */}
          <div className="col-xxl-4 col-sm-6">
            <div className="bank-box active">
              <div className="mb-4">
                <h5 className="fw-semibold mb-1">HDFC</h5>
                <p className="fw-medium">**** **** 4872</p>
              </div>
              <div className="d-flex align-items-center justify-content-between">
                <div>
                  <h6 className="fw-medium mb-1">Holder Name</h6>
                  <p className="fs-12">Darlee Robertson</p>
                </div>
                <div className="dropdown table-action">
                  <Link
                    href="#"
                    className="action-icon"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    <i className="fa fa-ellipsis-v" />
                  </Link>
                  <div className="dropdown-menu dropdown-menu-right">
                    <Link
                      className="dropdown-item"
                      href="#"
                      data-bs-toggle="modal"
                      data-bs-target="#edit_bank"
                    >
                      <i className="fa-solid fa-pencil text-blue" /> Edit
                    </Link>
                    <Link
                      className="dropdown-item"
                      href="#"
                      data-bs-toggle="modal"
                      data-bs-target="#delete_bank"
                    >
                      <i className="fa-regular fa-trash-can text-danger" />{" "}
                      Delete
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /Bank Account */}
          {/* Bank Account */}
          <div className="col-xxl-4 col-sm-6">
            <div className="bank-box">
              <div className="mb-4">
                <h5 className="fw-semibold mb-1">SBI</h5>
                <p className="fw-medium">**** **** 2495</p>
              </div>
              <div className="d-flex align-items-center justify-content-between">
                <div>
                  <h6 className="fw-medium mb-1">Holder Name</h6>
                  <p className="fs-12">Sharon Roy</p>
                </div>
                <div className="dropdown table-action">
                  <Link
                    href="#"
                    className="action-icon"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    <i className="fa fa-ellipsis-v" />
                  </Link>
                  <div className="dropdown-menu dropdown-menu-right">
                    <Link
                      className="dropdown-item"
                      href="#"
                      data-bs-toggle="modal"
                      data-bs-target="#edit_bank"
                    >
                      <i className="fa-solid fa-pencil text-blue" /> Edit
                    </Link>
                    <Link
                      className="dropdown-item"
                      href="#"
                      data-bs-toggle="modal"
                      data-bs-target="#delete_bank"
                    >
                      <i className="fa-regular fa-trash-can text-danger" />{" "}
                      Delete
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /Bank Account */}
          {/* Bank Account */}
          <div className="col-xxl-4 col-sm-6">
            <div className="bank-box">
              <div className="mb-4">
                <h5 className="fw-semibold mb-1">KVB</h5>
                <p className="fw-medium">**** **** 3948</p>
              </div>
              <div className="d-flex align-items-center justify-content-between">
                <div>
                  <h6 className="fw-medium mb-1">Holder Name</h6>
                  <p className="fs-12">Vaughan</p>
                </div>
                <div className="dropdown table-action">
                  <Link
                    href="#"
                    className="action-icon"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    <i className="fa fa-ellipsis-v" />
                  </Link>
                  <div className="dropdown-menu dropdown-menu-right">
                    <Link
                      className="dropdown-item"
                      href="#"
                      data-bs-toggle="modal"
                      data-bs-target="#edit_bank"
                    >
                      <i className="fa-solid fa-pencil text-blue" /> Edit
                    </Link>
                    <Link
                      className="dropdown-item"
                      href="#"
                      data-bs-toggle="modal"
                      data-bs-target="#delete_bank"
                    >
                      <i className="fa-regular fa-trash-can text-danger" />{" "}
                      Delete
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {/* /Bank Account */}
        </div>
      </div>
    </div>
    {/* /Settings Info */}
  </div>
</div>

          </div>
        </div>
      </div>

      <BankAccountsModal />
    </div>
  );
};

export default BankAccountsComponent;

// vue/vue/src/views/pages/settings/financial-settings/bank-accounts.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Page Header -->
          <page-header :title="title" />
          <!-- /Page Header -->

          <!-- Settings Menu -->
          <settings-tabs></settings-tabs>
          <!-- /Settings Menu -->

          <div class="row">
            <financial-sidebar></financial-sidebar>
            <div class="col-xl-9 col-lg-12">
              <!-- Settings Info -->
              <div class="card">
                <div class="card-body pb-0">
                  <div class="d-flex align-items-center justify-content-between mb-4">
                    <h4 class="fs-20">Bank Accounts</h4>
                    <a
                      href="javascript:void(0)"
                      class="btn btn-sm btn-icon rounded border"
                      data-bs-toggle="modal"
                      data-bs-target="#add_bank"
                      ><i class="ti ti-plus"></i
                    ></a>
                  </div>
                  <div class="row">
                    <!-- Bank Account -->
                    <div
                      v-for="(bank, index) in banks"
                      :key="index"
                      class="col-xxl-4 col-sm-6"
                    >
                      <div
                        :class="{ 'bank-box': true, active: bank.active }"
                        @click="makeActive(index)"
                      >
                        <div class="mb-4">
                          <h5 class="fw-semibold mb-1">{{ bank.name }}</h5>
                          <p class="fw-medium">{{ bank.cardNumber }}</p>
                        </div>
                        <div class="d-flex align-items-center justify-content-between">
                          <div>
                            <h6 class="fw-medium mb-1">Holder Name</h6>
                            <p class="fs-12">{{ bank.holderName }}</p>
                          </div>
                          <div class="dropdown table-action">
                            <a
                              href="#"
                              class="action-icon"
                              data-bs-toggle="dropdown"
                              aria-expanded="false"
                              ><i class="fa fa-ellipsis-v"></i
                            ></a>
                            <div class="dropdown-menu dropdown-menu-right">
                              <a
                                class="dropdown-item"
                                href="#"
                                data-bs-toggle="modal"
                                data-bs-target="#edit_bank"
                                ><i class="fa-solid fa-pencil text-blue"></i> Edit</a
                              >
                              <a
                                class="dropdown-item"
                                href="#"
                                data-bs-toggle="modal"
                                data-bs-target="#delete_bank"
                                ><i class="fa-regular fa-trash-can text-danger"></i>
                                Delete</a
                              >
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- /Bank Account -->
                  </div>
                </div>
              </div>
              <!-- /Settings Info -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <bank-modal></bank-modal>
</template>
<script>
export default {
  data() {
    return {
      title: "Settings",
      banks: [
        {
          name: "HDFC",
          cardNumber: "**** **** 4872",
          holderName: "Darlee Robertson",
          active: true,
        },
        {
          name: "SBI",
          cardNumber: "**** **** 2495",
          holderName: "Sharon Roy",
          active: false,
        },
        {
          name: "KVB",
          cardNumber: "**** **** 3948",
          holderName: "Vaughan",
          active: false,
        },
      ],
    };
  },
  methods: {
    makeActive(index) {
      this.banks.forEach((bank, i) => {
        bank.active = i === index;
      });
    },
  },
};
</script>
