// nextjs/nextjs/template/src/components/settings/websiteSettings/companySettings.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import CollapseHeader from "../../../core/common/collapse-header";

const CompanySettingsComponent = () => {
  const route = all_routes;
  return (
    <div className="page-wrapper">
      <div className="content">
        <div className="row">
          <div className="col-md-12">
            {/* Page Header */}
            <div className="page-header">
              <div className="row align-items-center">
                <div className="col-8">
                  <h4 className="page-title">Settings</h4>
                </div>
                <div className="col-4 text-end">
                  <div className="head-icons">
                    <CollapseHeader />
                  </div>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Settings Menu */}
            <div className="card">
              <div className="card-body pb-0 pt-2">
              <ul className="nav nav-tabs nav-tabs-bottom">
                    <li className="nav-item me-3">
                      <Link href={route.profile} className="nav-link px-0 ">
                        <i className="ti ti-settings-cog" /> General Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.companySettings}
                        className="nav-link px-0 active"
                      >
                        <i className="ti ti-world-cog" /> Website Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.invoiceSettings}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-apps" /> App Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link href={route.emailSettings} className="nav-link px-0 ">
                        <i className="ti ti-device-laptop" /> System Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.paymentGateways}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-moneybag" /> Financial Settings
                      </Link>
                    </li>
                    <li className="nav-item ">
                      <Link href={route.storage} className="nav-link px-0 ">
                        <i className="ti ti-flag-cog" /> Other Settings
                      </Link>
                    </li>
                  </ul>
              </div>
            </div>
            {/* /Settings Menu */}
            <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">Website Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
                          <Link
                            href={route.companySettings}
                            className="fw-medium"
                          >
                            Company Settings
                          </Link>
                          <Link href={route.localization} className="fw-medium active">
                            Localization
                          </Link>
                          <Link href={route.prefixes} className="fw-medium">
                            Prefixes
                          </Link>
                          <Link href={route.preference} className="fw-medium">
                            Preference
                          </Link>
                          <Link
                            href={route.appearance}
                            className="fw-medium"
                          >
                            Appearance
                          </Link>
                          <Link href={route.language} className="fw-medium">
                            Language
                          </Link>
                        </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Company Settings */}
    <div className="card">
      <div className="card-body">
        <h4 className="fw-semibold mb-3">Company Settings</h4>
        <form >
          <div className="border-bottom mb-3 pb-3">
            <h5 className="fw-semibold mb-1">Company Information</h5>
            <p>Provide the company information below</p>
          </div>
          <div className="border-bottom mb-3 ">
            <div className="row">
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">Company Name </label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">Company Email Address</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">Phone Number</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">Fax</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-md-4">
                <div className="mb-3">
                  <label className="form-label">Website</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
            </div>
          </div>
          <div className="border-bottom mb-3 pb-3">
            <h5 className="fw-semibold mb-1">Company Images</h5>
            <p>Provide the company images</p>
          </div>
          <div className="border-bottom mb-3">
            <div className="row">
              <div className="col-md-6">
                <div className="mb-3">
                  <div className="profile-upload">
                    <div className="profile-upload-img">
                      <span>
                        <i className="ti ti-photo" />
                      </span>
                      <img
                        src="assets/img/icons/company-icon-03.svg"
                        alt="img"
                        className="preview1"
                      />
                      <button type="button" className="profile-remove">
                        <i className="feather-x" />
                      </button>
                    </div>
                    <div className="profile-upload-content">
                      <label className="profile-upload-btn">
                        <i className="ti ti-file-broken" /> Upload File
                        <input type="file" className="input-img" />
                      </label>
                      <p>
                        Upload Logo of your company to display in website. JPG
                        or PNG. Max size of 800K
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="mb-3">
                  <div className="profile-upload">
                    <div className="profile-upload-img">
                      <span>
                        <i className="ti ti-photo" />
                      </span>
                      <img
                        src="assets/img/icons/company-icon-03.svg"
                        alt="img"
                        className="preview1"
                      />
                      <button type="button" className="profile-remove">
                        <i className="feather-x" />
                      </button>
                    </div>
                    <div className="profile-upload-content">
                      <label className="profile-upload-btn">
                        <i className="ti ti-file-broken" /> Upload File
                        <input type="file" className="input-img" />
                      </label>
                      <p>
                        Upload Logo of your company to display in website. JPG
                        or PNG. Max size of 800K
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="mb-3">
                  <div className="profile-upload">
                    <div className="profile-upload-img">
                      <span>
                        <i className="ti ti-photo" />
                      </span>
                      <img
                        src="assets/img/icons/company-icon-03.svg"
                        alt="img"
                        className="preview1"
                      />
                      <button type="button" className="profile-remove">
                        <i className="feather-x" />
                      </button>
                    </div>
                    <div className="profile-upload-content">
                      <label className="profile-upload-btn">
                        <i className="ti ti-file-broken" /> Upload File
                        <input type="file" className="input-img" />
                      </label>
                      <p>
                        Upload Logo of your company to display in website. JPG
                        or PNG. Max size of 800K
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-6">
                <div className="mb-3">
                  <div className="profile-upload">
                    <div className="profile-upload-img">
                      <span>
                        <i className="ti ti-photo" />
                      </span>
                      <img
                        src="assets/img/icons/company-icon-03.svg"
                        alt="img"
                        className="preview1"
                      />
                      <button type="button" className="profile-remove">
                        <i className="feather-x" />
                      </button>
                    </div>
                    <div className="profile-upload-content">
                      <label className="profile-upload-btn">
                        <i className="ti ti-file-broken" /> Upload File
                        <input type="file" className="input-img" />
                      </label>
                      <p>
                        Upload Logo of your company to display in website. JPG
                        or PNG. Max size of 800K
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="border-bottom mb-3 pb-3">
            <h5 className="fw-semibold mb-1">Address</h5>
            <p>Please enter the company address details</p>
          </div>
          <div className="border-bottom mb-3">
            <div className="row">
              <div className="col-md-12">
                <div className="mb-3">
                  <label className="form-label">Address</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-xl-3 col-md-4">
                <div className="mb-3">
                  <label className="form-label">Country</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-xl-3 col-md-4">
                <div className="mb-3">
                  <label className="form-label">State / Province</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-xl-3 col-md-4">
                <div className="mb-3">
                  <label className="form-label">Fax</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
              <div className="col-xl-3 col-md-4">
                <div className="mb-3">
                  <label className="form-label">Postal Code</label>
                  <input type="text" className="form-control" />
                </div>
              </div>
            </div>
          </div>
          <div>
            <Link href="#" className="btn btn-light me-2">
              Cancel
            </Link>
            <button type="button" className="btn btn-primary">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
    {/* /Company Settings */}
  </div>
</div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default CompanySettingsComponent;

// vue/vue/src/views/pages/settings/website-settings/company-settings.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Page Header -->
          <page-header :title="title" />
          <!-- /Page Header -->

          <!-- Settings Menu -->
          <settings-tabs></settings-tabs>
          <!-- /Settings Menu -->

          <div class="row">
            <website-sidebar></website-sidebar>

            <div class="col-xl-9 col-lg-12">
              <!-- Company Settings -->
              <div class="card">
                <div class="card-body">
                  <h4 class="fw-semibold mb-3">Company Settings</h4>
                  <form @submit.prevent="submitForm">
                    <div class="border-bottom mb-3 pb-3">
                      <h5 class="fw-semibold mb-1">Company Information</h5>
                      <p>Provide the company information below</p>
                    </div>
                    <div class="border-bottom mb-3">
                      <div class="row">
                        <div class="col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Company Name </label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Company Email Address</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Phone Number</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Fax</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Website</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="border-bottom mb-3 pb-3">
                      <h5 class="fw-semibold mb-1">Company Images</h5>
                      <p>Provide the company images</p>
                    </div>
                    <div class="border-bottom mb-3">
                      <div class="row">
                        <div class="col-md-6">
                          <div class="mb-3">
                            <div class="profile-upload">
                              <div class="profile-upload-img">
                                <span><i class="ti ti-photo"></i></span>
                                <img
                                  src="@/assets/img/icons/company-icon-03.svg"
                                  alt="img"
                                  class="preview1"
                                />
                                <button type="button" class="profile-remove">
                                  <i class="feather-x"></i>
                                </button>
                              </div>
                              <div class="profile-upload-content">
                                <label class="profile-upload-btn">
                                  <i class="ti ti-file-broken"></i> Upload File
                                  <input type="file" class="input-img" />
                                </label>
                                <p>
                                  Upload Logo of your company to display in website. JPG
                                  or PNG. Max size of 800K
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="mb-3">
                            <div class="profile-upload">
                              <div class="profile-upload-img">
                                <span><i class="ti ti-photo"></i></span>
                                <img
                                  src="@/assets/img/icons/company-icon-03.svg"
                                  alt="img"
                                  class="preview1"
                                />
                                <button type="button" class="profile-remove">
                                  <i class="feather-x"></i>
                                </button>
                              </div>
                              <div class="profile-upload-content">
                                <label class="profile-upload-btn">
                                  <i class="ti ti-file-broken"></i> Upload File
                                  <input type="file" class="input-img" />
                                </label>
                                <p>
                                  Upload Logo of your company to display in website. JPG
                                  or PNG. Max size of 800K
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="mb-3">
                            <div class="profile-upload">
                              <div class="profile-upload-img">
                                <span><i class="ti ti-photo"></i></span>
                                <img
                                  src="@/assets/img/icons/company-icon-03.svg"
                                  alt="img"
                                  class="preview1"
                                />
                                <button type="button" class="profile-remove">
                                  <i class="feather-x"></i>
                                </button>
                              </div>
                              <div class="profile-upload-content">
                                <label class="profile-upload-btn">
                                  <i class="ti ti-file-broken"></i> Upload File
                                  <input type="file" class="input-img" />
                                </label>
                                <p>
                                  Upload Logo of your company to display in website. JPG
                                  or PNG. Max size of 800K
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="mb-3">
                            <div class="profile-upload">
                              <div class="profile-upload-img">
                                <span><i class="ti ti-photo"></i></span>
                                <img
                                  src="@/assets/img/icons/company-icon-03.svg"
                                  alt="img"
                                  class="preview1"
                                />
                                <button type="button" class="profile-remove">
                                  <i class="feather-x"></i>
                                </button>
                              </div>
                              <div class="profile-upload-content">
                                <label class="profile-upload-btn">
                                  <i class="ti ti-file-broken"></i> Upload File
                                  <input type="file" class="input-img" />
                                </label>
                                <p>
                                  Upload Logo of your company to display in website. JPG
                                  or PNG. Max size of 800K
                                </p>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="border-bottom mb-3 pb-3">
                      <h5 class="fw-semibold mb-1">Address</h5>
                      <p>Please enter the company address details</p>
                    </div>
                    <div class="border-bottom mb-3">
                      <div class="row">
                        <div class="col-md-12">
                          <div class="mb-3">
                            <label class="form-label">Address</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-xl-3 col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Country</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-xl-3 col-md-4">
                          <div class="mb-3">
                            <label class="form-label">State / Province</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-xl-3 col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Fax</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                        <div class="col-xl-3 col-md-4">
                          <div class="mb-3">
                            <label class="form-label">Postal Code</label>
                            <input type="text" class="form-control" />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>
                      <a href="#" class="btn btn-light me-2">Cancel</a>
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form>
                </div>
              </div>
              <!-- /Company Settings -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      title: "Settings",
    };
  },
  methods: {
    submitForm() {
      this.$router.push("/website-settings/company-settings");
    },
  },
};
</script>
