// angular/angular/src/app/feature-module/settings/website-settings/localization-settings/localization-settings.component.ts
import { Component } from '@angular/core';
import { COMMA, ENTER } from '@angular/cdk/keycodes';
import { MatChipInputEvent, MatChipEditedEvent } from '@angular/material/chips';
import { DataService } from '../../../../../shared/data/data.service';
import { routes } from '../../../../../shared/routes/routes';
interface data {
  value: string;
}
export interface Fruit {
  name: string;
}
@Component({
    selector: 'app-localization-settings',
    templateUrl: './localization-settings.component.html',
    styleUrl: './localization-settings.component.scss',
    standalone: false
})
export class LocalizationSettingsComponent {
  public routes = routes;
  public selectedValue1 = '';
  public selectedValue2 = '';
  public selectedValue3 = '';
  public selectedValue4 = '';
  public selectedValue5 = '';
  public selectedValue6 = '';
  public selectedValue7 = '';
  public selectedValue8 = '';
  public selectedValue9 = '';
  public selectedValue10 = '';
  public selectedValue11 = '';
  public selectedValue12 = '';

  selectedList1: data[] = [{ value: 'English' }, { value: 'Spanish' }];
  selectedList2: data[] = [{ value: 'UTC 5:30' }, { value: '(UTC+11:00) INR' }];
  selectedList3: data[] = [{ value: '22 Jul 2023' }, { value: 'Jul 22 2023' }];
  selectedList4: data[] = [{ value: '12 Hours' }, { value: '24 Hours' }];
  selectedList5: data[] = [{ value: '2023' }, { value: '2022' }];
  selectedList6: data[] = [
    { value: 'January' },
    { value: 'February' },
    { value: 'March' },
  ];
  selectedList7: data[] = [
    { value: 'United Stated of America' },
    { value: 'India' },
  ];
  selectedList8: data[] = [{ value: '$' }, { value: '€' }, { value: '¥' }];
  selectedList9: data[] = [{ value: '$100' }, { value: '$400' }];
  selectedList10: data[] = [{ value: '.' }, { value: ',' }];
  selectedList11: data[] = [{ value: ',' }, { value: '.' }];
  selectedList12: data[] = [
    { value: 'Allow All Countries' },
    { value: 'Deny All Countries' },
  ];

  

  constructor( private data: DataService){}

  addOnBlur = true;
  readonly separatorKeysCodes = [ENTER, COMMA] as const;
  fruits: Fruit[] = [{ name: 'JPG' }, { name: 'GIF' }, { name: 'PNG' }];

  add(event: MatChipInputEvent): void {
    const value = (event.value || '').trim();
    if (value) {
      this.fruits.push({ name: value });
    }
    event.chipInput?.clear();
  }

  remove(fruit: Fruit): void {
    const index = this.fruits.indexOf(fruit);

    if (index >= 0) {
      this.fruits.splice(index, 1);
    }
  }

  edit(fruit: Fruit, event: MatChipEditedEvent) {
    const value = event.value.trim();
    if (!value) {
      this.remove(fruit);
      return;
    }
    const index = this.fruits.indexOf(fruit);
    if (index >= 0) {
      this.fruits[index].name = value;
    }
  }
}

<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">

        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h4 class="page-title">Settings</h4>
            </div>
            <div class="col-4 text-end">
              <div class="head-icons">
                <a [routerLink] = "routes.localizationSettings" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-original-title="Refresh" matTooltip="Refresh"><i class="ti ti-refresh-dot"></i></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <!-- Settings Menu -->
        <div class="card">
          <div class="card-body pb-0 pt-2">
            <ul class="nav nav-tabs nav-tabs-bottom">
              <li class="nav-item me-3">
                <a [routerLink] = "routes.generalSettings" class="nav-link px-0">
                  <i class="ti ti-settings-cog me-2"></i>General Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.companySettings" class="nav-link px-0 active">
                  <i class="ti ti-world-cog me-2"></i>Website Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.invoiceSettings" class="nav-link px-0">
                  <i class="ti ti-apps me-2"></i>App Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.emailSettings" class="nav-link px-0">
                  <i class="ti ti-device-laptop me-2"></i>System Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.paymentGatewaySettings" class="nav-link px-0">
                  <i class="ti ti-moneybag me-2"></i>Financial Settings
                </a>
              </li>
              <li class="nav-item">
                <a [routerLink] = "routes.storageSettings" class="nav-link px-0">
                  <i class="ti ti-flag-cog me-2"></i>Other Settings
                </a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /Settings Menu -->

        <div class="row">
          <div class="col-xl-3 col-lg-12 theiaStickySidebar">
            <div class="stickybar">
              <!-- Settings Sidebar -->
              <div class="card">
                <div class="card-body">
                  <div class="settings-sidebar">
                    <h4 class="fw-semibold mb-3">Website Settings</h4>
                    <div class="list-group list-group-flush settings-sidebar">
                      <a [routerLink] = "routes.companySettings" class="fw-medium">Company Settings</a>
                      <a [routerLink] = "routes.localizationSettings" class="fw-medium active">Localization</a>
                      <a [routerLink] = "routes.prefixes" class="fw-medium">Prefixes</a>
                      <a [routerLink] = "routes.preference" class="fw-medium">Preference</a>
                      <a [routerLink] = "routes.appearance" class="fw-medium">Appearance</a>
                      <a [routerLink] = "routes.languageSettings"class="fw-medium">Language</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Settings Sidebar -->
            </div>
          </div>

          <div class="col-xl-9 col-lg-12">

            <!-- Prefixes -->
            <div class="card">
              <div class="card-body">
                <div class="settings-header">
                  <h4 class="fw-semibold mb-3">Localization</h4>
                </div>
                <form>
                  <div class="border-bottom mb-3 pb-3">
                    <h5 class="fw-semibold mb-1">Basic Information</h5>
                    <p>Provide the basic information below</p>
                  </div>	
                  <div class="border-bottom mb-3">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Language</h6>
                          <p>Select Language of the website</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue1" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="English">
                            @for (data of selectedList1; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Language Switcher</h6>
                          <p>To display in all the pages</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <div class="status-toggle">
                            <input type="checkbox" id="prefer3" class="check" checked="">
                            <label for="prefer3" class="checktoggle"> </label>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Timezone</h6>
                          <p>Select date format to display in website</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue2" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="UTC 5:30">
                            @for (data of selectedList2; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Date Format</h6>
                          <p>Select Language of the website</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue3" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="22 Jul 2023">
                            @for (data of selectedList3; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Time Format</h6>
                          <p>Select time format to display in website</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue4" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="12 Hours">
                            @for (data of selectedList4; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Financial Year</h6>
                          <p>Select year for finance</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-wrap">
                          <mat-select [(ngModel)]="selectedValue5" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="2023">
                            @for (data of selectedList5; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Starting Month</h6>
                          <p>Select starting month to display</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue6" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="January">
                            @for (data of selectedList6; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="border-bottom mb-3 pb-3">
                    <h5 class="fw-semibold mb-1">Currency Settings</h5>
                    <p>Provide the currency information below</p>
                  </div>	
                  <div class="border-bottom mb-3">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Currency</h6>
                          <p>Select currency</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue7" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="United Stated of America">
                            @for (data of selectedList7; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Currency Symbol</h6>
                          <p>Select currency symbol</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue8" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="$">
                            @for (data of selectedList8; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Currency Position</h6>
                          <p>Select currency position</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue9" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"
                            placeholder="$100">
                            @for (data of selectedList9; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Decimal Seperator</h6>
                          <p>Select decimal seperator</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue10" [ngModelOptions]="{standalone: true}"
                            class="select custom-mat-select" placeholder=".">
                            @for (data of selectedList10; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Thousand Seperator</h6>
                          <p>Select thousand seperator</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue11" [ngModelOptions]="{standalone: true}"
                            class="select custom-mat-select" placeholder=",">
                            @for (data of selectedList11; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="border-bottom mb-3 pb-3">
                    <h5 class="fw-semibold mb-1">Country Settings</h5>
                    <p>Provide the country information below</p>
                  </div>	
                  <div class="border-bottom mb-3">
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Countries Restriction</h6>
                          <p>Select restricted countries</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <mat-select [(ngModel)]="selectedValue12" [ngModelOptions]="{standalone: true}"
                            class="select custom-mat-select" placeholder="Allow All Countries">
                            @for (data of selectedList12; track data) {
                            <mat-option [value]="data.value">
                              {{data.value}}
                            </mat-option>
                            }
                          </mat-select>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="border-bottom mb-3 pb-3">
                    <h5 class="fw-semibold mb-1">File Settings</h5>
                    <p>Provide the files information below</p>
                  </div>	
                  <div class="border-bottom mb-3 border-0 mb-0">		
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Allowed Files</h6>
                          <p>Select allowed files</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <input class="input-tags form-control" type="text" data-role="tagsinput"  name="Label" value="JPG, PNG, GIF" >	
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="mb-3">
                          <h6>Max File Size</h6>
                          <p>Select size of the files</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <input type="text" class="form-control" value="5000MB">
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <a href="javascript:void(0);" class="btn btn-light me-2">Cancel</a>
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                  </div>
                </form>
              </div>
            </div>
            <!-- /Prefixes -->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

// vue/vue/src/views/pages/settings/website-settings/localization-settings.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Page Header -->
          <page-header :title="title" />
          <!-- /Page Header -->

          <!-- Settings Menu -->
          <settings-tabs></settings-tabs>
          <!-- /Settings Menu -->

          <div class="row">
            <website-sidebar></website-sidebar>
            <div class="col-xl-9 col-lg-12">
              <!-- Prefixes -->
              <div class="card">
                <div class="card-body">
                  <h4 class="fw-semibold mb-3">Localization</h4>
                  <form @submit.prevent="submitForm">
                    <div class="border-bottom mb-3 pb-3">
                      <h5 class="fw-semibold mb-1">Basic Information</h5>
                      <p>Provide the basic information below</p>
                    </div>
                    <div class="border-bottom mb-3">
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Language</h6>
                            <p>Select Language of the website</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="Engliseti"
                              id="engliseti"
                              placeholder="English"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Language Switcher</h6>
                            <p>To display in all the pages</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <div class="status-toggle">
                              <input
                                type="checkbox"
                                id="prefer3"
                                class="check"
                                checked=""
                              />
                              <label for="prefer3" class="checktoggle"> </label>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Timezone</h6>
                            <p>Select date format to display in website</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="TimeSel"
                              id="timesel"
                              placeholder="UTC 4:30"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Date Format</h6>
                            <p>Select Language of the website</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="FormatSel"
                              id="formatsel"
                              placeholder="01 Jan 2023"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Time Format</h6>
                            <p>Select time format to display in website</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="HourSel"
                              id="hoursel"
                              placeholder="English"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Financial Year</h6>
                            <p>Select year for finance</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="YearSel"
                              id="yearsel"
                              placeholder="2023"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Starting Month</h6>
                            <p>Select starting month to display</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="MothSel"
                              id="monthsel"
                              placeholder="January"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="border-bottom mb-3 pb-3">
                      <h5 class="fw-semibold mb-1">Currency Settings</h5>
                      <p>Provide the currency information below</p>
                    </div>
                    <div class="border-bottom mb-3">
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Currency</h6>
                            <p>Select currency</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="CountrySel"
                              id="countrysel"
                              placeholder="United States Of America"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Currency Symbol</h6>
                            <p>Select currency symbol</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="SymbolSel"
                              id="symnbolsel"
                              placholder="$"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Currency Position</h6>
                            <p>Select currency position</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="AmountSel"
                              id="amountsel"
                              placeholder="$100"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Decimal Seperator</h6>
                            <p>Select decimal seperator</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select :options="Sele" id="sele" placeholder="," />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Thousand Seperator</h6>
                            <p>Select thousand seperator</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select :options="OpSel" id="opsel" placeholder="," />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="border-bottom mb-3 pb-3">
                      <h5 class="fw-semibold mb-1">Country Settings</h5>
                      <p>Provide the country information below</p>
                    </div>
                    <div class="border-bottom mb-3">
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Countries Restriction</h6>
                            <p>Select restricted countries</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue-select
                              :options="AllCounSel"
                              id="allcounsel"
                              placeholder="Allow All Countries"
                            />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="border-bottom mb-3 pb-3">
                      <h5 class="fw-semibold mb-1">File Settings</h5>
                      <p>Provide the files information below</p>
                    </div>
                    <div class="border-bottom mb-3 border-0 mb-0">
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Allowed Files</h6>
                            <p>Select allowed files</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <vue3-tags-input
                              class="input-tags form-control"
                              type="text"
                              data-role="tagsinput"
                              name="Label"
                              value="JPG, PNG, GIF"
                              :tags="tags"
                            />
                          </div>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-8">
                          <div class="mb-3">
                            <h6>Max File Size</h6>
                            <p>Select size of the files</p>
                          </div>
                        </div>
                        <div class="col-md-4">
                          <div class="mb-3">
                            <input type="text" class="form-control" value="5000MB" />
                          </div>
                        </div>
                      </div>
                    </div>
                    <div>
                      <a href="#" class="btn btn-light me-2">Cancel</a>
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form>
                </div>
              </div>
              <!-- /Prefixes -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import Vue3TagsInput from "vue3-tags-input";
export default {
  components: {
    Vue3TagsInput,
  },
  data() {
    return {
      title: "Settings",
      AllCountSel: ["Allow All Countries", "Deny All COuntries"],
      OpSel: [",", "."],
      Sele: [",", ","],
      AmountSel: ["$100", "$400"],
      SymbolSel: ["$", "€"],
      Country: ["United States Of America", "India"],
      MothSel: ["January", "February", "March"],
      Engliseti: ["English", "Chinese", "Hindi"],
      TimeSel: ["UTC 4:30", "(UTC+11:00) INR"],
      FormatSel: ["01 Jan 2023", "01-Jan-2023"],
      HourSel: ["English", "12 Hours", "24 Hours"],
      YearSel: ["2023", "2024", "2022"],
      CountrySel: ["United States Of America", "India"],
      tags: ["JPG", "PNG", "GIF"],
      AllCounSel: ["Allow All Countries", "Deny All Countries"],
    };
  },
  methods: {
    submitForm() {
      this.$router.push("/website-settings/localization");
    },
  },
};
</script>
