// nextjs/nextjs/template/src/components/application/email.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from 'react'
import Link from "next/link";

const  EmailComponent = () => {
  return (
    <div className="page-wrapper">
  <div className="content">
    <div className="page-header">
      <div className="row">
        <div className="col">
          <h3 className="page-title">Inbox</h3>
        </div>
      </div>
    </div>
    <div className="row">
      <div className="col-lg-3 col-md-12">
        <div className="compose-btn">
          <Link
            href="#"
            className="btn btn-primary btn-block w-100"
          >
            Compose
          </Link>
        </div>
        <ul className="inbox-menu">
          <li className="active">
            <Link href="#">
              <i className="fas fa-download" /> Inbox{" "}
              <span className="mail-count">(5)</span>
            </Link>
          </li>
          <li>
            <Link href="#">
              <i className="far fa-star" /> Important
            </Link>
          </li>
          <li>
            <Link href="#">
              <i className="far fa-paper-plane" /> Sent Mail
            </Link>
          </li>
          <li>
            <Link href="#">
              <i className="far fa-file-alt" /> Drafts{" "}
              <span className="mail-count">(13)</span>
            </Link>
          </li>
          <li>
            <Link href="#">
              <i className="far fa-trash-alt" /> Trash
            </Link>
          </li>
        </ul>
      </div>
      <div className="col-lg-9 col-md-12">
        <div className="card">
          <div className="card-body">
            <div className="email-header">
              <div className="row">
                <div className="col-lg-9 top-action-left col-sm-12">
                  <div className="float-left">
                    <div className="btn-group dropdown-action me-1">
                      <button
                        type="button"
                        className="btn btn-white dropdown-toggle"
                        data-bs-toggle="dropdown"
                      >
                        Select <i className="fas fa-angle-down" />
                      </button>
                      <div className="dropdown-menu">
                        <Link className="dropdown-item" href="#">
                          All
                        </Link>
                        <Link className="dropdown-item" href="#">
                          None
                        </Link>
                        <div className="dropdown-divider" />
                        <Link className="dropdown-item" href="#">
                          Read
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Unread
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action me-1">
                      <button
                        type="button"
                        className="btn btn-white dropdown-toggle"
                        data-bs-toggle="dropdown"
                      >
                        Actions <i className="fas fa-angle-down" />
                      </button>
                      <div className="dropdown-menu">
                        <Link className="dropdown-item" href="#">
                          Reply
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Forward
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Archive
                        </Link>
                        <div className="dropdown-divider" />
                        <Link className="dropdown-item" href="#">
                          Mark As Read
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Mark As Unread
                        </Link>
                        <div className="dropdown-divider" />
                        <Link className="dropdown-item" href="#">
                          Delete
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action me-1">
                      <button
                        type="button"
                        className="btn btn-white dropdown-toggle"
                        data-bs-toggle="dropdown"
                      >
                        <i className="fas fa-folder" />{" "}
                        <i className="fas fa-angle-down" />
                      </button>
                      <div role="menu" className="dropdown-menu">
                        <Link className="dropdown-item" href="#">
                          Social
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Forums
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Updates
                        </Link>
                        <div className="dropdown-divider" />
                        <Link className="dropdown-item" href="#">
                          Spam
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Trash
                        </Link>
                        <div className="dropdown-divider" />
                        <Link className="dropdown-item" href="#">
                          New
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action me-1">
                      <button
                        type="button"
                        data-bs-toggle="dropdown"
                        className="btn btn-white dropdown-toggle"
                      >
                        <i className="fas fa-tags" />{" "}
                        <i className="fas fa-angle-down" />
                      </button>
                      <div role="menu" className="dropdown-menu">
                        <Link className="dropdown-item" href="#">
                          Work
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Family
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Social
                        </Link>
                        <div className="dropdown-divider" />
                        <Link className="dropdown-item" href="#">
                          Primary
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Promotions
                        </Link>
                        <Link className="dropdown-item" href="#">
                          Forums
                        </Link>
                      </div>
                    </div>
                    <div className="btn-group dropdown-action mail-search">
                      <input
                        type="text"
                        placeholder="Search Messages"
                        className="form-control search-message"
                      />
                    </div>
                  </div>
                </div>
                <div className="col-lg-3 top-action-right col-sm-12">
                  <div className="text-end ">
                    <button
                      type="button"
                      title="Refresh"
                      data-toggle="tooltip"
                      className="btn btn-white d-none d-md-inline-block me-1"
                    >
                      <i className="fas fa-sync-alt" />
                    </button>
                    <div className="btn-group">
                      <Link href="#" className="btn btn-white">
                        <i className="fas fa-angle-left" />
                      </Link>
                      <Link href="#" className="btn btn-white">
                        <i className="fas fa-angle-right" />
                      </Link>
                    </div>
                  </div>
                  <div className="text-end">
                    <span className="text-muted d-none d-md-inline-block">
                      Showing 10 of 112{" "}
                    </span>
                  </div>
                </div>
              </div>
            </div>
            <div className="email-content">
              <div className="table-responsive">
                <table className="table table-inbox table-hover">
                  <thead>
                    <tr>
                      <th colSpan={6}>
                        <label className="checkboxs">
                          <input type="checkbox" id="select-all" />
                          <span className="checkmarks" />
                        </label>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="unread clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="fas fa-star starred" />
                        </span>
                      </td>
                      <td className="name">John Doe</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td>
                        <i className="fas fa-paperclip" />
                      </td>
                      <td className="mail-date">13:14</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Envato Account</td>
                      <td className="subject">
                        Important account security update from Envato
                      </td>
                      <td />
                      <td className="mail-date">8:42</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Twitter</td>
                      <td className="subject">HRMS Bootstrap Admin Template</td>
                      <td />
                      <td className="mail-date">30 Nov</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Richard Parker</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">18 Sep</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">John Smith</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">21 Aug</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">me, Robert Smith (3)</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">1 Aug</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Codecanyon</td>
                      <td className="subject">Welcome To Codecanyon</td>
                      <td />
                      <td className="mail-date">Jul 13</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">Richard Miles</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td>
                        <i className="fas fa-paperclip" />
                      </td>
                      <td className="mail-date">May 14</td>
                    </tr>
                    <tr className="unread clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star" />
                        </span>
                      </td>
                      <td className="name">John Smith</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">11/11/16</td>
                    </tr>
                    <tr className="clickable-row">
                      <td>
                        <label className="checkboxs">
                          <input type="checkbox" />
                          <span className="checkmarks" />
                        </label>
                      </td>
                      <td>
                        <span className="mail-important">
                          <i className="far fa-star starred" />
                        </span>
                      </td>
                      <td className="name">Mike Litorus</td>
                      <td className="subject">
                        Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                      </td>
                      <td />
                      <td className="mail-date">10/31/16</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  )
}

export default EmailComponent

// angular/angular/src/app/feature-module/main-menu/application/email/email.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-email',
    templateUrl: './email.component.html',
    styleUrls: ['./email.component.scss'],
    standalone: false
})
export class EmailComponent {
  checkAll = false;
  checkbox1 = false;
  checkbox2 = false;
  checkbox3 = false;
  checkbox4 = false;
  checkbox5 = false;
  checkbox6 = false;
  checkbox7 = false;
  checkbox8 = false;
  checkbox9 = false;
  checkbox10 = false;


  toggleAllCheckboxes() {
    this.checkbox1 = this.checkAll;
    this.checkbox2 = this.checkAll;
    this.checkbox3 = this.checkAll;
    this.checkbox4 = this.checkAll;
    this.checkbox5 = this.checkAll;
    this.checkbox6 = this.checkAll;
    this.checkbox7 = this.checkAll;
    this.checkbox8 = this.checkAll;
    this.checkbox9 = this.checkAll;
    this.checkbox10 = this.checkAll;
  }
}

<div class="page-wrapper">
    <div class="content">
        <div class="page-header">
            <div class="row">
                <div class="col">
                    <h3 class="page-title">Inbox</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-12">
                <div class="compose-btn">
                    <a href="javascript:void(0);" class="btn btn-primary btn-block w-100">
                        Compose
                    </a>
                </div>
                <ul class="inbox-menu">
                    <li class="active">
                        <a href="javascript:void(0);"><i class="fas fa-download"></i> Inbox <span
                                class="mail-count">(5)</span></a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><i class="far fa-star"></i> Important</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><i class="far fa-paper-plane"></i> Sent Mail</a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><i class="far fa-file-alt"></i> Drafts <span
                                class="mail-count">(13)</span></a>
                    </li>
                    <li>
                        <a href="javascript:void(0);"><i class="far fa-trash-alt"></i> Trash</a>
                    </li>
                </ul>
            </div>

            <div class="col-lg-9 col-md-12">
                <div class="card bg-white">
                    <div class="card-body">
                        <div class="email-header">
                            <div class="row">
                                <div class="col-lg-9 top-action-left col-sm-12">
                                    <div class="float-left">
                                        <div class="btn-group dropdown-action me-1">
                                            <button type="button" class="btn btn-white dropdown-toggle"
                                                data-bs-toggle="dropdown">Select <i
                                                    class="fas fa-angle-down"></i></button>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" href="javascript:void(0);">All</a>
                                                <a class="dropdown-item" href="javascript:void(0);">None</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0);">Read</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Unread</a>
                                            </div>
                                        </div>
                                        <div class="btn-group dropdown-action me-1">
                                            <button type="button" class="btn btn-white dropdown-toggle"
                                                data-bs-toggle="dropdown">Actions <i
                                                    class="fas fa-angle-down"></i></button>
                                            <div class="dropdown-menu">
                                                <a class="dropdown-item" href="javascript:void(0);">Reply</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Forward</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Archive</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0);">Mark As Read</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Mark As Unread</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0);">Delete</a>
                                            </div>
                                        </div>
                                        <div class="btn-group dropdown-action me-1">
                                            <button type="button" class="btn btn-white dropdown-toggle"
                                                data-bs-toggle="dropdown"><i class="fas fa-folder"></i> <i
                                                    class="fas fa-angle-down"></i></button>
                                            <div role="menu" class="dropdown-menu">
                                                <a class="dropdown-item" href="javascript:void(0);">Social</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Forums</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Updates</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0);">Spam</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Trash</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0);">New</a>
                                            </div>
                                        </div>
                                        <div class="btn-group dropdown-action me-1">
                                            <button type="button" data-bs-toggle="dropdown"
                                                class="btn btn-white dropdown-toggle"><i class="fas fa-tags"></i> <i
                                                    class="fas fa-angle-down"></i></button>
                                            <div role="menu" class="dropdown-menu">
                                                <a class="dropdown-item" href="javascript:void(0);">Work</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Family</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Social</a>
                                                <div class="dropdown-divider"></div>
                                                <a class="dropdown-item" href="javascript:void(0);">Primary</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Promotions</a>
                                                <a class="dropdown-item" href="javascript:void(0);">Forums</a>
                                            </div>
                                        </div>
                                        <div class="btn-group dropdown-action mail-search">
                                            <input type="text" placeholder="Search Messages"
                                                class="form-control search-message">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 top-action-right col-sm-12">
                                    <div class="text-end ">
                                        <button type="button" title="Refresh" data-toggle="tooltip"
                                            class="btn btn-white d-none d-md-inline-block me-1"><i
                                                class="fas fa-sync-alt"></i></button>
                                        <div class="btn-group">
                                            <a class="btn btn-white"><i class="fas fa-angle-left"></i></a>
                                            <a class="btn btn-white"><i class="fas fa-angle-right"></i></a>
                                        </div>
                                    </div>
                                    <div class="text-end">
                                        <span class="text-muted d-none d-md-inline-block">Showing 10 of 112 </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="email-content">
                            <div class="table-responsive">
                                <table class="table table-inbox table-hover">
                                    <thead>
                                        <tr>
                                            <th colspan="6">
                                                <label class="checkboxs">
                                                    <input type="checkbox" id="select-all" [(ngModel)]="checkAll"
                                                        (change)="toggleAllCheckboxes()">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="unread clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox1">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="fas fa-star starred"></i></span>
                                            </td>
                                            <td class="name">John Doe</td>
                                            <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                                            </td>
                                            <td><i class="fas fa-paperclip"></i></td>
                                            <td class="mail-date">13:14</td>
                                        </tr>
                                        <tr class="unread clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox2">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">Envato Account</td>
                                            <td class="subject">Important account security update from Envato</td>
                                            <td></td>
                                            <td class="mail-date">8:42</td>
                                        </tr>
                                        <tr class="clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox3">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">Twitter</td>
                                            <td class="subject">HRMS Bootstrap Admin Template</td>
                                            <td></td>
                                            <td class="mail-date">30 Nov</td>
                                        </tr>
                                        <tr class="unread clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox4">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">Richard Parker</td>
                                            <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                                            </td>
                                            <td></td>
                                            <td class="mail-date">18 Sep</td>
                                        </tr>
                                        <tr class="clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox5">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">John Smith</td>
                                            <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                                            </td>
                                            <td></td>
                                            <td class="mail-date">21 Aug</td>
                                        </tr>
                                        <tr class="clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox6">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">me, Robert Smith (3)</td>
                                            <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                                            </td>
                                            <td></td>
                                            <td class="mail-date">1 Aug</td>
                                        </tr>
                                        <tr class="unread clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox7">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">Codecanyon</td>
                                            <td class="subject">Welcome To Codecanyon</td>
                                            <td></td>
                                            <td class="mail-date">Jul 13</td>
                                        </tr>
                                        <tr class="clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox8">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">Richard Miles</td>
                                            <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                                            </td>
                                            <td><i class="fas fa-paperclip"></i></td>
                                            <td class="mail-date">May 14</td>
                                        </tr>
                                        <tr class="unread clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox9">
                                                    <span class="checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star"></i></span></td>
                                            <td class="name">John Smith</td>
                                            <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                                            </td>
                                            <td></td>
                                            <td class="mail-date">11/11/16</td>
                                        </tr>
                                        <tr class="clickable-row">
                                            <td>
                                                <label class="checkboxs">
                                                    <input type="checkbox" [(ngModel)]="checkbox10">
                                                    <span class=" checkmarks"></span>
                                                </label>
                                            </td>
                                            <td><span class="mail-important"><i class="far fa-star starred"></i></span>
                                            </td>
                                            <td class="name">Mike Litorus</td>
                                            <td class="subject">Lorem ipsum dolor sit amet, consectetuer adipiscing elit
                                            </td>
                                            <td></td>
                                            <td class="mail-date">10/31/16</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="searchpart">
    <div class="searchcontent">
        <div class="searchhead">
            <h3>Search </h3>
            <a id="closesearch"><i class="fa fa-times-circle" aria-hidden="true"></i></a>
        </div>
        <div class="searchcontents">
            <div class="searchparts">
                <input type="text" placeholder="search here">
                <a class="btn btn-searchs">Search</a>
            </div>
            <div class="recentsearch">
                <h2>Recent Search</h2>
                <ul>
                    <li>
                        <h6><i class="fa fa-search me-2"></i> Settings</h6>
                    </li>
                    <li>
                        <h6><i class="fa fa-search me-2"></i> Report</h6>
                    </li>
                    <li>
                        <h6><i class="fa fa-search me-2"></i> Invoice</h6>
                    </li>
                    <li>
                        <h6><i class="fa fa-search me-2"></i> Sales</h6>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
