// vue/vue/src/views/pages/pages/blank-page.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <div class="page-header">
            <div class="row align-items-center">
              <div class="col-8">
                <h3 class="page-title">Blank Page</h3>
              </div>
              <div class="col-4 text-sm-end">
                <div class="title-head">
                  <div class="head-icons">
                    <router-link
                      to="/blank-page"
                      data-bs-toggle="tooltip"
                      data-bs-placement="top"
                      data-bs-original-title="Refresh"
                      ><i class="ti ti-refresh-dot"></i
                    ></router-link>
                    <a
                      href="javascript:void(0);"
                      data-bs-toggle="tooltip"
                      data-bs-placement="top"
                      data-bs-original-title="Collapse"
                      id="collapse-header"
                      ><i class="ti ti-chevrons-up"></i
                    ></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
  data() {
    return {
      title: "Blank Page",
    };
  },
};
</script>

// nextjs/nextjs/template/src/components/pages/blankPage.tsx
import React from 'react'
import CollapseHeader from '../../core/common/collapse-header';

const BlankPageComponent = () => {

  return (

   <div className="page-wrapper">
  <div className="content">
    <div className="row">
      <div className="col-md-12">
        <div className="page-header">
          <div className="row align-items-center ">
            <div className="col-8">
              <h3 className="page-title">Blank Page</h3>
            </div>
            <div className="col-4 text-sm-end">
              <div className="title-head">
                <div className="head-icons">
                  <CollapseHeader />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



  )
}

export default BlankPageComponent
