// vue/vue/src/views/pages/settings/website-settings/language-settings.vue
<template>
  <layouts-header></layouts-header>
  <layouts-sidebar></layouts-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="row">
        <div class="col-md-12">
          <!-- Page Header -->
          <page-header :title="title" />
          <!-- /Page Header -->

          <!-- Settings Menu -->
          <settings-tabs></settings-tabs>
          <!-- /Settings Menu -->

          <div class="row">
            <website-sidebar></website-sidebar>
            <div class="col-xl-9 col-lg-12">
              <!-- Custom Fields -->
              <div class="card">
                <div class="card-body">
                  <h4 class="fw-semibold mb-3">Language</h4>
                  <!-- Search -->
                  <div class="row">
                    <div class="col-xl-3 col-md-3 col-lg-5">
                      <div class="mb-3 icon-form">
                        <span class="form-icon"><i class="ti ti-search"></i></span>
                        <input
                          type="text"
                          class="form-control"
                          placeholder="Search Language"
                        />
                      </div>
                    </div>
                    <div class="col-xl-9 col-md-9 col-lg-12">
                      <div
                        class="d-flex align-items-center flex-wrap justify-content-sm-end"
                      >
                        <div class="dropdown me-2 mb-3">
                          <a
                            href="javascript:void(0);"
                            class="dropdown-toggle"
                            data-bs-toggle="dropdown"
                            ><i class="ti ti-package-export me-2"></i>Export</a
                          >
                          <div class="dropdown-menu dropdown-menu-end">
                            <ul>
                              <li>
                                <a href="javascript:void(0);" class="dropdown-item"
                                  ><i class="ti ti-file-type-pdf text-danger me-1"></i
                                  >Export as PDF</a
                                >
                              </li>
                              <li>
                                <a href="javascript:void(0);" class="dropdown-item"
                                  ><i class="ti ti-file-type-xls text-green me-1"></i
                                  >Export as Excel
                                </a>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <a
                          href="javascript:void(0);"
                          class="btn btn-primary me-2 mb-3"
                          data-bs-toggle="modal"
                          data-bs-target="#import_sample"
                          ><i class="ti ti-download me-2"></i>Import Sample</a
                        >
                        <a
                          href="javascript:void(0);"
                          class="btn btn-primary mb-3"
                          data-bs-toggle="modal"
                          data-bs-target="#add_translation"
                          ><i class="ti ti-square-rounded-plus me-2"></i>Add
                          Translation</a
                        >
                      </div>
                    </div>
                  </div>
                  <!-- /Search -->

                  <!-- Filter -->
                  <div
                    class="d-flex align-items-center justify-content-between flex-wrap mb-2"
                  >
                    <div class="dropdown mb-3">
                      <a
                        href="javascript:void(0);"
                        class="dropdown-toggle"
                        data-bs-toggle="dropdown"
                        ><i class="ti ti-sort-ascending-2 me-2"></i>Sort
                      </a>
                      <div class="dropdown-menu dropdown-menu-start">
                        <ul>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item">
                              <i class="ti ti-circle-chevron-right me-1"></i>Ascending
                            </a>
                          </li>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item">
                              <i class="ti ti-circle-chevron-right me-1"></i>Descending
                            </a>
                          </li>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item">
                              <i class="ti ti-circle-chevron-right me-1"></i>Recently
                              Viewed
                            </a>
                          </li>
                          <li>
                            <a href="javascript:void(0);" class="dropdown-item">
                              <i class="ti ti-circle-chevron-right me-1"></i>Recently
                              Added
                            </a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="dropdown mb-3">
                      <a
                        href="javascript:void(0);"
                        class="btn bg-soft-purple text-purple"
                        data-bs-toggle="dropdown"
                        data-bs-auto-close="outside"
                        ><i class="ti ti-columns-3 me-2"></i>Manage Columns</a
                      >
                      <div class="dropdown-menu dropdown-menu-md-end dropdown-md p-3">
                        <h4 class="mb-2 fw-semibold">Want to manage datatables?</h4>
                        <p class="mb-3">
                          Please drag and drop your column to reorder your table and
                          enable see option as you want.
                        </p>
                        <div class="border-top pt-3">
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Language
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-name" class="check" />
                              <label for="col-name" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Code
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-phone" class="check" />
                              <label for="col-phone" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>RTL
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-email" class="check" />
                              <label for="col-email" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Total
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-tag" class="check" />
                              <label for="col-tag" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Done
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-loc" class="check" />
                              <label for="col-loc" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Progress
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-rate" class="check" />
                              <label for="col-rate" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Status
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-owner" class="check" />
                              <label for="col-owner" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Contact
                            </p>
                            <div class="status-toggle">
                              <input
                                type="checkbox"
                                id="col-contact"
                                class="check"
                                checked=""
                              />
                              <label for="col-contact" class="checktoggle"></label>
                            </div>
                          </div>
                          <div
                            class="d-flex align-items-center justify-content-between mb-3"
                          >
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Status
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-status" class="check" />
                              <label for="col-status" class="checktoggle"></label>
                            </div>
                          </div>
                          <div class="d-flex align-items-center justify-content-between">
                            <p class="mb-0 d-flex align-items-center">
                              <i class="ti ti-grip-vertical me-2"></i>Action
                            </p>
                            <div class="status-toggle">
                              <input type="checkbox" id="col-action" class="check" />
                              <label for="col-action" class="checktoggle"></label>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- /Filter -->

                  <!-- Contact List -->
                  <div class="table-responsive custom-table">
                    <a-table
                      class="table dataTable no-footer"
                      :columns="columns"
                      :data-source="data"
                      :row-selection="rowSelection"
                    >
                      <template #bodyCell="{ column, record }">
                        <template v-if="column.key === 'Star'">
                          <div class="set-star rating-select">
                            <i class="fa fa-star"></i>
                          </div>
                        </template>
                        <template v-else-if="column.key === 'Language'">
                          <h2 class="d-flex align-items-center">
                            <a
                              href="javascript:void(0);"
                              class="avatar avatar-sm border me-2"
                              ><img
                                class="w-auto h-auto"
                                :src="require(`@/assets/img/icons/${record.Image}`)"
                                alt="User Image" /></a
                            ><a href="javascript:void(0);">{{ record.Language }}</a>
                          </h2>
                        </template>
                        <template v-else-if="column.key === 'RTL'">
                          <div class="status-toggle">
                            <input
                              type="checkbox"
                              :id="record.Id"
                              class="check"
                              undefined=""
                            /><label :for="record.For" class="checktoggle"
                              >/label&gt;</label
                            >
                          </div>
                        </template>
                        <template v-else-if="column.key === 'Progress'">
                          <div class="pipeline-progress d-flex align-items-center">
                            <div class="progress">
                              <div :class="record.Progressclass" role="progressbar"></div>
                            </div>
                            <span>{{ record.Progress }}</span>
                          </div>
                        </template>
                        <template v-else-if="column.key === 'Status'">
                          <span class="badge badge-pill badge-status bg-success">{{
                            record.Status
                          }}</span>
                        </template>
                        <template v-else-if="column.key === 'action'">
                          <div class="d-flex align-items-center">
                            <ul class="lang-type">
                              <li>
                                <router-link to="/website-settings/language-web"
                                  >Web</router-link
                                >
                              </li>

                              <li><a href="javascript:void(0);">App</a></li>
                              <li><a href="javascript:void(0);">Admin</a></li>
                            </ul>
                            <div class="dropdown table-action">
                              <a
                                href="#"
                                class="action-icon"
                                data-bs-toggle="dropdown"
                                aria-expanded="false"
                                ><i class="fa fa-ellipsis-v"></i
                              ></a>
                              <div class="dropdown-menu dropdown-menu-right">
                                <a
                                  class="dropdown-item"
                                  href="#"
                                  data-bs-toggle="modal"
                                  data-bs-target="#edit_translation"
                                  ><i class="ti ti-edit text-blue"></i> Edit</a
                                ><a
                                  class="dropdown-item"
                                  href="#"
                                  data-bs-toggle="modal"
                                  data-bs-target="#delete_translation"
                                  ><i class="ti ti-trash text-danger"></i> Delete</a
                                >
                              </div>
                            </div>
                          </div>
                        </template>
                      </template>
                    </a-table>
                  </div>
                  <div class="row align-items-center">
                    <div class="col-md-6">
                      <div class="datatable-length"></div>
                    </div>
                    <div class="col-md-6">
                      <div class="datatable-paginate"></div>
                    </div>
                  </div>
                  <!-- /Contact List -->
                </div>
              </div>
              <!-- /Custom Fields -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <language-settings-modal></language-settings-modal>
</template>
<script>
const columns = [
  {
    title: "",
    dataIndex: "",
    sorter: false,
  },
  {
    title: "",
    dataIndex: "",
    key: "Star",
    sorter: false,
  },
  {
    title: "Language",
    dataIndex: "Language",
    key: "Language",
    sorter: {
      compare: (a, b) => {
        a = a.Language.toLowerCase();
        b = b.Language.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Code",
    dataIndex: "Code",
    sorter: {
      compare: (a, b) => {
        a = a.Code.toLowerCase();
        b = b.Code.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "RTL",
    dataIndex: "RTL",
    key: "RTL",
    sorter: {
      compare: (a, b) => {
        a = a.RTL.toLowerCase();
        b = b.RTL.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Total",
    dataIndex: "Total",
    sorter: {
      compare: (a, b) => {
        a = a.Total.toLowerCase();
        b = b.Total.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Done",
    dataIndex: "Done",
    sorter: {
      compare: (a, b) => {
        a = a.Done.toLowerCase();
        b = b.Done.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Progress",
    dataIndex: "Progress",
    key: "Progress",
    sorter: {
      compare: (a, b) => {
        a = a.Progress.toLowerCase();
        b = b.Progress.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Status",
    dataIndex: "Status",
    key: "Status",
    sorter: {
      compare: (a, b) => {
        a = a.Status.toLowerCase();
        b = b.Status.toLowerCase();
        return a > b ? -1 : b > a ? 1 : 0;
      },
    },
  },
  {
    title: "Action",
    key: "action",
    sorter: true,
  },
];
const data = [
  {
    key: 1,
    Language: "English",
    Image: "flag-01.svg",
    Code: "en",
    Total: "3481",
    Done: "2861",
    For: "English",
    Id: "English",
    Progress: "80%",
    Status: "Active",
    Statusclass: "badge badge-pill badge-status bg-success",
    Progressclass: "progress-bar progress-bar-warning",
  },
  {
    key: 2,
    Language: "Arabic",
    Image: "flag-02.svg",
    Code: "ar",
    Total: "4815",
    Done: "4815",
    For: "Arabic",
    Id: "Arabic",
    Progress: "100%",
    Status: "Active",
    Statusclass: "badge badge-pill badge-status bg-success",
    Progressclass: "progress-bar progress-bar-success",
  },
  {
    key: 3,
    Language: "Chinese",
    Image: "flag-01.svg",
    Code: "zh",
    Total: "2590",
    Done: "250",
    For: "Chinese",
    Id: "Chinese",
    Progress: "5%",
    Status: "Active",
    Statusclass: "badge badge-pill badge-status bg-success",
    Progressclass: "progress-bar progress-bar-danger",
  },
  {
    key: 4,
    Language: "Hindi",
    Image: "flag-01.svg",
    Code: "hi",
    Total: "1892",
    Done: "387",
    For: "Hindi",
    Id: "Hindi",
    Progress: "40%",
    Status: "Active",
    Statusclass: "badge badge-pill badge-status bg-success",
    Progressclass: "progress-bar progress-bar-info",
  },
];
const rowSelection = {
  onChange: () => {},
  onSelect: () => {},
  onSelectAll: () => {},
};
export default {
  data() {
    return {
      title: "Settings",
      data,
      columns,
      rowSelection,
    };
  },
};
</script>

// angular/angular/src/app/feature-module/settings/website-settings/language-settings/language-settings.component.ts
import { Component } from '@angular/core';
import { Sort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { Router } from '@angular/router';
import { routes } from '../../../../../shared/routes/routes';
import { DataService } from '../../../../../shared/data/data.service';
import {
  apiResultFormat,
  languageSetting,
} from '../../../../../shared/model/pages.model';
import {
  PaginationService,
  tablePageSize,
  pageSelection,
} from '../../../../../shared/shared.index';
interface data {
  value: string;
}

@Component({
    selector: 'app-language-settings',
    templateUrl: './language-settings.component.html',
    styleUrl: './language-settings.component.scss',
    standalone: false
})
export class LanguageSettingsComponent {
  initChecked = false;
  public routes = routes;
  public selectedValue1 = '';
  // pagination variables
  public tableData: languageSetting[] = [];
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<languageSetting>;
  public searchDataValue = '';
  public actualData: languageSetting[] = [];
  public tableDataCopy: languageSetting[] = [];
  //** / pagination variables

  constructor(
    private data: DataService,
    private pagination: PaginationService,
    private router: Router,
  ) {
    this.data.getLanguageSetting().subscribe((apiRes: apiResultFormat) => {
      this.actualData = apiRes.data;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.languageSettings) {
          this.getTableData({ skip: res.skip, limit: res.limit });
          this.pageSize = res.pageSize;
        }
      });
    });
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getLanguageSetting().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.tableDataCopy = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: languageSetting, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.sNo = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
          this.tableDataCopy.push(res);
        }
      });
      this.dataSource = new MatTableDataSource<languageSetting>(this.actualData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        tableDataCopy: this.tableDataCopy,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }


  
  selectedList1: data[] = [
    { value: 'Select Language' },
    { value: 'English' },
    { value: 'Arabic' },
    { value: 'Chinese' },
  ];
  public searchData(value: string): void {
    if (value == '') {
      this.tableData = this.tableDataCopy;
    } else {
      this.dataSource.filter = value.trim().toLowerCase();
      this.tableData = this.dataSource.filteredData;
    }
  }
  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
}

<!-- Page Wrapper -->
<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">

        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h4 class="page-title">Settings</h4>
            </div>
            <div class="col-4 text-end">
              <div class="head-icons">
                <a [routerLink] = "routes.languageSettings" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-original-title="Refresh" matTooltip="Refresh"><i class="ti ti-refresh-dot"></i></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <!-- Settings Menu -->
        <div class="card">
          <div class="card-body pb-0 pt-2">
            <ul class="nav nav-tabs nav-tabs-bottom">
              <li class="nav-item me-3">
                <a [routerLink] = "routes.generalSettings" class="nav-link px-0">
                  <i class="ti ti-settings-cog me-2"></i>General Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.companySettings" class="nav-link px-0 active">
                  <i class="ti ti-world-cog me-2"></i>Website Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.invoiceSettings" class="nav-link px-0">
                  <i class="ti ti-apps me-2"></i>App Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.emailSettings" class="nav-link px-0">
                  <i class="ti ti-device-laptop me-2"></i>System Settings
                </a>
              </li>
              <li class="nav-item me-3">
                <a [routerLink] = "routes.paymentGatewaySettings" class="nav-link px-0">
                  <i class="ti ti-moneybag me-2"></i>Financial Settings
                </a>
              </li>
              <li class="nav-item">
                <a [routerLink] = "routes.storageSettings" class="nav-link px-0">
                  <i class="ti ti-flag-cog me-2"></i>Other Settings
                </a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /Settings Menu -->

        <div class="row">
          <div class="col-xl-3 col-lg-12 theiaStickySidebar">
            <div class="stickybar">
              <!-- Settings Sidebar -->
              <div class="card">
                <div class="card-body">
                  <div class="settings-sidebar">
                    <h4 class="fw-semibold mb-3">Website Settings</h4>
                    <div class="list-group list-group-flush settings-sidebar">
                      <a [routerLink] = "routes.companySettings" class="fw-medium">Company Settings</a>
                      <a [routerLink] = "routes.localizationSettings" class="fw-medium">Localization</a>
                      <a [routerLink] = "routes.prefixes" class="fw-medium">Prefixes</a>
                      <a [routerLink] = "routes.preference" class="fw-medium">Preference</a>
                      <a [routerLink] = "routes.appearance" class="fw-medium">Appearance</a>
                      <a [routerLink] = "routes.languageSettings"class="fw-medium active">Language</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Settings Sidebar -->
            </div>
          </div>

          <div class="col-xl-9 col-lg-12">

            <!-- Custom Fields -->
            <div class="card">
              <div class="card-body">
                <h4 class="fw-semibold mb-3">Language</h4>
                <!-- Search -->
               
                  <div class="row">
                    <div class="col-xl-3 col-md-3 col-lg-5">
                      <div class="form-wrap icon-form">
                        <span class="form-icon"><i class="ti ti-search"></i></span>
                        <input type="text" class="form-control" placeholder="Search Language">
                      </div>
                    </div>
                    <div class="col-xl-9 col-md-9 col-lg-12">
                      <div class="d-flex align-items-center flex-wrap justify-content-sm-end">
                        <div class="dropdown me-2 mb-3">
                          <a href="javascript:void(0);" class="dropdown-toggle"  data-bs-toggle="dropdown"><i class="ti ti-package-export me-2"></i>Export</a>
                          <div class="dropdown-menu  dropdown-menu-end">
                            <ul>
                              <li>
                                <a href="javascript:void(0);" class="dropdown-item"><i class="ti ti-file-type-pdf text-danger me-1"></i>Export as PDF</a>
                              </li>
                              <li>
                                <a href="javascript:void(0);" class="dropdown-item"><i class="ti ti-file-type-xls text-green me-1"></i>Export as Excel </a>
                              </li>
                            </ul>
                          </div>
                        </div>	
                        <a href="javascript:void(0);" class="btn btn-primary me-2 mb-3" data-bs-toggle="modal" data-bs-target="#import_sample"><i class="ti ti-download me-2"></i>Import Sample</a>	
                        <a href="javascript:void(0);" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#add_translation"><i class="ti ti-square-rounded-plus me-2"></i>Add Translation</a>
                      </div>
                    </div>
                  </div>
                
                <!-- /Search -->

                <!-- Filter -->
										<div class="d-flex align-items-center justify-content-between flex-wrap mb-2">											
											<div class="dropdown mb-3">
												<a href="javascript:void(0);" class="dropdown-toggle"  data-bs-toggle="dropdown"><i class="ti ti-sort-ascending-2 me-2"></i>Sort </a>
												<div class="dropdown-menu  dropdown-menu-start">
													<ul>
														<li>
															<a href="javascript:void(0);" class="dropdown-item">
																<i class="ti ti-circle-chevron-right me-1"></i>Ascending
															</a>
														</li>
														<li>
															<a href="javascript:void(0);" class="dropdown-item">
																<i class="ti ti-circle-chevron-right me-1"></i>Descending
															</a>
														</li>
														<li>
															<a href="javascript:void(0);" class="dropdown-item">
																<i class="ti ti-circle-chevron-right me-1"></i>Recently Viewed
															</a>
														</li>
														<li>
															<a href="javascript:void(0);" class="dropdown-item">
																<i class="ti ti-circle-chevron-right me-1"></i>Recently Added
															</a>
														</li>
													</ul>
												</div>
											</div>
											<div class="dropdown mb-3">
												<a href="javascript:void(0);" class="btn bg-soft-purple text-purple"  data-bs-toggle="dropdown"  data-bs-auto-close="outside"><i class="ti ti-columns-3 me-2"></i>Manage Columns</a>
												<div class="dropdown-menu  dropdown-menu-md-end dropdown-md p-3">
													<h4 class="mb-2 fw-semibold">Want to manage datatables?</h4>
													<p class="mb-3">Please drag and drop your column to reorder your table and enable see option as you want.</p>
													<div class="border-top pt-3">
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Language</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-name" class="check">
																<label for="col-name" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Code</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-phone" class="check">
																<label for="col-phone" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>RTL</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-email" class="check">
																<label for="col-email" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Total</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-tag" class="check">
																<label for="col-tag" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Done</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-loc" class="check">
																<label for="col-loc" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Progress</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-rate" class="check">
																<label for="col-rate" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Status</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-owner" class="check">
																<label for="col-owner" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Contact</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-contact" class="check" checked="">
																<label for="col-contact" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between mb-3">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Status</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-status" class="check">
																<label for="col-status" class="checktoggle"></label>
															</div>
														</div>
														<div class="d-flex align-items-center justify-content-between">
															<p class="mb-0 d-flex align-items-center"><i class="ti ti-grip-vertical me-2"></i>Action</p>
															<div class="status-toggle">
																<input type="checkbox" id="col-action" class="check">
																<label for="col-action" class="checktoggle"></label>
															</div>
														</div>
													</div>
												</div>
											</div>											
										</div>
										<!-- /Filter -->

                <!-- Contact List -->
                <div class="table-responsive custom-table">
                  <table class="table" id="language-list" matSort (matSortChange)="sortData($event)">
                    <thead>
                      <tr>
                        <th class="no-sort">
                           <label class="checkboxs" (click)="selectAll(initChecked)"  (keydown.enter)="selectAll(initChecked)" tabindex="0">
                            <input type="checkbox" id="select-all" [(ngModel)]="initChecked">
                            <span class="checkmarks"></span>
                          </label>
                        </th>
                        <th></th>
                        <th mat-sort-header="language">Language</th>
                        <th mat-sort-header="code">Code</th>
                        <th mat-sort-header="rtl">RTL</th>
                        <th mat-sort-header="total">Total</th>
                        <th mat-sort-header="done">Done</th>
                        <th mat-sort-header="progress">Progress</th>
                        <th mat-sort-header="status">Status</th>
                        <th class="no-sort">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      @for (data of tableData; track data; let i = $index) {
                      <tr>
                        <td>
                          <label class="checkboxs">
                            <input type="checkbox" [(ngModel)]="data.isSelected">
                            <span class="checkmarks"></span>
                          </label>
                        </td>
                        <td>
                          <div class="set-star rating-select"><i class="fa fa-star"></i></div>
                        </td>
                        <td>
                          <div class="language-name d-flex align-items-center">
                            <img [src]="data.img" class="me-2" alt="">
                            {{data.language}}
                          </div>
                        </td>
                        <td>
                          {{data.code}}
                        </td>
                        <td>
                          <div class="status-toggle modal-status d-flex justify-content-between align-items-center">
                            <input type="checkbox" id="user1" class="check" checked="">
                            <label for="user1" class="checktoggle"></label>
                          </div>
                        </td>
                        <td> {{data.total}}</td>
                        <td> {{data.done}}</td>
                        <td>
                          <div class="pipeline-progress d-flex align-items-center">
                            <div class="progress">
                              <div class="progress-bar"
                                [ngClass]="{'progress-bar-warning': data.progress === '80%', 'progress-bar-success': data.progress === '100%', 'progress-bar-danger': data.progress === '5%', 'progress-bar-info': data.progress === '40%'}"
                                role="progressbar"></div>
                            </div><span>{{data.progress}}</span>
                          </div>
                        </td>
                        <td><span class="badge badge-pill badge-status"
                            [ngClass]="{'bg-success': data.status === 'Active', 'bg-danger': data.status === 'Inactive'}">{{data.status}}</span>
                        </td>
                        <td>
                          <div class="d-flex align-items-center">
                            <ul class="lang-type">
                              <li><a [routerLink] = "routes.languageSettingsweb">Web</a></li>
                              <li><a href="javascript:void(0);">App</a></li>
                              <li><a href="javascript:void(0);">Admin</a></li>
                            </ul>
                            <div class="dropdown table-action"><a href="javascript:void(0);" class="action-icon "
                                data-bs-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                              <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item"
                                  href="javascript:void(0);" data-bs-toggle="modal"
                                  data-bs-target="#edit_translation"><i class="ti ti-edit text-blue"></i> Edit</a><a
                                  class="dropdown-item" href="javascript:void(0);" data-bs-toggle="modal"
                                  data-bs-target="#delete_translation"><i class="ti ti-trash text-danger"></i>
                                  Delete</a></div>
                            </div>
                          </div>
                        </td>
                      </tr>
                      }

                    </tbody>
                  </table>
                </div>
                <app-custom-pagination></app-custom-pagination>
                <div class="row align-items-center">
                  <div class="col-md-6">
                    <div class="datatable-length"></div>
                  </div>
                  <div class="col-md-6">
                    <div class="datatable-paginate"></div>
                  </div>
                </div>
                <!-- /Contact List -->

              </div>
            </div>
            <!-- /Custom Fields -->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Page Wrapper -->

<!-- Add Translation -->
<div class="modal  fade" id="add_translation" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Translation</h5>
        <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <form>
      <div class="modal-body">
        
          <div class="mb-3">
            <label class="form-label" for="tag">Language <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Code <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Status</label>
            <div class="radio-wrap">
              <div class="d-flex flex-wrap">
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="add-active" name="status" checked="">
                  <label for="add-active">Active</label>
                </div>
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="add-inactive" name="status">
                  <label for="add-inactive">Inactive</label>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
       
      </div>
    </form>
    </div>
  </div>
</div>
<!-- /Add Translation -->

<!-- Edit Translation -->
<div class="modal fade" id="edit_translation" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Translation</h5>
        <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <form>
      <div class="modal-body">
        
          <div class="mb-3">
            <label class="form-label" for="tag">Language <span class="text-danger">*</span></label>
            <input type="text" class="form-control" value="English">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Code <span class="text-danger">*</span></label>
            <input type="text" class="form-control" value="en">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Status</label>
            <div class="radio-wrap">
              <div class="d-flex flex-wrap">
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="edit-active" name="status" checked="">
                  <label for="edit-active">Active</label>
                </div>
                <div class="radio-btn">
                  <input type="radio" class="status-radio" id="edit-inactive" name="status">
                  <label for="edit-inactive">Inactive</label>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
       
      </div>
    </form>
    </div>
  </div>
</div>
<!-- /Edit Translation -->

<!-- Import Sample -->
<div class="modal custom-modal fade" id="import_sample" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Import Sample</h5>
        <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <form>
      <div class="modal-body">
        
          <div class="mb-3">
            <label class="form-label" for="tag">File <span class="text-danger">*</span></label>
            <mat-select class="select custom-mat-select" placeholder="Inventory">
              <mat-option value="inventory">Inventory</mat-option>
              <mat-option value="expense">Expense</mat-option>
              <mat-option value="product">Product</mat-option>
            </mat-select>
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Language <span class="text-danger">*</span></label>
            <mat-select class="select custom-mat-select" placeholder="English">
              <mat-option value="Choose">Choose</mat-option>
                          <mat-option value="English">English</mat-option>
                          <mat-option value="Arabic">Arabic</mat-option>
                          <mat-option value="German">French</mat-option>
                          <mat-option value="German">German</mat-option>
            </mat-select>
          </div>
          <div class="mb-3">
            <div class="drag-attach">
              <input type="file">
              <div class="img-upload">
                <i class="ti ti-file-broken"></i>Upload File
              </div>
            </div>
          </div>
          <div class="mb-0">
            <label class="col-form-label" for="reason">Uploaded Files</label>
            <div class="upload-file">
              <h6>Projectneonals teyys.xls</h6>
              <p>4.25 MB</p>
              <div class="progress">
                <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25"
                  aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <p class="black-text">45%</p>
            </div>
            <div class="upload-file upload-list">
              <div>
                <h6>tes.txt</h6>
                <p>4.25 MB</p>
              </div>
              <a href="javascript:void(0);" class="text-danger"><i class="ti ti-trash-x"></i></a>
            </div>
          </div>
          <div class="modal-footer">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        
      </div>
    </form>
    </div>
  </div>
</div>
<!-- /Import Sample -->

<!-- Delete Translation -->
<div class="modal custom-modal fade" id="delete_translation" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header border-0 m-0 justify-content-end">
        <button class="btn-close" data-bs-dismiss="modal" aria-label="Close">
          <i class="ti ti-x"></i>
        </button>
      </div>
      <div class="modal-body">
        <form>
          <div class="success-message text-center">
            <div class="success-popup-icon">
              <i class="ti ti-trash-x"></i>
            </div>
            <h3>Remove Translation?</h3>
            <p class="del-info">Are you sure you want to remove it.</p>
            <div class="col-lg-12 text-center modal-btn">
              <a href="javascript:void(0);" class="btn btn-light" data-bs-dismiss="modal">Cancel</a>
              <button type="submit" class="btn btn-danger">Yes, Delete it</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- /Delete Translation -->
