// angular/angular/src/app/feature-module/crmsetting/contact-stage/contact-stage.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';
import { apiResultFormat, contactStage } from '../../../../shared/model/pages.model';
import { MatTableDataSource } from '@angular/material/table';
import { DataService } from '../../../../shared/data/data.service';
import { PaginationService, pageSelection, tablePageSize } from '../../../../shared/custom-pagination/pagination.service';
import { Router } from '@angular/router';
import { Sort } from '@angular/material/sort';

@Component({
    selector: 'app-contact-stage',
    templateUrl: './contact-stage.component.html',
    styleUrl: './contact-stage.component.scss',
    standalone: false
})
export class ContactStageComponent {
  public routes = routes;
  // pagination variables
  public tableData: contactStage[] = [];
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<contactStage>;
  public searchDataValue = '';
  public tableDataCopy: contactStage[] = [];
  public actualData: contactStage[] = [];
  //** pagination variables
  
  public sidebarPopup = false;
  public sidebarPopup2 = false;

  initChecked = false;

 
 

  constructor(
    private data: DataService,
    private pagination: PaginationService,
    private router: Router
  ) {
    this.data.getContactStage().subscribe((apiRes: apiResultFormat) => {
      this.actualData = apiRes.data;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.contactStage) {
          this.getTableData({ skip: res.skip, limit: res.limit });
          this.pageSize = res.pageSize;
        }
      });
    });
    
   
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getContactStage().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.tableDataCopy = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: contactStage, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.id = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
          this.tableDataCopy.push(res);
        }
      });
      this.dataSource = new MatTableDataSource<contactStage>(this.actualData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        tableDataCopy: this.tableDataCopy,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public searchData(value: string): void {
    if (value == '') {
      this.tableData = this.tableDataCopy;
    } else {
      this.dataSource.filter = value.trim().toLowerCase();
      this.tableData = this.dataSource.filteredData;
    }
  }
  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
}

<!-- Page Wrapper -->
<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-sm-8">
              <h4 class="page-title">
                Contact Stages <span class="count-title">123</span>
              </h4>
            </div>
            <div class="col-sm-4 text-sm-end">
              <div class="head-icons">
                <a
                [routerLink] = "routes.contactStage"
                  data-bs-toggle="tooltip"
                  data-bs-placement="top"
                  data-bs-original-title="Refresh"
                  ><i class="ti ti-refresh-dot"></i
                ></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <div class="card">
          <div class="card-header">
            <!-- Search -->
            <div class="row align-items-center">
              <div class="col-sm-4">
                <div class="icon-form mb-3 mb-sm-0">
                  <span class="form-icon"><i class="ti ti-search"></i></span>
                  <input type="text" class="form-control" placeholder="Search Contact Stages">
                </div>							
              </div>		
              <div class="col-sm-8">					
                <div class="text-sm-end">
                  <a href="javascript:void(0);" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add_contact_stage"><i class="ti ti-square-rounded-plus me-2"></i>Add New Stages</a>
                </div>
              </div>
            </div>
            <!-- /Search -->
          </div>
          <div class="card-body">
            
            <!-- Contact Stage List -->
            <div class="table-responsive custom-table">
              <table class="table" id="contact-stage" matSort (matSortChange)="sortData($event)">
                <thead class="thead-light">
                  <tr>
                    <th class="no-sort">
                       <label class="checkboxs" (click)="selectAll(initChecked)"  (keydown.enter)="selectAll(initChecked)" tabindex="0"
                        ><input type="checkbox" [(ngModel)]="initChecked" /><span
                          class="checkmarks"
                        ></span
                      ></label>
                    </th>
                    <th mat-sort-header="title">Title</th>
                    <th mat-sort-header="Created">Created at</th>
                    <th mat-sort-header="Status">Status</th>
                    <th mat-sort-header="Action">Action</th>
                  </tr>
                </thead>
                <tbody>
                  @for (data of tableData; track data) {
                  <tr class="odd">
                    <td class="sorting_1">
                      <label class="checkboxs"
                        ><input type="checkbox" [(ngModel)]="data.isSelected"/><span
                          class="checkmarks"
                        ></span
                      ></label>
                    </td>
                    <td>
                      <span class="title-name">{{ data.title }}</span>
                    </td>
                    <td>{{ data.created_date }}</td>
                    <td>
                       <span
                        class="badge badge-pill badge-status"
                        [ngClass]="{
                          'bg-success': data.status === 'Active',
                          'bg-danger': data.status === 'Inactive'
                        }"
                        >{{ data.status }}</span
                      > 
                    </td>
                    <td>
                      <div class="dropdown table-action">
                        <a
                          href="javascript:void(0);"
                          class="action-icon"
                          data-bs-toggle="dropdown"
                          aria-expanded="false"
                          ><i class="fa fa-ellipsis-v"></i
                        ></a>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="modal"
                            data-bs-target="#edit_contact_stage"
                            ><i class="ti ti-edit text-blue"></i> Edit</a
                          ><a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="modal"
                            data-bs-target="#delete_contact_stage"
                            ><i class="ti ti-trash text-danger"></i> Delete</a
                          >
                        </div>
                      </div>
                    </td>
                  </tr>
                  }
                </tbody>
              </table>
            </div>
            <app-custom-pagination></app-custom-pagination>
            <div class="row align-items-center">
              <div class="col-md-6">
                <div class="datatable-length"></div>
              </div>
              <div class="col-md-6">
                <div class="datatable-paginate"></div>
              </div>
            </div>
            <!-- /Contact Stage List -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Page Wrapper -->

<!-- Add New Contact Stage -->
<div class="modal fade" id="add_contact_stage" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add New Contact Stage</h5>
        <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">	
          <i class="ti ti-x"></i>
        </button>
      </div>
      <form >
        <div class="modal-body">
          <div class="mb-3">
            <label class="col-form-label" for="Stage">Contact Stage <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-0">
            <label class="col-form-label"  for="Status">Status</label>
            <div class="d-flex align-items-center">
              <div class="me-2">
                <input type="radio" class="status-radio" id="add-active" name="status" checked="">
                <label for="add-active" >Active</label>
              </div>
              <div>
                <input type="radio" class="status-radio" id="add-inactive" name="status">
                <label for="add-inactive">Inactive</label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="d-flex align-items-center justify-content-end m-0">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Create</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /Add New Contact Stage -->

<!-- Edit Contact Stage -->
<div class="modal fade" id="edit_contact_stage" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Contact Stage</h5>
        <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">	
          <i class="ti ti-x"></i>
        </button>
      </div>
      <form >
        <div class="modal-body">
          <div class="mb-3">
            <label class="col-form-label" for="Contact">Contact Stage <span class="text-danger">*</span></label>
            <input type="text" class="form-control" value="Contacted">
          </div>
          <div class="mb-0">
            <label class="col-form-label" for="Status">Status</label>
            <div class="d-flex flex-wrap radio-wrap">
              <div class="radio-btn">
                <input type="radio" class="status-radio" id="edit-active" name="status" checked="">
                <label for="edit-active">Active</label>
              </div>
              <div class="radio-btn">
                <input type="radio" class="status-radio" id="edit-inactive" name="status">
                <label for="edit-inactive">Inactive</label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <div class="d-flex align-items-center justify-content-end m-0">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save Changes</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /Edit Contact Stage -->

<!-- Delete Contact Stage -->
<div class="modal fade" id="delete_contact_stage" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body">
        <div class="text-center">
          <div class="avatar avatar-xl bg-danger-light rounded-circle mb-3">
            <i class="ti ti-trash-x fs-36 text-danger"></i>
          </div>
          <h4 class="mb-2">Remove Contact Stage?</h4>
          <p class="mb-0">AAre you sure you want to remove it.</p>
          <div class="d-flex align-items-center justify-content-center mt-4">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <a [routerLink]="routes.contactStage" class="btn btn-danger">Yes, Delete it</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Delete Contact Stage -->

// nextjs/nextjs/template/src/components/crmSetting/contactStage.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import ContactStageModal from "../../core/modals/contactStageModal";
import Table from "../../core/common/dataTable/index";
import CollapseHeader from "../../core/common/collapse-header";
import { all_routes } from "@/data/all_routes";
import { contactStageData } from "@/data/json/contactStage_data";
import Link from 'next/link';

const ContactStage = () => {
  const route = all_routes;

  const data = contactStageData;

  const columns = [
    {
      title: "Title",
      dataIndex: "title",
      sorter: (a: any, b: any) => a.title.length - b.title.length,
    },

    {
      title: "Created At",
      dataIndex: "created_date",
      sorter: (a: any, b: any) => a.created_date.length - b.created_date.length,
    },
    {
      title: "Status",
      dataIndex: "status",
      render: (text: any, record: any) => (
        <span
          className={`badge badge-pill badge-status ${
            record?.status == "" ? "bg-success" : "bg-danger"
          }`}
        >
          {record?.status}
        </span>
      ),
      sorter: (a: any, b: any) => a.status - b.status.length,
    },
    {
      title: "Action",
      render: () => (
        <div className="dropdown table-action">
          <Link
            href="#"
            className="action-icon "
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i className="fa fa-ellipsis-v" />
          </Link>
          <div className="dropdown-menu dropdown-menu-right">
            <Link
              className="dropdown-item"
              href="#"
              data-bs-toggle="modal"
              data-bs-target="#edit_contact_stage"
            >
              <i className="ti ti-edit text-blue" /> Edit
            </Link>
            <Link
              className="dropdown-item"
              href="#"
              data-bs-toggle="modal"
              data-bs-target="#delete_contact_stage"
            >
              <i className="ti ti-trash text-danger" /> Delete
            </Link>
          </div>
        </div>
      ),
    },
  ];

  return (
    <>
  {/* Page Wrapper */}
  <div className="page-wrapper">
    <div className="content">
      <div className="row">
        <div className="col-md-12">
          {/* Page Header */}
          <div className="page-header">
            <div className="row align-items-center">
              <div className="col-sm-8">
                <h4 className="page-title">
                  Contact Stages <span className="count-title">123</span>
                </h4>
              </div>
              <div className="col-sm-4 text-sm-end">
                <div className="head-icons">
                 <CollapseHeader/>
                </div>
              </div>
            </div>
          </div>
          {/* /Page Header */}
          <div className="card">
            <div className="card-header">
              {/* Search */}
              <div className="row align-items-center">
                <div className="col-sm-4">
                  <div className="icon-form mb-3 mb-sm-0">
                    <span className="form-icon">
                      <i className="ti ti-search" />
                    </span>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="Search Contact Stages"
                    />
                  </div>
                </div>
                <div className="col-sm-8">
                  <div className="text-sm-end">
                    <Link
                      href="#"
                      className="btn btn-primary"
                      data-bs-toggle="modal"
                      data-bs-target="#add_contact_stage"
                    >
                      <i className="ti ti-square-rounded-plus me-2" />
                      Add New Stages
                    </Link>
                  </div>
                </div>
              </div>
              {/* /Search */}
            </div>
            <div className="card-body">
              {/* Contact Stage List */}
              <div className="table-responsive custom-table">
              <Table columns={columns} dataSource={data} />
              </div>
              <div className="row align-items-center">
                <div className="col-md-6">
                  <div className="datatable-length" />
                </div>
                <div className="col-md-6">
                  <div className="datatable-paginate" />
                </div>
              </div>
              {/* /Contact Stage List */}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {/* /Page Wrapper */}
 <ContactStageModal/>
</>

  );
};

export default ContactStage;
