// angular/angular/src/app/feature-module/crmsetting/lost-reason/lost-reason.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../shared/routes/routes';
import { apiResultFormat, lostReason } from '../../../../shared/model/pages.model';
import { MatTableDataSource } from '@angular/material/table';
import { DataService } from '../../../../shared/data/data.service';
import { PaginationService, pageSelection, tablePageSize } from '../../../../shared/custom-pagination/pagination.service';
import { Router } from '@angular/router';
import { Sort } from '@angular/material/sort';

@Component({
    selector: 'app-lost-reason',
    templateUrl: './lost-reason.component.html',
    styleUrl: './lost-reason.component.scss',
    standalone: false
})
export class LostReasonComponent {
  public routes = routes;
  // pagination variables
  public tableData: lostReason[] = [];
  public pageSize = 10;
  public serialNumberArray: number[] = [];
  public totalData = 0;
  showFilter = false;
  dataSource!: MatTableDataSource<lostReason>;
  public searchDataValue = '';
  public tableDataCopy: lostReason[] = [];
  public actualData: lostReason[] = [];
  //** pagination variables
  
  public sidebarPopup = false;
  public sidebarPopup2 = false;

  initChecked = false;

 
 

  constructor(
    private data: DataService,
    private pagination: PaginationService,
    private router: Router
  ) {
    this.data.getLostReason().subscribe((apiRes: apiResultFormat) => {
      this.actualData = apiRes.data;
      this.pagination.tablePageSize.subscribe((res: tablePageSize) => {
        if (this.router.url == this.routes.LostReason) {
          this.getTableData({ skip: res.skip, limit: res.limit });
          this.pageSize = res.pageSize;
        }
      });
    });
    
   
  }

  private getTableData(pageOption: pageSelection): void {
    this.data.getLostReason().subscribe((apiRes: apiResultFormat) => {
      this.tableData = [];
      this.tableDataCopy = [];
      this.serialNumberArray = [];
      this.totalData = apiRes.totalData;
      apiRes.data.map((res: lostReason, index: number) => {
        const serialNumber = index + 1;
        if (index >= pageOption.skip && serialNumber <= pageOption.limit) {
          res.id = serialNumber;
          this.tableData.push(res);
          this.serialNumberArray.push(serialNumber);
          this.tableDataCopy.push(res);
        }
      });
      this.dataSource = new MatTableDataSource<lostReason>(this.actualData);
      this.pagination.calculatePageSize.next({
        totalData: this.totalData,
        pageSize: this.pageSize,
        tableData: this.tableData,
        tableDataCopy: this.tableDataCopy,
        serialNumberArray: this.serialNumberArray,
      });
    });
  }

  public sortData(sort: Sort) {
    const data = this.tableData.slice();
    if (!sort.active || sort.direction === '') {
      this.tableData = data;
    } else {
      this.tableData = data.sort((a, b) => {
        const aValue = (a as never)[sort.active];
        const bValue = (b as never)[sort.active];
        return (aValue < bValue ? -1 : 1) * (sort.direction === 'asc' ? 1 : -1);
      });
    }
  }
  public searchData(value: string): void {
    if (value == '') {
      this.tableData = this.tableDataCopy;
    } else {
      this.dataSource.filter = value.trim().toLowerCase();
      this.tableData = this.dataSource.filteredData;
    }
  }
 
  selectAll(initChecked: boolean) {
    if (!initChecked) {
      this.tableData.forEach((f) => {
        f.isSelected = true;
      });
    } else {
      this.tableData.forEach((f) => {
        f.isSelected = false;
      });
    }
  }
 
}

<!-- Page Wrapper -->
<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">
        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-sm-8">
              <h4 class="page-title">
                Lost Reason <span class="count-title">123</span>
              </h4>
            </div>
            <div class="col-sm-4 text-sm-end">
              <div class="head-icons">
                <a
                [routerLink] = "routes.lostReason"
                  data-bs-toggle="tooltip"
                  data-bs-placement="top"
                  data-bs-original-title="Refresh"
                  ><i class="ti ti-refresh-dot"></i
                ></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <div class="card">
          <div class="card-header">
            <!-- Search -->
            <div class="row align-items-center">
              <div class="col-sm-4">
                <div class="icon-form mb-3 mb-sm-0">
                  <span class="form-icon"><i class="ti ti-search"></i></span>
                  <input type="text" class="form-control" placeholder="Search Lost Reason">
                </div>							
              </div>		
              <div class="col-sm-8">					
                <div class="text-sm-end">
                  <a href="javascript:void(0);" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add_reason"><i class="ti ti-square-rounded-plus me-2"></i>Add New Reason</a>
                </div>
              </div>
            </div>
            <!-- /Search -->
          </div>
          <div class="card-body">
            

            <!-- Reason List -->
            <div class="table-responsive custom-table">
              <table class="table" id="reason-list" matSort (matSortChange)="sortData($event)">
                <thead class="thead-light">
                  <tr>
                    <th class="no-sort">
                       <label class="checkboxs" (click)="selectAll(initChecked)"  (keydown.enter)="selectAll(initChecked)" tabindex="0"
                        ><input type="checkbox"  [(ngModel)]="initChecked" /><span
                          class="checkmarks"
                        ></span
                      ></label>
                    </th>
                    <th mat-sort-header="title">Title</th>
                    <th mat-sort-header="Created">Created at</th>
                    <th mat-sort-header="Status">Status</th>
                    <th mat-sort-header="Action">Action</th>
                  </tr>
                </thead>
                <tbody>
                  @for (data of tableData; track data) {
                  <tr class="odd">
                    <td class="sorting_1">
                      <label class="checkboxs"
                        ><input type="checkbox" [(ngModel)]="data.isSelected"  /><span
                          class="checkmarks"
                        ></span
                      ></label>
                    </td>
                    <td>
                      <span class="title-name">{{ data.title }}</span>
                    </td>
                    <td>{{ data.created_date }}</td>
                    <td>
                      <span
                        class="badge badge-pill badge-status"
                        [ngClass]="{
                          'bg-success': data.status === 'Active',
                          'bg-danger': data.status === 'Inactive'
                        }"
                        >{{ data.status }}</span
                      >
                    </td>
                    <td>
                      <div class="dropdown table-action">
                        <a
                          href="javascript:void(0);"
                          class="action-icon"
                          data-bs-toggle="dropdown"
                          aria-expanded="false"
                          ><i class="fa fa-ellipsis-v"></i
                        ></a>
                        <div class="dropdown-menu dropdown-menu-right">
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="modal"
                            data-bs-target="#edit_reason"
                            ><i class="ti ti-edit text-blue"></i> Edit</a
                          ><a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            data-bs-toggle="modal"
                            data-bs-target="#delete_reason"
                            ><i class="ti ti-trash text-danger"></i> Delete</a
                          >
                        </div>
                      </div>
                    </td>
                  </tr>
                  }
                </tbody>
              </table>
            </div>
            <app-custom-pagination></app-custom-pagination>
            <div class="row align-items-center">
              <div class="col-md-6">
                <div class="datatable-length"></div>
              </div>
              <div class="col-md-6">
                <div class="datatable-paginate"></div>
              </div>
            </div>
            <!-- /Reason List -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /Page Wrapper -->


		<!-- Add New Reason -->
		<div class="modal fade" id="add_reason" role="dialog">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Add New Reason</h5>
						<button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">	
							<i class="ti ti-x"></i>
						</button>
					</div>
					<form>
						<div class="modal-body">
							<div class="mb-3">
								<label class="col-form-label" for="reason">Reason <span class="text-danger">*</span></label>
								<input type="text" class="form-control">
							</div>
							<div class="mb-0">
								<label class="col-form-label" for="reason">Status</label>
								<div class="d-flex align-items-center">
									<div class="me-2">
										<input type="radio" class="status-radio" id="add-active" name="status" checked="">
										<label for="add-active">Active</label>
									</div>
									<div>
										<input type="radio" class="status-radio" id="add-inactive" name="status">
										<label for="add-inactive">Inactive</label>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<div class="d-flex align-items-center justify-content-end m-0">
								<a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
								<button type="submit" class="btn btn-primary">Create</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<!-- /Add New Reason -->

		<!-- Edit Reason -->
		<div class="modal fade" id="edit_reason" role="dialog">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title">Edit Reason</h5>
						<button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">	
							<i class="ti ti-x"></i>
						</button>
					</div>
					<form >
						<div class="modal-body">
							<div class="mb-3">
								<label class="col-form-label" for="reason">Reason <span class="text-danger">*</span></label>
								<input type="text" class="form-control" value="Client went silent">
							</div>
							<div class="mb-0">
								<label class="col-form-label" for="reason">Status</label>
								<div class="d-flex align-items-center">
									<div class="me-2">
										<input type="radio" class="status-radio" id="edit-active" name="status" checked="">
										<label for="edit-active">Active</label>
									</div>
									<div>
										<input type="radio" class="status-radio" id="edit-inactive" name="status">
										<label for="edit-inactive">Inactive</label>
									</div>
								</div>
							</div>
						</div>
						<div class="modal-footer">
							<div class="d-flex align-items-center justify-content-end m-0">
								<a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
								<button type="submit" class="btn btn-primary">Save Changes</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
		<!-- /Edit Reason -->

		<!-- Delete Reason -->
		<div class="modal fade" id="delete_reason" role="dialog">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-body">
						<div class="text-center">
							<div class="avatar avatar-xl bg-danger-light rounded-circle mb-3">
								<i class="ti ti-trash-x fs-36 text-danger"></i>
							</div>
							<h4 class="mb-2">Remove Reason?</h4>
							<p class="mb-0">AAre you sure you want to remove it.</p>
							<div class="d-flex align-items-center justify-content-center mt-4">
								<a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
								<a [routerLink]="routes.LostReason" class="btn btn-danger">Yes, Delete it</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /Delete Reason -->

// nextjs/nextjs/template/src/components/crmSetting/lostReason.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import Table from "../../core/common/dataTable/index";
import CollapseHeader from "../../core/common/collapse-header";
import Link from 'next/link';
import { lostReason } from "@/data/json/lostreason";

const LostReason = () => {

    const data = lostReason;
  
    const columns = [
      {
        title: "Title",
        dataIndex: "title",
        key: "title",
        sorter: true,
      },
      {
        title: "Created at",
        dataIndex: "created_date",
        key: "created_date",
        sorter: true,
      },
      {
        title: "Status",
        dataIndex: "status",
        render: (text: string) => (
          <div>
            {text === "Active" && (
              <span className="badge badge-pill badge-status bg-success">
                {text}
              </span>
            )}
  
            {text === "Inactive" && (
              <span className="badge badge-pill badge-status bg-danger">
                {text}
              </span>
            )}
          </div>
        ),
        sorter: true,
      },
      {
        title: "Action",
        dataIndex: "action",
        render: () => (
          <div className="dropdown table-action">
            <Link
              href="#"
              className="action-icon "
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <i className="fa fa-ellipsis-v" />
            </Link>
            <div className="dropdown-menu dropdown-menu-right">
              <Link
                href="#"
              
                data-bs-toggle="modal"
                data-bs-target="#add_reason"
              >
                <i className="ti ti-edit text-blue" /> Edit
              </Link>
  
              <Link
                className="dropdown-item"
                href="#"
                data-bs-toggle="modal"
                data-bs-target="#delete_reason"
              >
                <i className="ti ti-trash text-danger"></i> Delete
              </Link>
            </div>
          </div>
        ),
      },
    ];
  
    return (
      <>
  {/* Page Wrapper */}
  <div className="page-wrapper">
    <div className="content">
      <div className="row">
        <div className="col-md-12">
          {/* Page Header */}
          <div className="page-header">
            <div className="row align-items-center">
              <div className="col-sm-8">
                <h4 className="page-title">
                  Lost Reason <span className="count-title">123</span>
                </h4>
              </div>
              <div className="col-sm-4 text-sm-end">
                <div className="head-icons">
                  <CollapseHeader/>
                </div>
              </div>
            </div>
          </div>
          {/* /Page Header */}
          <div className="card">
            <div className="card-header">
              {/* Search */}
              <div className="row align-items-center">
                <div className="col-sm-4">
                  <div className="icon-form mb-3 mb-sm-0">
                    <span className="form-icon">
                      <i className="ti ti-search" />
                    </span>
                    <input
                      type="text"
                      className="form-control"
                      placeholder="Search Lost Reason"
                    />
                  </div>
                </div>
                <div className="col-sm-8">
                  <div className="text-sm-end">
                    <Link
                      href="#"
                      className="btn btn-primary"
                      data-bs-toggle="modal"
                      data-bs-target="#add_reason"
                    >
                      <i className="ti ti-square-rounded-plus me-2" />
                      Add New Reason
                    </Link>
                  </div>
                </div>
              </div>
              {/* /Search */}
            </div>
            <div className="card-body">
              {/* Reason List */}
              <div className="table-responsive custom-table">
              <Table columns={columns} dataSource={data} />
              </div>
              <div className="row align-items-center">
                <div className="col-md-6">
                  <div className="datatable-length" />
                </div>
                <div className="col-md-6">
                  <div className="datatable-paginate" />
                </div>
              </div>
              {/* /Reason List */}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {/* /Page Wrapper */}
  {/* Add New Reason */}
  <div className="modal fade" id="add_reason" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">Add New Reason</h5>
          <button
            className="btn-close custom-btn-close border p-1 me-0 text-dark"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <form action="#">
          <div className="modal-body">
            <div className="mb-3">
              <label className="col-form-label">
                Reason <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-0">
              <label className="col-form-label">Status</label>
              <div className="d-flex align-items-center">
                <div className="me-2">
                  <input
                    type="radio"
                    className="status-radio"
                    id="add-active"
                    name="status"
                    defaultChecked
                  />
                  <label htmlFor="add-active">Active</label>
                </div>
                <div>
                  <input
                    type="radio"
                    className="status-radio"
                    id="add-inactive"
                    name="status"
                  />
                  <label htmlFor="add-inactive">Inactive</label>
                </div>
              </div>
            </div>
          </div>
          <div className="modal-footer">
            <div className="d-flex align-items-center justify-content-end m-0">
              <Link
                href="#"
                className="btn btn-light me-2"
                data-bs-dismiss="modal"
              >
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Create
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {/* /Add New Reason */}
  {/* Edit Reason */}
  <div className="modal fade" id="edit_reason" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">Edit Reason</h5>
          <button
            className="btn-close custom-btn-close border p-1 me-0 text-dark"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <form action="#">
          <div className="modal-body">
            <div className="mb-3">
              <label className="col-form-label">
                Reason <span className="text-danger">*</span>
              </label>
              <input
                type="text"
                className="form-control"
                defaultValue="Client went silent"
              />
            </div>
            <div className="mb-0">
              <label className="col-form-label">Status</label>
              <div className="d-flex align-items-center">
                <div className="me-2">
                  <input
                    type="radio"
                    className="status-radio"
                    id="edit-active"
                    name="status"
                    defaultChecked
                  />
                  <label htmlFor="edit-active">Active</label>
                </div>
                <div>
                  <input
                    type="radio"
                    className="status-radio"
                    id="edit-inactive"
                    name="status"
                  />
                  <label htmlFor="edit-inactive">Inactive</label>
                </div>
              </div>
            </div>
          </div>
          <div className="modal-footer">
            <div className="d-flex align-items-center justify-content-end m-0">
              <Link
                href="#"
                className="btn btn-light me-2"
                data-bs-dismiss="modal"
              >
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Save Changes
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {/* /Edit Reason */}
  {/* Delete Reason */}
  <div className="modal fade" id="delete_reason" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-body">
          <div className="text-center">
            <div className="avatar avatar-xl bg-danger-light rounded-circle mb-3">
              <i className="ti ti-trash-x fs-36 text-danger" />
            </div>
            <h4 className="mb-2">Remove Reason?</h4>
            <p className="mb-0">AAre you sure you want to remove it.</p>
            <div className="d-flex align-items-center justify-content-center mt-4">
              <Link
                href="#"
                className="btn btn-light me-2"
                data-bs-dismiss="modal"
              >
                Cancel
              </Link>
              <Link href="#" data-bs-dismiss="modal" className="btn btn-danger">
                Yes, Delete it
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {/* /Delete Reason */}
</>

    );
}

export default LostReason
