// angular/angular/src/app/feature-module/ui-interface/forms/layouts/form-vertical/form-vertical.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../../../shared/routes/routes';
interface data {
  value: string;
}
@Component({
    selector: 'app-form-vertical',
    templateUrl: './form-vertical.component.html',
    styleUrls: ['./form-vertical.component.scss'],
    standalone: false
})
export class FormVerticalComponent {
  public routes = routes;
  public selectedValue1 = ''
  public selectedValue2 = '' ;
  public selectedValue3 = '' ;


  selectedList1: data[] = [
    {value: 'Select'},
    {value: 'A+'},
    {value: 'O+'},
    {value: 'B+'},
    {value: 'AB+'},
  ];
  selectedList2: data[] = [
    {value: 'Select State'},
    {value: 'California'},
    {value: 'Texas'},
    {value: 'Florida'},
  ];
  selectedList3: data[] = [
    {value: 'Select Country'},
    {value: 'USA'},
    {value: 'France'},
    {value: 'India'},
    {value: 'Spain'},
  ];
   

 

}

<!-- Page Header -->
<div class="page-header">
  <div class="row">
    <div class="col">
      <h3 class="page-title">Vertical Form</h3>
    </div>
  </div>
</div>
<!-- /Page Header -->

<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Basic Form</h5>
      </div>
      <div class="card-body">
        <form action="#">
          <div class="mb-3">
             <label class="form-label" for="last">First Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="first">First Name</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Email Address</label>
            <input type="email" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Username</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Password</label>
            <input type="password" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Repeat Password</label>
            <input type="password" class="form-control">
          </div>
          <div class="text-end">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Address Form</h5>
      </div>
      <div class="card-body">
        <form action="#">
          <div class="mb-3">
            <label class="form-label" for="tag">Address Line 1</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Address Line 2</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">City</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">State</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Country</label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="form-label" for="tag">Postal Code</label>
            <input type="text" class="form-control">
          </div>
          <div class="text-end">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Two Column Vertical Form</h5>
      </div>
      <div class="card-body">
        <form action="#">
          <h5 class="card-title">Personal Information</h5>
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                 <label class="form-label" for="last">First Name</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="first">First Name</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Blood Group</label>
                <mat-select [(ngModel)]="selectedValue1" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"  placeholder="Select">
                  @for (data of selectedList1; track data) {
                    <mat-option [value]="data.value">
                      {{data.value}}
                    </mat-option>
                  }
                </mat-select>
              </div>
              <div class="mb-3">
                <label class="d-block" for="gender">Gender:</label>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="gender" id="gender_male" value="option1">
                  <label class="form-check-label" for="gender_male">Male</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="gender" id="gender_female" value="option2">
                  <label class="form-check-label" for="gender_female">Female</label>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label class="form-label" for="tag">Username</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Email</label>
                <input type="text" class="form-control">
              </div>

              <div class="mb-3">
                <label class="form-label" for="tag">Password</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Repeat Password</label>
                <input type="text" class="form-control">
              </div>
            </div>
          </div>
          <h5 class="card-title">Postal Address</h5>
          <div class="row">
            <div class="col-md-6">
              <div class="mb-3">
                <label class="form-label" for="tag">Address Line 1</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Address Line 2</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">State</label>
                <input type="text" class="form-control">
              </div>
            </div>
            <div class="col-md-6">
              <div class="mb-3">
                <label class="form-label" for="tag">City</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Country</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Postal Code</label>
                <input type="text" class="form-control">
              </div>
            </div>
          </div>
          <div class="text-end">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Two Column Vertical Form</h5>
      </div>
      <div class="card-body">
        <form action="#">
          <div class="row">
            <div class="col-md-6">
              <h5 class="card-title">Personal details</h5>
              <div class="mb-3">
                <label class="form-label" for="tag">Name:</label>
                <input type="text" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Password:</label>
                <input type="password" class="form-control">
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">State:</label>
                <mat-select [(ngModel)]="selectedValue2" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"  placeholder="Select State">
                  @for (data of selectedList2; track data) {
                    <mat-option [value]="data.value">
                      {{data.value}}
                    </mat-option>
                  }
                </mat-select>
              </div>
              <div class="mb-3">
                <label class="form-label" for="tag">Your Message:</label>
                <textarea rows="5" cols="5" class="form-control" placeholder="Enter message"></textarea>
              </div>
            </div>
            <div class="col-md-6">
              <h5 class="card-title">Personal details</h5>
              <div class="row">
                <div class="col-md-6">
                  <div class="mb-3">
                    <label class="form-label" for="tag">First Name:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="mb-3">
                    <label class="form-label" for="tag">Last Name:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="mb-3">
                    <label class="form-label" for="tag">Email:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="mb-3">
                    <label class="form-label" for="tag">Phone:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="mb-3">
                    <label class="form-label" for="tag">Address line:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="mb-3">
                    <label class="form-label" for="tag">Country:</label>
                    <mat-select [(ngModel)]="selectedValue3" [ngModelOptions]="{standalone: true}" class="select custom-mat-select"  placeholder="Select Country">
                      @for (data of selectedList3; track data) {
                        <mat-option [value]="data.value">
                          {{data.value}}
                        </mat-option>
                      }
                    </mat-select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="mb-3">
                    <label for="state">State/Province:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="mb-3">
                    <label class="form-label" for="tag">ZIP code:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="mb-3">
                    <label class="form-label" for="tag">City:</label>
                    <input type="text" class="form-control">
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="text-end">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xl-6">
    <div class="card">
      <div class="card-header justify-content-between">
        <div class="card-title">
          Vertical Forms with icon
        </div>

      </div>
      <div class="card-body">
        <div class="mb-3">
          <label for="form-text1" class="form-label fs-14">Enter name</label>
          <div class="input-group">
            <div class="input-group-text"><i class="feather icon-user feather-user"></i></div>
            <input type="text" class="form-control" id="form-text1" placeholder="">
          </div>
        </div>
        <div class="mb-3">
          <label for="form-password1" class="form-label fs-14">Enter
            Password</label>
          <div class="input-group">
            <div class="input-group-text"><i class="feather icon-lock feather-lock"></i></div>
            <input type="password" class="form-control" id="form-password1" placeholder="">
          </div>
        </div>
        <div class="mb-3">
          <label for="form-password1" class="form-label fs-14">Enter Repeat Password</label>
          <div class="input-group">
            <div class="input-group-text"><i class="feather-lock"></i></div>
            <input type="password" class="form-control" id="form-password1" placeholder="">
          </div>
        </div>
        <button class="btn btn-primary" type="submit">Submit</button>
      </div>

    </div>
  </div>

  <div class="col-xl-6">
    <div class="card">
      <div class="card-header justify-content-between">
        <div class="card-title">
          Horizontal form label sizing
        </div>

      </div>
      <div class="card-body">
        <div class="mb-3">
          <label for="colFormLabelSm" class="col-form-label col-form-label-sm">Email</label>
          <input type="email" class="form-control form-control-sm" id="colFormLabelSm" placeholder="col-form-label-sm">
        </div>
        <div class="mb-3">
          <label for="colFormLabel" class="col-form-label">Email</label>
          <input type="email" class="form-control" id="colFormLabel" placeholder="col-form-label">
        </div>
        <div>
          <label for="colFormLabelLg" class="col-form-label col-form-label-lg">Email</label>
          <input type="email" class="form-control form-control-lg" id="colFormLabelLg" placeholder="col-form-label-lg">
        </div>
      </div>

    </div>
  </div>
</div>

// nextjs/nextjs/template/src/components/uiinterface/forms/formelements/layouts/form-vertical.tsx
"use client";
/* eslint-disable @next/next/no-img-element */

import React from "react";
import Link from "next/link";
import Select from "react-select";
import { all_routes } from "@/data/all_routes";


const FormVerticalComponent = () => {
  const routes = all_routes;
  const bloodgroup = [
    { value: "Select", label: "Select" },
    { value: "A+", label: "A+" },
    { value: "O+", label: "O+" },
    { value: "B+", label: "B+" },
    { value: "AB+", label: "AB+" },
  ];
  const statelist = [
    { value: "Select State", label: "Select State" },
    { value: "California", label: "California" },
    { value: "Texas", label: "Texas" },
    { value: "Florida", label: "Florida" },
  ];
  const countrylist = [
    { value: "Select Country", label: "Select Country" },
    { value: "USA", label: "USA" },
    { value: "France", label: "France" },
    { value: "India", label: "India" },
    { value: "Spain", label: "Spain" },
  ];
  return (
    <div>
      <div className="page-wrapper cardhead">
        <div className="content container-fluid">
          {/* Page Header */}
          <div className="page-header">
            <div className="row">
              <div className="col">
                <h3 className="page-title">Vertical Form</h3>
                <ul className="breadcrumb">
                  <li className="breadcrumb-item">
                    <Link href={routes.dealsDashboard}>Dashboard</Link>
                  </li>
                  <li className="breadcrumb-item active">Vertical Form</li>
                </ul>
              </div>
            </div>
          </div>
          {/* /Page Header */}
          <div className="row">
            <div className="col-md-6">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Basic Form</h5>
                </div>
                <div className="card-body">
                  <form action="#">
                    <div className="mb-3">
                      <label className="form-label">First Name</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Last Name</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Email Address</label>
                      <input type="email" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Username</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Password</label>
                      <input type="password" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Repeat Password</label>
                      <input type="password" className="form-control" />
                    </div>
                    <div className="text-end">
                      <Link href="#" className="btn btn-primary">
                        Submit
                      </Link>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            <div className="col-md-6">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Address Form</h5>
                </div>
                <div className="card-body">
                  <form action="#">
                    <div className="mb-3">
                      <label className="form-label">Address Line 1</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Address Line 2</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">City</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">State</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Country</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="mb-3">
                      <label className="form-label">Postal Code</label>
                      <input type="text" className="form-control" />
                    </div>
                    <div className="text-end">
                      <Link href="#" className="btn btn-primary">
                        Submit
                      </Link>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-12">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Two Column Vertical Form</h5>
                </div>
                <div className="card-body">
                  <form action="#">
                    <h5 className="card-title">Personal Information</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <div className="mb-3">
                          <label className="form-label">First Name</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Last Name</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Blood Group</label>
                          <Select classNamePrefix="react-select"
                            className="select"
                            options={bloodgroup}
                            placeholder="Select"
                          />
                        </div>
                        <div className="mb-3">
                          <label className="d-block">Gender:</label>
                          <div className="form-check form-check-inline">
                            <input
                              className="form-check-input"
                              type="radio"
                              name="gender"
                              id="gender_male"
                              defaultValue="option1"
                            />
                            <label
                              className="form-check-label"
                              htmlFor="gender_male"
                            >
                              Male
                            </label>
                          </div>
                          <div className="form-check form-check-inline">
                            <input
                              className="form-check-input"
                              type="radio"
                              name="gender"
                              id="gender_female"
                              defaultValue="option2"
                            />
                            <label
                              className="form-check-label"
                              htmlFor="gender_female"
                            >
                              Female
                            </label>
                          </div>
                        </div>
                      </div>
                      <div className="col-md-6">
                        <div className="mb-3">
                          <label className="form-label">Username</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Email</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Password</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Repeat Password</label>
                          <input type="text" className="form-control" />
                        </div>
                      </div>
                    </div>
                    <h5 className="card-title">Postal Address</h5>
                    <div className="row">
                      <div className="col-md-6">
                        <div className="mb-3">
                          <label className="form-label">Address Line 1</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Address Line 2</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">State</label>
                          <input type="text" className="form-control" />
                        </div>
                      </div>
                      <div className="col-md-6">
                        <div className="mb-3">
                          <label className="form-label">City</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Country</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Postal Code</label>
                          <input type="text" className="form-control" />
                        </div>
                      </div>
                    </div>
                    <div className="text-end">
                      <Link href="#" className="btn btn-primary">
                        Submit
                      </Link>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-12">
              <div className="card">
                <div className="card-header">
                  <h5 className="card-title">Two Column Vertical Form</h5>
                </div>
                <div className="card-body">
                  <form action="#">
                    <div className="row">
                      <div className="col-md-6">
                        <h5 className="card-title">Personal details</h5>
                        <div className="mb-3">
                          <label className="form-label">Name:</label>
                          <input type="text" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Password:</label>
                          <input type="password" className="form-control" />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">State:</label>
                          <Select classNamePrefix="react-select"
                            className="select"
                            options={statelist}
                            placeholder="Select"
                          />
                        </div>
                        <div className="mb-3">
                          <label className="form-label">Your Message:</label>
                          <textarea
                            rows={5}
                            cols={5}
                            className="form-control"
                            placeholder="Enter message"
                            defaultValue={""}
                          />
                        </div>
                      </div>
                      <div className="col-md-6">
                        <h5 className="card-title">Personal details</h5>
                        <div className="row">
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label className="form-label">First Name:</label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label className="form-label">Last Name:</label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label className="form-label">Email:</label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label className="form-label">Phone:</label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-md-12">
                            <div className="mb-3">
                              <label className="form-label">
                                Address line:
                              </label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label className="form-label">Country:</label>
                              <Select classNamePrefix="react-select"
                                className="select"
                                options={countrylist}
                                placeholder="Select"
                              />
                            </div>
                          </div>
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label>State/Province:</label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                        </div>
                        <div className="row">
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label className="form-label">ZIP code:</label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                          <div className="col-md-6">
                            <div className="mb-3">
                              <label className="form-label">City:</label>
                              <input type="text" className="form-control" />
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="text-end">
                      <Link href="#" className="btn btn-primary">
                        Submit
                      </Link>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-xl-6">
              <div className="card">
                <div className="card-header justify-content-between">
                  <div className="card-title">Vertical Forms with icon</div>
                </div>
                <div className="card-body">
                  <div className="mb-3">
                    <label htmlFor="form-text1" className="form-label fs-14">
                      Enter name
                    </label>
                    <div className="input-group">
                      <div className="input-group-text">
                        <i className="feather-user" />
                      </div>
                      <input
                        type="text"
                        className="form-control"
                        id="form-text1"
                        placeholder=""
                      />
                    </div>
                  </div>
                  <div className="mb-3">
                    <label
                      htmlFor="form-password1"
                      className="form-label fs-14"
                    >
                      Enter Password
                    </label>
                    <div className="input-group">
                      <div className="input-group-text">
                        <i className="feather-lock" />
                      </div>
                      <input
                        type="password"
                        className="form-control"
                        id="form-password1"
                        placeholder=""
                      />
                    </div>
                  </div>
                  <div className="mb-3">
                    <label
                      htmlFor="form-password1"
                      className="form-label fs-14"
                    >
                      Enter Repeat Password
                    </label>
                    <div className="input-group">
                      <div className="input-group-text">
                        <i className="feather-lock" />
                      </div>
                      <input
                        type="password"
                        className="form-control"
                        id="form-password1"
                        placeholder=""
                      />
                    </div>
                  </div>
                  <Link className="btn btn-primary" href="#">
                    Submit
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-xl-6">
              <div className="card">
                <div className="card-header justify-content-between">
                  <div className="card-title">Horizontal form label sizing</div>
                </div>
                <div className="card-body">
                  <div className="mb-3">
                    <label
                      htmlFor="colFormLabelSm"
                      className="col-form-label col-form-label-sm"
                    >
                      Email
                    </label>
                    <input
                      type="email"
                      className="form-control form-control-sm"
                      id="colFormLabelSm"
                      placeholder="col-form-label-sm"
                    />
                  </div>
                  <div className="mb-3">
                    <label htmlFor="colFormLabel" className="col-form-label">
                      Email
                    </label>
                    <input
                      type="email"
                      className="form-control"
                      id="colFormLabel"
                      placeholder="col-form-label"
                    />
                  </div>
                  <div>
                    <label
                      htmlFor="colFormLabelLg"
                      className="col-form-label col-form-label-lg"
                    >
                      Email
                    </label>
                    <input
                      type="email"
                      className="form-control form-control-lg"
                      id="colFormLabelLg"
                      placeholder="col-form-label-lg"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FormVerticalComponent;
