// nextjs/nextjs/template/src/components/auth/register.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React, { useState } from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
type PasswordField = 'password' | 'confirmPassword';

const Register = () => {
  const route = all_routes;
  const [passwordVisibility, setPasswordVisibility] = useState({
    password: false,
    confirmPassword: false,
  });

  const togglePasswordVisibility = (field: PasswordField) => {
    setPasswordVisibility((prevState) => ({
      ...prevState,
      [field]: !prevState[field],
    }));
  };
  return (
    <div className="account-content">
  <div className="d-flex flex-wrap w-100 vh-100 overflow-hidden account-bg-02">
    <div className="d-flex align-items-center justify-content-center flex-wrap vh-100 overflow-auto p-4 w-50 bg-backdrop">
      <form  className="flex-fill">
        <div className="mx-auto mw-450">
          <div className="text-center mb-4">
            <img src="assets/img/logo.svg" className="img-fluid" alt="Logo" />
          </div>
          <div className="mb-4">
            <h4 className="mb-2 fs-20">Register</h4>
            <p>Create new CRMS account</p>
          </div>
          <div className="mb-3">
            <label className="col-form-label">Name</label>
            <div className="position-relative">
              <span className="input-icon-addon">
                <i className="ti ti-user" />
              </span>
              <input type="text" defaultValue="" className="form-control" />
            </div>
          </div>
          <div className="mb-3">
            <label className="col-form-label">Email Address</label>
            <div className="position-relative">
              <span className="input-icon-addon">
                <i className="ti ti-mail" />
              </span>
              <input type="text" defaultValue="" className="form-control" />
            </div>
          </div>
          <div className="mb-3">
            <label className="col-form-label">Password</label>
            <div className="pass-group">
              <input
                    type={passwordVisibility.password ? "text" : "password"}
                    className="pass-input form-control"
                  />
                  <span
                    className={`ti toggle-passwords ${
                      passwordVisibility.password ? "ti-eye" : "ti-eye-off"
                    }`}
                    onClick={() => togglePasswordVisibility("password")}
                  ></span>
            </div>
          </div>
          <div className="mb-3">
            <label className="col-form-label">Confirm Password</label>
            <div className="pass-group">
              <input
                    type={
                      passwordVisibility.confirmPassword ? "text" : "password"
                    }
                    className="pass-input form-control"
                  />
                  <span
                    className={`ti toggle-passwords ${
                      passwordVisibility.confirmPassword
                        ? "ti-eye"
                        : "ti-eye-off"
                    }`}
                    onClick={() => togglePasswordVisibility("confirmPassword")}
                  ></span>
            </div>
          </div>
          <div className="d-flex align-items-center justify-content-between mb-3">
            <div className="form-check form-check-md d-flex align-items-center">
              <input
                className="form-check-input"
                type="checkbox"
                defaultValue=""
                id="checkebox-md"
                defaultChecked
              />
              <label className="form-check-label" htmlFor="checkebox-md">
                I agree to the{" "}
                <Link
                  href="#"
                  className="text-primary link-hover"
                >
                  Terms &amp; Privacy
                </Link>
                
              </label>
            </div>
          </div>
          <div className="mb-3">
           
            <Link href={route.login} className="btn btn-primary w-100">
                  Sign Up
                </Link>
          </div>
          <div className="mb-3">
            <h6>
              Already have an account?{" "}
              <Link href={route.login} className="text-purple link-hover">
                {" "}
                Sign In Instead
              </Link>
            </h6>
          </div>
          <div className="form-set-login or-text mb-3">
            <h4>OR</h4>
          </div>
          <div className="d-flex align-items-center justify-content-center flex-wrap mb-3">
            <div className="text-center me-2 flex-fill">
              <Link
                href="#"
                className="br-10 p-2 px-4 btn bg-pending  d-flex align-items-center justify-content-center"
              >
                <img
                  className="img-fluid m-1"
                  src="assets/img/icons/facebook-logo.svg"
                  alt="Facebook"
                />
              </Link>
            </div>
            <div className="text-center me-2 flex-fill">
              <Link
                href="#"
                className="br-10 p-2 px-4 btn bg-white d-flex align-items-center justify-content-center"
              >
                <img
                  className="img-fluid  m-1"
                  src="assets/img/icons/google-logo.svg"
                  alt="Facebook"
                />
              </Link>
            </div>
            <div className="text-center flex-fill">
              <Link
                href="#"
                className="bg-dark br-10 p-2 px-4 btn btn-dark d-flex align-items-center justify-content-center"
              >
                <img
                  className="img-fluid  m-1"
                  src="assets/img/icons/apple-logo.svg"
                  alt="Apple"
                />
              </Link>
            </div>
          </div>
          <div className="text-center">
            <p className="fw-medium text-gray">Copyright © 2025 - CRMS</p>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

  );
};

export default Register;

// angular/angular/src/app/auth/register/register.component.ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Component } from '@angular/core';
import { routes } from '../../../shared/routes/routes';
import { Router } from '@angular/router';

@Component({
    selector: 'app-register',
    templateUrl: './register.component.html',
    styleUrl: './register.component.scss',
    standalone: false
})
export class RegisterComponent {
  public routes = routes
  constructor(private router: Router) {}

  public navigate() {
    this.router.navigate([routes.login]);
  }
  public password : boolean[] = [false];

  public togglePassword(index: any){
    this.password[index] = !this.password[index]
  }
}

<div class="account-content">
    <div class="login-wrapper account-bg register-bg">
        <div class="login-content">
            <form >
                <div class="login-user-info">
                    <div class="login-logo">
                       <img src="assets/img/logo.svg" class="img-fluid" alt="Logo">
                   </div>
                   <div class="login-heading">
                       <h4>Register</h4>
                       <p>Create new CRMS account</p>
                   </div>
                   <div class="form-wrap">
                       <label class="col-form-label" for="name">Name</label>
                       <div class="form-wrap-icon">
                           <input type="text" class="form-control">
                           <i class="ti ti-user"></i>
                       </div>
                   </div>
                   <div class="form-wrap">
                       <label class="col-form-label" for="email">Email Address</label>
                       <div class="form-wrap-icon">
                           <input type="text" class="form-control">
                           <i class="ti ti-mail"></i>
                       </div>
                   </div>
                   <div class="form-wrap">
                       <label class="col-form-label" for="Password">Password</label>
                       <div class="pass-group">
                        <input [type]="password[1] ? 'text' : 'password' " class="pass-input form-control">
                        <span class="ti toggle-password " [ngClass]=" password[1] ? 'ti-eye' : 'ti-eye-off'" (click)="togglePassword(1)"  (keydown.enter)="togglePassword(1)"
                        tabindex="0"></span>
                    </div>
                   </div>
                   <div class="form-wrap">
                       <label class="col-form-label" for="reason">Confirm Password</label>
                       <div class="pass-group">
                        <input [type]="password[2] ? 'text' : 'password' " class="pass-input form-control">
                        <span class="ti toggle-password " [ngClass]=" password[2] ? 'ti-eye' : 'ti-eye-off'" (click)="togglePassword(2)"  (keydown.enter)="togglePassword(2)"
                        tabindex="0"></span>
                       </div>
                   </div>
                   <div class="form-wrap form-wrap-checkbox">
                       <div class="custom-control custom-checkbox">
                            <label class="check">
                                <input type="checkbox">
                                <span class="box"></span>
                                I agree to the <a href="javascript:void(0);" class="forgot-link ms-1">Terms & Privacy</a>
                            </label>
                       </div>
                   </div>
                   <div class="form-wrap">
                       <button type="submit" class="btn btn-primary" (click)="navigate()">Sign Up</button>
                   </div>
                   <div class="login-form">
                       <h6>Already have an account?<a [routerLink]="routes.login" class="hover-a"> Sign In Instead</a></h6>
                   </div>
                   <div class="form-set-login or-text">
                       <h4>OR</h4>
                   </div>
                   <div class="login-social-link">
                       <ul class="nav">
                           <li>
                               <a href="javascript:void(0);" class="facebook-logo">
                                   <img src="assets/img/icons/facebook-logo.svg" alt="Facebook">
                               </a>
                           </li>
                           <li>
                               <a href="javascript:void(0);">
                                   <img src="assets/img/icons/google-logo.svg" alt="Google">
                               </a>
                           </li>
                           <li>
                               <a href="javascript:void(0);" class="apple-logo">
                                   <img src="assets/img/icons/apple-logo.svg" alt="Apple">
                               </a>
                           </li>
                       </ul>
                       <div class="copyright-text">
                           <p>Copyright &copy;2024 - CRMS</p>
                       </div>
                   </div>
               </div>
            </form>
        </div>
    </div>
</div>
