// nextjs/nextjs/template/src/components/settings/appSettings/invoiceSettings.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import Select from "react-select";
import CollapseHeader from "../../../core/common/collapse-header";
const route = all_routes;
const InvoiceSettingsComponent = () => {
  const options1 = [
    { value: "5", label: "5" },
    { value: "7", label: "7" },
  ];

  const options2 = [
    { value: "roundoff-up", label: "Roundoff Up" },
    { value: "roundoff-down", label: "Roundoff Down" },
  ];
  return (
    <div className="page-wrapper">
      <div className="content">
        <div className="row">
          <div className="col-md-12">
            {/* Page Header */}
            <div className="page-header">
              <div className="row align-items-center">
                <div className="col-8">
                  <h4 className="page-title">Settings</h4>
                </div>
                <div className="col-4 text-end">
                  <div className="head-icons">
                    <CollapseHeader />
                  </div>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Settings Menu */}
            <div className="card">
              <div className="card-body pb-0 pt-2">
              <ul className="nav nav-tabs nav-tabs-bottom">
                    <li className="nav-item me-3">
                      <Link href={route.profile} className="nav-link px-0 ">
                        <i className="ti ti-settings-cog" /> General Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.companySettings}
                        className="nav-link px-0 "
                      >
                        <i className="ti ti-world-cog" /> Website Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.invoiceSettings}
                        className="nav-link px-0 active"
                      >
                        <i className="ti ti-apps" /> App Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link href={route.emailSettings} className="nav-link px-0 ">
                        <i className="ti ti-device-laptop" /> System Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.paymentGateways}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-moneybag" /> Financial Settings
                      </Link>
                    </li>
                    <li className="nav-item ">
                      <Link href={route.storage} className="nav-link px-0 ">
                        <i className="ti ti-flag-cog" /> Other Settings
                      </Link>
                    </li>
                  </ul>
              </div>
            </div>
            {/* /Settings Menu */}
            <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">App Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
            <Link href={route.invoiceSettings} className="fw-medium active">
              Invoice Settings
            </Link>
            <Link href={route.printers} className="fw-medium">
              Printer
            </Link>
            <Link href={route.customFields} className="fw-medium">
              Custom Fields
            </Link>
          </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Invoice Settings */}
    <div className="card">
      <div className="card-body">
        <h4 className="fw-semibold mb-3">Invoice Settings</h4>
        <form >
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Logo</h6>
                <p>Upload logo of your company to display in invoice</p>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="profile-upload">
                  <div className="profile-upload-img">
                    <span>
                      <i className="ti ti-photo" />
                    </span>
                    <img
                      id="ImgPreview"
                      src="assets/img/logo.svg"
                      alt="img"
                      className="preview1"
                    />
                    <button
                      type="button"
                      id="removeImage1"
                      className="profile-remove"
                    >
                      <i className="feather-x" />
                    </button>
                  </div>
                  <div className="profile-upload-content">
                    <label className="profile-upload-btn">
                      <i className="ti ti-file-broken" /> Upload File
                      <input type="file" id="imag" className="input-img" />
                    </label>
                    <p>
                      Upload Logo of your company to display in website(JPG or
                      PNG). Max size of 800K
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Prefix</h6>
                <p>Add prefix to your invoice</p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="mb-3">
                <input
                  type="text"
                  className="form-control"
                  defaultValue="INV-"
                />
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Due</h6>
                <p>Select due date to display in invoice</p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="mb-3">
                <div className="d-flex align-items-center inv-days">
                  <div className="select-drop">
                  <Select
                                     classNamePrefix="react-select"
                                    className="select"
                                    defaultValue={options1[0]}
                                    options={options1}
                                  />
                  </div>
                  <p>Days</p>
                </div>
              </div>
            </div>
          </div>
          <div className="row align-items-center">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Round Off</h6>
                <p>Value roundoff in invoice</p>
              </div>
            </div>
            <div className="col-md-4">
              <div className="mb-3">
                <div className="d-flex align-items-center">
                  <div className="form-check form-switch me-2">
                    <input
                      className="form-check-input"
                      type="checkbox"
                      role="switch"
                      defaultChecked
                    />
                  </div>
                  <div className="select-drop w-100">
                  <Select
                                    className="select"
                                    defaultValue={options2[0]}
                                    options={options2}
                                  />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="row align-items-center">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Show Company Details</h6>
                <p>Show/hide company details in invoice</p>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="form-check form-switch">
                  <input
                    className="form-check-input"
                    type="checkbox"
                    role="switch"
                    defaultChecked
                  />
                </div>
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Header Terms</h6>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="summernote" />
              </div>
            </div>
          </div>
          <div className="row">
            <div className="col-md-6">
              <div className="mb-3">
                <h6 className="fw-medium">Invoice Footer Terms</h6>
              </div>
            </div>
            <div className="col-md-6">
              <div className="mb-3">
                <div className="summernote" />
              </div>
            </div>
          </div>
          <div>
            <Link href="#" className="btn btn-light me-2">
              Cancel
            </Link>
            <button type="button" className="btn btn-primary">
              Save Changes
            </button>
          </div>
        </form>
      </div>
    </div>
    {/* /Invoice Settings */}
  </div>
</div>

          </div>
        </div>
      </div>
    </div>
  );
};

export default InvoiceSettingsComponent;

// angular/angular/src/app/feature-module/settings/app-settings/invoice-settings/invoice-settings.component.ts
import { Component } from '@angular/core';
import { routes } from '../../../../../shared/routes/routes';
interface data {
  value: string;
}

@Component({
    selector: 'app-invoice-settings',
    templateUrl: './invoice-settings.component.html',
    styleUrl: './invoice-settings.component.scss',
    standalone: false
})
export class InvoiceSettingsComponent {
  public routes = routes;
  public selectedValue1 = '';
  public selectedValue2 = '';
  selectedList1: data[] = [{ value: '5' }, { value: '6' }, { value: '7' }];
  selectedList2: data[] = [
    { value: 'Round Off Up' },
    { value: 'Round Off Down' },
  ];

  text1: string | undefined;
  text2: string | undefined;
}

<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">

        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h4 class="page-title">Settings</h4>
            </div>
            <div class="col-4 text-end">
              <div class="head-icons">
                <a [routerLink]="routes.invoiceSettings" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-original-title="Refresh" matTooltip="Refresh"><i class="ti ti-refresh-dot"></i></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <!-- Settings Menu -->
        <div class="card">
          <div class="card-body pb-0 pt-2">
            
              <ul class="nav nav-tabs nav-tabs-bottom">
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.generalSettings" class="nav-link px-0">
                    <i class="ti ti-settings-cog me-2"></i>General Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.companySettings" class="nav-link px-0">
                    <i class="ti ti-world-cog me-2"></i>Website Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.invoiceSettings" class="nav-link px-0 active">
                    <i class="ti ti-apps me-2"></i>App Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.emailSettings" class="nav-link px-0">
                    <i class="ti ti-device-laptop me-2"></i>System Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.paymentGatewaySettings" class="nav-link px-0">
                    <i class="ti ti-moneybag me-2"></i>Financial Settings
                  </a>
                </li>
                <li class="nav-item">
                  <a [routerLink] = "routes.storageSettings" class="nav-link px-0">
                    <i class="ti ti-flag-cog me-2"></i>Other Settings
                  </a>
                </li>
              </ul>
            
          </div>
        </div>
        <!-- /Settings Menu -->

        <div class="row">
          <div class="col-xl-3 col-lg-12 theiaStickySidebar">
            <div class="stickybar">
              <!-- Settings Sidebar -->
              <div class="card">
                <div class="card-body">
                  <div class="settings-sidebar">
                    <h4 class="fw-semibold mb-3">App Settings</h4>
                    <div class="list-group list-group-flush settings-sidebar">
                      <a [routerLink] = "routes.invoiceSettings" class="fw-medium active">Invoice Settings</a>
                      <a [routerLink]="routes.printerSettings" class="fw-medium">Printer</a>
                    <a [routerLink]="routes.customFields" class="fw-medium active">Custom Fields</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Settings Sidebar -->
            </div>
          </div>

          <div class="col-xl-9 col-lg-12">

            <!-- Invoice Settings -->
            <div class="card">
              <div class="card-body">
                <h4 class="fw-semibold mb-3">Invoice Settings</h4>
               
                  <form>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Logo</h6>
                          <p>Upload logo of your company to display in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-6">
                          <div class="profile-upload">
                            <div class="profile-upload-img">
                              <span><i class="ti ti-photo"></i></span>
                              <img id="ImgPreview" src="assets/img/logo.svg" alt="img" class="preview1">
                              <button type="button" id="removeImage1" class="profile-remove">
                                <i class="feather-x"></i>
                              </button>
                            </div>
                            <div class="profile-upload-content">
                              <label class="profile-upload-btn">
                                <i class="ti ti-file-broken"></i> Upload File
                                <input type="file" id="imag" class="input-img">
                              </label>
                              <p>Upload Logo of your company to display in website(JPG or PNG). Max size of 800K</p>
                            </div>
                          </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Prefix</h6>
                          <p>Add prefix to your invoice</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <input type="text" class="form-control" value="INV-">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Due</h6>
                          <p>Select due date to display in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <div class="d-flex align-items-center inv-days">
                            <div class="select-drop">
                              <mat-select [(ngModel)]="selectedValue1" [ngModelOptions]="{standalone: true}"
                                class="select custom-mat-select" placeholder="5">
                                @for (data of selectedList1; track data) {
                                <mat-option [value]="data.value">
                                  {{data.value}}
                                </mat-option>
                                }
                              </mat-select>
                            </div>
                            <p>Days</p>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row align-items-center">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Round Off</h6>
                          <p>Value roundoff in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="mb-3">
                          <div class="d-flex align-items-center">
                            <div class="form-check form-switch me-2">
                              <input class="form-check-input" type="checkbox" role="switch" checked>
                            </div>
                            <div class="select-drop w-100">
                              <mat-select [(ngModel)]="selectedValue2" [ngModelOptions]="{standalone: true}"
                                class="select custom-mat-select" placeholder="Round Off Up">
                                @for (data of selectedList2; track data) {
                                <mat-option [value]="data.value">
                                  {{data.value}}
                                </mat-option>
                                }
                              </mat-select>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row align-items-center">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Show Company Details</h6>
                          <p>Show/hide company details in invoice</p>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="mb-3">
                          <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" role="switch" checked>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="mb-3">
                          <h6 class="fw-medium">Invoice Header Terms</h6>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="mb-3">
                          <div class="summernote">
                            <p-editor [(ngModel)]="text1" [ngModelOptions]="{standalone: true}"
                              [style]="{ height: '100px' }"></p-editor>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="fw-medium">
                          <h6>Invoice Footer Terms</h6>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="mb-3">
                          <div class="summernote">
                            <p-editor [(ngModel)]="text2" [ngModelOptions]="{standalone: true}"
                              [style]="{ height: '100px' }"></p-editor>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div >
                      <a href="javascript:void(0);" class="btn btn-light me-3">Cancel</a>
                      <button type="submit" class="btn btn-primary">Save Changes</button>
                    </div>
                  </form>
                
              </div>
            </div>
            <!-- /Invoice Settings -->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
