// nextjs/nextjs/template/src/components/settings/systemSettings/emailSettings.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { all_routes } from "@/data/all_routes";
import Link from "next/link";
import CollapseHeader from '../../../core/common/collapse-header';
const route = all_routes;
const EmailSettingsComponent = () => {
  return (
    <div>
    {/* Page Wrapper */}
    <div className="page-wrapper">
      <div className="content">
        <div className="row">
          <div className="col-md-12">
            {/* Page Header */}
            <div className="page-header">
              <div className="row align-items-center">
                <div className="col-8">
                  <h4 className="page-title">Settings</h4>
                </div>
                <div className="col-4 text-end">
                  <div className="head-icons">
                    <CollapseHeader />
                  </div>
                </div>
              </div>
            </div>
            {/* /Page Header */}
            {/* Settings Menu */}
            <div className="card">
              <div className="card-body pb-0 pt-2">
              <ul className="nav nav-tabs nav-tabs-bottom">
                    <li className="nav-item me-3">
                      <Link href={route.profile} className="nav-link px-0 ">
                        <i className="ti ti-settings-cog" /> General Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.companySettings}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-world-cog" /> Website Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.invoiceSettings}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-apps" /> App Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link href={route.emailSettings} className="nav-link px-0 active">
                        <i className="ti ti-device-laptop" /> System Settings
                      </Link>
                    </li>
                    <li className="nav-item me-3">
                      <Link
                        href={route.paymentGateways}
                        className="nav-link px-0"
                      >
                        <i className="ti ti-moneybag" /> Financial Settings
                      </Link>
                    </li>
                    <li className="nav-item ">
                      <Link href={route.storage} className="nav-link px-0 ">
                        <i className="ti ti-flag-cog" /> Other Settings
                      </Link>
                    </li>
                  </ul>
              </div>
            </div>
            {/* /Settings Menu */}
            <div className="row">
  <div className="col-xl-3 col-lg-12 theiaStickySidebar">
    {/* Settings Sidebar */}
    <div className="card">
      <div className="card-body">
        <div className="settings-sidebar">
          <h4 className="fw-semibold mb-3">Other Settings</h4>
          <div className="list-group list-group-flush settings-sidebar">
            <Link href={route.emailSettings} className="fw-medium active">
              Email Settings
            </Link>
            <Link href={route.smsGateways} className="fw-medium">
              SMS Gateways
            </Link>
            <Link href={route.gdprCookies} className="fw-medium">
              GDPR Cookies
            </Link>
          </div>
        </div>
      </div>
    </div>
    {/* /Settings Sidebar */}
  </div>
  <div className="col-xl-9 col-lg-12">
    {/* Settings Info */}
    <div className="card">
      <div className="card-body">
        <div className="d-flex align-items-center justify-content-between mb-4">
          <h4 className="fs-20">Email Settings</h4>
          <Link
            href="#"
            className="btn-add"
            data-bs-toggle="modal"
            data-bs-target="#add_mail"
          >
            <i className="ti ti-mail" />
          </Link>
        </div>
        <div className="row">
          {/* Email Wrap */}
          <div className="col-md-12">
            {/* PHP Mailer */}
            <div className="border rounded p-3 mb-4">
              <div className="row gy-3">
                <div className="col-sm-5">
                  <div className="d-flex align-items-center">
                    <span className="avatar avtar-lg border me-2 flex-shrink-0">
                      <img
                        src="assets/img/icons/mail-01.svg"
                        className="w-auto h-auto"
                        alt=""
                      />
                    </span>
                    <div>
                      <h6 className="fw-medium mb-1">PHP Mailer</h6>
                      <Link
                        href="#"
                        className="badge bg-soft-success"
                      >
                        Connected
                      </Link>
                    </div>
                  </div>
                </div>
                <div className="col-sm-7">
                  <div className="d-flex align-items-center justify-content-between">
                    <div>
                      <Link
                        href="#"
                        data-bs-toggle="collapse"
                        data-bs-target="#php-mail"
                        className="info-icon me-3 text-default"
                      >
                        <i className="ti ti-info-circle-filled me-1" />
                      </Link>
                      <Link
                        href="#"
                        className="btn btn-light"
                        data-bs-toggle="modal"
                        data-bs-target="#add_phpmail"
                      >
                        <i className="ti ti-tool me-1" />
                        View Integration
                      </Link>
                    </div>
                    <div className="status-toggle">
                      <input
                        type="checkbox"
                        id="mail1"
                        className="check"
                        defaultChecked
                      />
                      <label htmlFor="mail1" className="checktoggle">
                        {" "}
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              <div className="collapse" id="php-mail">
                <div className="mail-collapse">
                  <p>
                    PHPMailer is a third-party PHP library that provides a
                    simple way to send emails in PHP. It offers a range of
                    features that make it a popular alternative to PHP's
                    built-in mail() function, such as support for HTML emails,
                    attachments, and SMTP authentication.
                  </p>
                </div>
              </div>
            </div>
            {/* /PHP Mailer */}
            {/* SMTP */}
            <div className="border rounded p-3 mb-4">
              <div className="row gy-3">
                <div className="col-sm-5">
                  <div className="d-flex align-items-center">
                    <span className="avatar avtar-lg border me-2 flex-shrink-0">
                      <img
                        src="assets/img/icons/mail-02.svg"
                        className="w-auto h-auto"
                        alt=""
                      />
                    </span>
                    <div>
                      <h6 className="fw-medium mb-1">SMTP</h6>
                      <Link
                        href="#"
                        className="badge bg-soft-success"
                      >
                        Connected
                      </Link>
                    </div>
                  </div>
                </div>
                <div className="col-sm-7">
                  <div className="d-flex align-items-center justify-content-between">
                    <div>
                      <Link
                        href="#"
                        className="me-3 text-default"
                      >
                        <i className="ti ti-info-circle-filled me-1" />
                      </Link>
                      <Link
                        href="#"
                        className="btn btn-light"
                        data-bs-toggle="modal"
                        data-bs-target="#add_smtp"
                      >
                        <i className="ti ti-tool me-1" />
                        View Integration
                      </Link>
                    </div>
                    <div className="status-toggle">
                      <input
                        type="checkbox"
                        id="mail2"
                        className="check"
                        defaultChecked
                      />
                      <label htmlFor="mail2" className="checktoggle">
                        {" "}
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /SMTP */}
            {/* SendGrid */}
            <div className="border rounded p-3">
              <div className="row gy-3">
                <div className="col-sm-5">
                  <div className="d-flex align-items-center">
                    <span className="avatar avtar-lg border me-2 flex-shrink-0">
                      <img
                        src="assets/img/icons/mail-03.svg"
                        className="w-auto h-auto"
                        alt=""
                      />
                    </span>
                    <div>
                      <h6 className="fw-medium mb-1">SendGrid</h6>
                      <Link
                        href="#"
                        className="badge bg-soft-purple text-purple"
                      >
                        Not Connected
                      </Link>
                    </div>
                  </div>
                </div>
                <div className="col-sm-7">
                  <div className="d-flex align-items-center justify-content-between">
                    <div>
                      <Link
                        href="#"
                        className="me-3 text-default"
                      >
                        <i className="ti ti-info-circle-filled me-1" />
                      </Link>
                      <Link href="#" className="btn btn-primary">
                        <i className="ti ti-plug-connected me-1" />
                        Connect Now
                      </Link>
                    </div>
                    <div className="status-toggle">
                      <input
                        type="checkbox"
                        id="mail3"
                        className="check"
                        defaultChecked
                      />
                      <label htmlFor="mail3" className="checktoggle">
                        {" "}
                      </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /SendGrid */}
          </div>
          {/* /Email Wrap */}
        </div>
      </div>
    </div>
    {/* /Settings Info */}
  </div>
</div>

          </div>
        </div>
      </div>
    </div>
    {/* /Page Wrapper */}
    <>
  {/* PHP Mailer */}
  <div className="modal fade" id="add_phpmail" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">PHP Mailer</h5>
          <div className="d-flex align-items-center">
            <div className="status-toggle me-2">
              <input
                type="checkbox"
                id="toggle"
                className="check"
                defaultChecked
              />
              <label htmlFor="toggle" className="checktoggle" />
            </div>
            <button
              className="btn-close custom-btn-close border p-1 me-0 text-dark"
              data-bs-dismiss="modal"
              aria-label="Close"
            >
              <i className="ti ti-x" />
            </button>
          </div>
        </div>
        <form >
          <div className="modal-body">
            <div className="mb-3">
              <label className="col-form-label">
                From Email Address <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-3">
              <label className="col-form-label">
                Email Password <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-0">
              <label className="col-form-label">
                From Email Name <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
          </div>
          <div className="modal-footer">
            <div className="d-flex align-items-center justify-content-end m-0">
              <Link
                href="#"
                className="btn btn-light me-2"
                data-bs-dismiss="modal"
              >
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Save
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {/* /PHP Mailer */}
  {/* SMTP */}
  <div className="modal fade" id="add_smtp" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">SMTP</h5>
          <div className="d-flex align-items-center">
            <div className="status-toggle me-2">
              <input
                type="checkbox"
                id="toggle1"
                className="check"
                defaultChecked
              />
              <label htmlFor="toggle1" className="checktoggle" />
            </div>
            <button
              className="btn-close custom-btn-close border p-1 me-0 text-dark"
              data-bs-dismiss="modal"
              aria-label="Close"
            >
              <i className="ti ti-x" />
            </button>
          </div>
        </div>
        <form >
          <div className="modal-body">
            <div className="mb-3">
              <label className="col-form-label">
                From Email Address <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-3">
              <label className="col-form-label">
                Email Password <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-3">
              <label className="col-form-label">
                Email Host <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
            <div className="mb-0">
              <label className="col-form-label">
                Port <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
          </div>
          <div className="modal-footer">
            <div className="d-flex align-items-center justify-content-end m-0">
              <Link
                href="#"
                className="btn btn-light me-2"
                data-bs-dismiss="modal"
              >
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Save
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {/* /SMTP */}
  {/* Test Mail */}
  <div className="modal fade" id="add_mail" role="dialog">
    <div className="modal-dialog modal-dialog-centered">
      <div className="modal-content">
        <div className="modal-header">
          <h5 className="modal-title">Test Mail</h5>
          <button
            className="btn-close custom-btn-close border p-1 me-0 text-dark"
            data-bs-dismiss="modal"
            aria-label="Close"
          >
            <i className="ti ti-x" />
          </button>
        </div>
        <form >
          <div className="modal-body">
            <div className="mb-0">
              <label className="col-form-label">
                Enter Email Address <span className="text-danger">*</span>
              </label>
              <input type="text" className="form-control" />
            </div>
          </div>
          <div className="modal-footer">
            <div className="d-flex align-items-center justify-content-end m-0">
              <Link
                href="#"
                className="btn btn-light me-2"
                data-bs-dismiss="modal"
              >
                Cancel
              </Link>
              <button type="button" data-bs-dismiss="modal" className="btn btn-primary">
                Submit
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  {/* /Test Mail */}
</>

  </div>
  )
}

export default EmailSettingsComponent

// angular/angular/src/app/feature-module/settings/system-settings/email-settings/email-settings.component.ts
import { Component } from '@angular/core';
import { DataService } from '../../../../../shared/data/data.service';
import { routes } from '../../../../../shared/routes/routes';

@Component({
    selector: 'app-email-settings',
    templateUrl: './email-settings.component.html',
    styleUrl: './email-settings.component.scss',
    standalone: false
})
export class EmailSettingsComponent {
  public routes = routes;
  constructor( private data: DataService){}


  
}

<!-- Page Wrapper -->
<div class="page-wrapper">
  <div class="content">
    <div class="row">
      <div class="col-md-12">

        <!-- Page Header -->
        <div class="page-header">
          <div class="row align-items-center">
            <div class="col-8">
              <h4 class="page-title">Settings</h4>
            </div>
            <div class="col-4 text-end">
              <div class="head-icons">
                <a [routerLink] = "routes.emailSettings" data-bs-toggle="tooltip" data-bs-placement="top"
                  data-bs-original-title="Refresh" matTooltip="Refresh"><i class="ti ti-refresh-dot"></i></a>
                <app-collapse-header></app-collapse-header>
              </div>
            </div>
          </div>
        </div>
        <!-- /Page Header -->

        <!-- Settings Menu -->
        <div class="card">
          <div class="card-body pb-0 pt-2">
            <div class="settings-menu">
              <ul class="nav nav-tabs nav-tabs-bottom">
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.generalSettings" class="nav-link px-0">
                    <i class="ti ti-settings-cog"></i> General Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.companySettings" class="nav-link px-0">
                    <i class="ti ti-world-cog"></i> Website Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.invoiceSettings" class="nav-link px-0">
                    <i class="ti ti-apps"></i> App Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.emailSettings" class="nav-link px-0 active">
                    <i class="ti ti-device-laptop"></i> System Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.paymentGatewaySettings" class="nav-link px-0">
                    <i class="ti ti-moneybag"></i> Financial Settings
                  </a>
                </li>
                <li class="nav-item me-3">
                  <a [routerLink] = "routes.storageSettings" class="nav-link px-0">
                    <i class="ti ti-flag-cog"></i> Other Settings
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- /Settings Menu -->

        <div class="row">
          <div class="col-xl-3 col-lg-12 theiaStickySidebar">
            <div class="stickybar">
              <!-- Settings Sidebar -->
              <div class="card">
                <div class="card-body">
                  <div class="settings-sidebar">
                    <h4 class="fw-semibold mb-3">Other Settings</h4>
                    <div class="list-group list-group-flush settings-sidebar">
                      <a [routerLink] = "routes.emailSettings" class="fw-medium active">Email Settings</a>
                      <a [routerLink] = "routes.smsGateway" class="fw-medium">SMS Gateways</a>
                      <a [routerLink] = "routes.gdprSettings" class="fw-medium">GDPR Cookies</a>
                    </div>
                  </div>
                </div>
              </div>
              <!-- /Settings Sidebar -->
            </div>
          </div>

          <div class="col-xl-9 col-lg-12">

           <!-- Settings Info -->
								<div class="card">
									<div class="card-body">
										<div class="d-flex align-items-center justify-content-between mb-4">
											<h4 class="fs-20">Email Settings</h4>
											<a href="javascript:void(0)" class="btn-add" data-bs-toggle="modal" data-bs-target="#add_mail"><i class="ti ti-mail"></i></a>
										</div>
										<div class="row">

											<!-- Email Wrap -->
											<div class="col-md-12">

												<!-- PHP Mailer -->
												<div class="border rounded p-3 mb-4">
													<div class="row gy-3">
														<div class="col-sm-5">
															<div class="d-flex align-items-center">
																<span class="avatar avtar-lg border me-2 flex-shrink-0">
																	<img src="assets/img/icons/mail-01.svg" class="w-auto h-auto" alt="">
																</span>
																<div>
																	<h6 class="fw-medium mb-1">PHP Mailer</h6>
																	<a href="javascript:void(0);" class="badge bg-soft-success">Connected</a>
																</div>
															</div>
														</div>
														<div class="col-sm-7">
															<div class="d-flex align-items-center justify-content-between">
																<div>
																	<a href="javascript:void(0);" data-bs-toggle="collapse" data-bs-target="#php-mail" class="info-icon me-3 text-default"><i class="ti ti-info-circle-filled me-1"></i></a>
																	<a href="javascript:void(0);" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#add_phpmail"><i class="ti ti-tool me-1"></i>View Integration</a>
																</div>
																<div class="status-toggle">
																	<input type="checkbox" id="mail1" class="check" checked="">
																	<label for="mail1" class="checktoggle">	</label>
																</div>
															</div>
														</div>
													</div>
													<div class="collapse" id="php-mail">
														<div class="mail-collapse">
															<p>PHPMailer is a third-party PHP library that provides a simple way to send emails in PHP. It offers a range of features that make it a popular alternative to PHP's built-in mail() function, such as support for HTML emails, attachments, and SMTP authentication.</p>
														</div>
													</div>
												</div>
												<!-- /PHP Mailer -->

												<!-- SMTP -->
												<div class="border rounded p-3 mb-4">
													<div class="row gy-3">
														<div class="col-sm-5">
															<div class="d-flex align-items-center">
																<span class="avatar avtar-lg border me-2 flex-shrink-0">
																	<img src="assets/img/icons/mail-02.svg" class="w-auto h-auto" alt="">
																</span>
																<div>
																	<h6 class="fw-medium mb-1">SMTP</h6>
																	<a href="javascript:void(0);" class="badge bg-soft-success">Connected</a>
																</div>
															</div>
														</div>
														<div class="col-sm-7">
															<div class="d-flex align-items-center justify-content-between">
																<div>
																	<a href="javascript:void(0);" class="me-3 text-default"><i class="ti ti-info-circle-filled me-1"></i></a>
																	<a href="javascript:void(0);" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#add_smtp"><i class="ti ti-tool me-1"></i>View Integration</a>
																</div>
																<div class="status-toggle">
																	<input type="checkbox" id="mail2" class="check" checked="">
																	<label for="mail2" class="checktoggle">	</label>
																</div>
															</div>
														</div>
													</div>
												</div>
												<!-- /SMTP -->

												<!-- SendGrid -->
												<div class="border rounded p-3">
													<div class="row gy-3">
														<div class="col-sm-5">
															<div class="d-flex align-items-center">
																<span class="avatar avtar-lg border me-2 flex-shrink-0">
																	<img src="assets/img/icons/mail-03.svg" class="w-auto h-auto" alt="">
																</span>
																<div>
																	<h6 class="fw-medium mb-1">SendGrid</h6>
																	<a href="javascript:void(0);" class="badge bg-soft-purple text-purple">Not Connected</a>
																</div>
															</div>
														</div>
														<div class="col-sm-7">
															<div class="d-flex align-items-center justify-content-between">
																<div>
																	<a href="javascript:void(0);" class="me-3 text-default"><i class="ti ti-info-circle-filled me-1"></i></a>
																	<a href="javascript:void(0);" class="btn btn-primary"><i class="ti ti-plug-connected me-1"></i>Connect Now</a>
																</div>
																<div class="status-toggle">
																	<input type="checkbox" id="mail3" class="check" checked="">
																	<label for="mail3" class="checktoggle">	</label>
																</div>
															</div>
														</div>
													</div>
												</div>
												<!-- /SendGrid -->

											</div>
											<!-- /Email Wrap -->

										</div>
									</div>
								</div>
								<!-- /Settings Info -->

          </div>
        </div>

      </div>
    </div>
  </div>
</div>
<!-- /Page Wrapper -->

<!-- PHP Mailer -->
<div class="modal fade" id="add_phpmail" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">PHP Mailer</h5>
        <div class="d-flex align-items-center">
          <div class="status-toggle me-2">
            <input type="checkbox" id="toggle" class="check" checked="">
            <label for="toggle" class="checktoggle"></label>
          </div>
          <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">	
            <i class="ti ti-x"></i>
          </button>
        </div>
      </div>
      <form action="email-settings.html">
        <div class="modal-body">
          <div class="mb-3">
            <label class="col-form-label" for="email">From Email Address <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="col-form-label" for="password">Email Password <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-0">
            <label class="col-form-label" for="emailname">From Email Name <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
        </div>
        <div class="modal-footer">
          <div class="d-flex align-items-center justify-content-end m-0">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /PHP Mailer -->

<!-- SMTP -->
<div class="modal fade" id="add_smtp" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">SMTP</h5>
        <div class="d-flex align-items-center">
          <div class="status-toggle me-2">
            <input type="checkbox" id="toggle1" class="check" checked="">
            <label for="toggle1" class="checktoggle"></label>
          </div>
          <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">	
            <i class="ti ti-x"></i>
          </button>
        </div>
      </div>
      <form action="email-settings.html">
        <div class="modal-body">
          <div class="mb-3">
            <label class="col-form-label" for="email">From Email Address <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="col-form-label"  for="Password">Email Password <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-3">
            <label class="col-form-label"   for="host">Email Host <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
          <div class="mb-0">
            <label class="col-form-label" for="port">Port <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
        </div>
        <div class="modal-footer">
          <div class="d-flex align-items-center justify-content-end m-0">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /SMTP -->

<!-- Test Mail -->
<div class="modal fade" id="add_mail" role="dialog">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Test Mail</h5>
        <button class="btn-close custom-btn-close border p-1 me-0 text-dark" data-bs-dismiss="modal" aria-label="Close">	
          <i class="ti ti-x"></i>
        </button>
      </div>
      <form >
        <div class="modal-body">
          <div class="mb-0">
            <label class="col-form-label" for="reason">Enter Email Address <span class="text-danger">*</span></label>
            <input type="text" class="form-control">
          </div>
        </div>
        <div class="modal-footer">
          <div class="d-flex align-items-center justify-content-end m-0">
            <a href="javascript:void(0);" class="btn btn-light me-2" data-bs-dismiss="modal">Cancel</a>
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- /Test Mail -->
